### ISSUE TITLE
avahi-daemon

### ISSUE THREAD

**Issue by bjwelker** [buanet/docker-iobroker#1]
Damit unter anderem apple homekit funktioniert muss im docker noch der avahi-daemon gestartet werden. Dazu habe ich einfach eine avahi-start.sh mit dem Inhalt 
rm /var/run/dbus/pid                                                                                                             
dbus-daemon --system                                                                                                             
/etc/init.d/avahi-daemon stop                                                                                                    
/etc/init.d/avahi-daemon start
exit 0
im Verzeichniss /opt/iobroker/ angelegt und im startup.sh direkt über dem ./iobroker start via ./avahi-start.sh aufrufen lassen. Damit funktioniert dann alles im Docker :-)

**Comment by buanet** [comment]
Hallo,
danke für die Info. Ich habe den avahi-daemon jetzt integriert.
Wenn ich den Container starte sieht auch alles gut aus. Da ich aber homekit nicht nutze, kann ich schlecht prüfen ob es funktioniert. Vielleicht kannst du ja bei Gelegenheit mal schauen und die neue Version des Docker-Images funktioniert? :)

MfG,
André

**Comment by bjwelker** [comment]
Wenn ich wüsste wie ich das mache ohne das meine Daten in dem alten Container weg sind

**Comment by buanet** [comment]
Danke für den Denkanstoß. Ich hab da mal was vorbereitet: http://forum.iobroker.net/viewtopic.php?f=17&t=5089

MfG,
André

**Comment by Kiter1988** [comment]
> Damit unter anderem apple homekit funktioniert muss im docker noch der avahi-daemon gestartet werden. Dazu habe ich einfach eine avahi-start.sh mit dem Inhalt rm /var/run/dbus/pid dbus-daemon --system /etc/init.d/avahi-daemon stop /etc/init.d/avahi-daemon start exit 0 im Verzeichniss /opt/iobroker/ angelegt und im startup.sh direkt über dem ./iobroker start via ./avahi-start.sh aufrufen lassen. Damit funktioniert dann alles im Docker :-)

Hallo,
kann mir jemand den letzten Teil 
**im startup.sh direkt über dem ./iobroker start via ./avahi-start.sh aufrufen lassen.**
besser erklären ? 
Wo finde ich die startup.sh ? 
In welches Verzeichnis muss diese ? 
Was bedeutet ./iobroker start via ./avahi-start.sh ?

**Comment by buanet** [comment]
@Kiter1988 Schau mal bitte aufs Datum. Diese Info ist 7 Jahre alt! Das ist längst im Docker Image integriert... Siehe Doku zu Umgebungsvariablen:  https://docs.buanet.de/de/iobroker-docker-image/docs/#umgebungsvariablen-env

MfG,
André
