### ISSUE TITLE
host change funktioniert nicht / findet nichts

### ISSUE THREAD

**Issue by mcdhrts** [buanet/docker-iobroker#100]
Hey Andre,
habe heute meinen Container neu aufgebaut und jetzt kommt iobroker nicht mehr hoch.
Laut Log will er den Host Namen ändern und hat dann das Problem das er keine Instanzen findet. Die Instanzen will er dann am Ende mit dem alten Host Namen starten, was nicht geht, passt logischerweise nicht zusammen. 

Hier das Log vom Container, hast du schon mal sowas gesehen?

`-----       Welcome to your ioBroker-container!        -----,
-----          Startupscript is now running.           -----,
-----                Please be patient!                -----,
------------------------------------------------------------,
 ,
------------------------------------------------------------,
-----              Debugging information               -----,
-----                                                  -----,
-----                      System                      -----,
-----               arch:      x86_64                  -----,
-----                                                  -----,
-----                     Versions                     -----,
-----               image:     v4.2.0                  -----,
-----               node:      v10.20.1                -----,
-----               npm:       6.14.4                  -----,
-----                                                  -----,
-----                       ENV                        -----,
-----               PACKAGES:  vi                      -----,
-----               SETGID:    1000                    -----,
-----               SETUID:    1000                    -----,
------------------------------------------------------------,
 ,
------------------------------------------------------------,
-----         Step 1 of 5: Preparing container         -----,
------------------------------------------------------------,
 ,
Installing additional packages is set by ENV.,
The following packages will be installed: vi...,
E: Paket vi kann nicht gefunden werden.,
Done.,
 ,
------------------------------------------------------------,
-----   Step 2 of 5: Detecting ioBroker installation   -----,
------------------------------------------------------------,
 ,
Existing installation of ioBroker detected in /opt/iobroker.,
 ,
------------------------------------------------------------,
-----   Step 3 of 5: Checking ioBroker installation    -----,
------------------------------------------------------------,
 ,
(Re)Setting folder permissions (This might take a while! Please be patient!)...,
Done.,
 ,
Fixing "sudo-bug" by replacing sudo in iobroker with gosu...,
Done.,
 ,
Hostname in ioBroker does not match the hostname of this container.,
Updating hostname to  475d005bacb2...,
No instances found for host "7523cc29b726"!,
Done.,
 ,
------------------------------------------------------------,
-----      Step 4 of 5: Applying special settings      -----,
------------------------------------------------------------,
 ,
Some adapters have special requirements/ settings which can be activated by the use of environment variables.,
For more information take a look at readme.md on Github!,
 ,
------------------------------------------------------------,
-----          Step 5 of 5: ioBroker startup           -----,
------------------------------------------------------------,
 ,
Starting ioBroker...,
 ,
host.475d005bacb2 check instance "system.adapter.admin.0" for host "7523cc29b726",
host.475d005bacb2 check instance "system.adapter.discovery.0" for host "7523cc29b726",
host.475d005bacb2 check instance "system.adapter.info.0" for host "7523cc29b726",
host.475d005bacb2 check instance "system.adapter.telegram.0" for host "7523cc29b726",
host.475d005bacb2 check instance "system.adapter.telegram.1" for host "7523cc29b726",
host.475d005bacb2 check instance "system.adapter.telegram.2" for host "7523cc29b726",
host.475d005bacb2 check instance "system.adapter.javascript.0" for host "7523cc29b726",
host.475d005bacb2 check instance "system.adapter.asuswrt.0" for host "7523cc29b726",
host.475d005bacb2 check instance "system.adapter.dwd.0" for host "7523cc29b726",
host.475d005bacb2 check instance "system.adapter.daswetter.0" for host "7523cc29b726",
host.475d005bacb2 check instance "system.adapter.ical.0" for host "7523cc29b726",
host.475d005bacb2 check instance "system.adapter.iot.0" for host "7523cc29b726",
host.475d005bacb2 check instance "system.adapter.meross.0" for host "7523cc29b726",
host.475d005bacb2 check instance "system.adapter.miio.0" for host "7523cc29b726",
host.475d005bacb2 check instance "system.adapter.ping.0" for host "7523cc29b726",
host.475d005bacb2 check instance "system.adapter.simple-api.0" for host "7523cc29b726",
host.475d005bacb2 check instance "system.adapter.text2command.0" for host "7523cc29b726",
host.475d005bacb2 check instance "system.adapter.yahka.0" for host "7523cc29b726",
host.475d005bacb2 check instance "system.adapter.sql.0" for host "7523cc29b726",
host.475d005bacb2 check instance "system.adapter.hue.0" for host "7523cc29b726",
host.475d005bacb2 check instance "system.adapter.web.0" for host "7523cc29b726",
host.475d005bacb2 check instance "system.adapter.vis.0" for host "7523cc29b726",
host.475d005bacb2 check instance "system.adapter.vis-colorpicker.0" for host "7523cc29b726",
host.475d005bacb2 check instance "system.adapter.vis-hqwidgets.0" for host "7523cc29b726",
host.475d005bacb2 check instance "system.adapter.vis-justgage.0" for host "7523cc29b726",
host.475d005bacb2 check instance "system.adapter.vis-fancyswitch.0" for host "7523cc29b726",
host.475d005bacb2 check instance "system.adapter.vis-weather.0" for host "7523cc29b726",
host.475d005bacb2 check instance "system.adapter.alexa2.0" for host "7523cc29b726",
host.475d005bacb2 check instance "system.adapter.mihome-vacuum.0" for host "7523cc29b726",
host.475d005bacb2 check instance "system.adapter.vw-connect.0" for host "7523cc29b726",
host.475d005bacb2 check instance "system.adapter.hs100.0" for host "7523cc29b726",
host.475d005bacb2 check instance "system.adapter.fritzdect.0" for host "7523cc29b726",
host.475d005bacb2 check instance "system.adapter.tr-064.0" for host "7523cc29b726",
host.475d005bacb2 check instance "system.adapter.fb-checkpresence.0" for host "7523cc29b726",
host.475d005bacb2 check instance "system.adapter.ring.0" for host "7523cc29b726",`

Hier mal noch als Bild da der den Code nicht so schön darstellt:
![image](https://user-images.githubusercontent.com/37240726/81219682-706f2580-8fe0-11ea-90bc-b8d1f0a0f70a.png)

**Comment by mcdhrts** [comment]
Ich habe den Broker wieder hochbekommen.
Dafür musste ich folgendes machen:
Den Container mit `-h 7523cc29b726` aufbauen (also der alte host Name), das hat allerdings noch nicht gereicht, danach noch in der Konsole vom Container:
`pkill io
sudo iobroker host this`
Container neustarten und er ist wieder hochgekommen. Es scheint aber dann in Summe auf jeden Fall irgendwas nicht mit den setzen des Hostnames zu passen.

**Comment by mc-0815** [comment]
Can we reopen the issue?

I have the same (reporducable) problem and work at the moment with a dirty workaround in the iobroker-startup scripts by replacing the oldhostname via sed in the concerned json files  during first startup.

Thanks.

**Comment by mcdhrts** [comment]
i can confirm that the hostname does not work well. 
i have a total clean installation without setting a hostname in the docker run and it makes different hostnames which has the effect that iobroker does not start correctly
![image](https://user-images.githubusercontent.com/37240726/83566962-19963680-a521-11ea-94e4-2feb1cdc9ef8.png)
![image](https://user-images.githubusercontent.com/37240726/83567001-2dda3380-a521-11ea-89d1-f86f7dd73570.png)

**Comment by buanet** [comment]
@mc-0815 
> with a dirty workaround in the iobroker-startup scripts by replacing the oldhostname via sed in the concerned json files during first startup

Can you give me that code? 

Are you running your containers with host network?

**Comment by mc-0815** [comment]
I wouldn't call it code, it's just basic usage of inline replacement via sed:

OLDHOSTNAME=$(cat /opt/iobroker/.install_host)
sed -i  "s/$OLDHOSTNAME/iobroker/g" /opt/iobroker/iobroker-data/states.json
sed -i  "s/$OLDHOSTNAME/iobroker/g" /opt/iobroker/iobroker-data/objects.json

My containers are running with bridge network but not the default one, I created a dedicated network that is shared with an nginx reverse proxy container which exposes the web ports to the outside world.

**Comment by mcdhrts** [comment]
@buanet the example from yesterday was in Bridge Mode but the First Problem was in MACVLAN.

**Comment by buanet** [comment]
Small Update. 
I implemented a small workaround based on @mc-0815 code (yes I call it code).
So a new beta version is in buid process now and will be available as v4.2.2beta. But be careful, I upgaded to node 12 with v4.2.1beta. So if you upgrade an existing installation some additional steps are needed (see readme.md).

Along with that I opened an issue to iobroker js-controller to get some hel investigating whats going wrong. For details see here: https://github.com/ioBroker/ioBroker.js-controller/issues/920

Let me know how the workaround works for u. Thank you. 

Regards,
André

**Comment by mc-0815** [comment]
On my side it does.

Thanks

**Comment by mcdhrts** [comment]
with the beta version it works.
i see that with js-controller 3.1.5 it shoud be fixed without this "hack"

**Comment by buanet** [comment]
True. I'm still preparing a new Beta (v4.2.3beta) for it and removing the workaround.
Some more tests and it will be available tomorrow...

**Comment by buanet** [comment]
I think the fix in actual beta is working and solves the problem. So I close this. If you got something else, let me know.

Regards,
André
