### ISSUE TITLE
Clean Docker Image: Cannot install adapters

### ISSUE THREAD

**Issue by itchy2** [buanet/docker-iobroker#105]
Hi all,

I decided to try out ioBroker on Docker Basis.

I defined a compose file:

`version: '3'

services:
  iobroker:
    image: buanet/iobroker:v4.2.0
    restart: unless-stopped
    container_name: iobroker
    hostname: iobroker
    ports:
      - "8081:8081"
    volumes:
      - c:/Docker/iobroker/datapath:/opt/iobroker`

ioBroker starts fine and everything looks good, but I cannot add any adapters.

E.g. Modbus:

$ ./iobroker add modbus --host iobroker

`$ ./iobroker add modbus  --host iobroker
NPM version: 6.14.4
npm install iobroker.modbus@3.0.0 --loglevel error --prefix "/opt/iobroker" (System call)
npm ERR! code ENOENTnpm ERR! syscall renamenpm ERR! path /opt/iobroker/node_modules/stampit/node_modules/lodashnpm ERR! dest /opt/iobroker/node_modules/stampit/node_modules/.lodash.DELETE
npm ERR! errno -2npm ERR! enoent ENOENT: no such file or directory, rename '/opt/iobroker/node_modules/stampit/node_modules/lodash' -> '/opt/iobroker/node_modules/stampit/node_modules/.lodash.DELETE'npm ERR! enoent This is related to npm not being able to find a file.npm ERR! enoent 
npm ERR! A complete log of this run can be found in:npm ERR!     /opt/iobroker/.npm/_logs/2020-05-31T21_43_44_752Z-debug.log
ERROR: host.iobroker Cannot install iobroker.modbus@3.0.0: 254
ERROR: process exited with code 25`

As it is a clean Docker version without any adjustments it feels strange.

Somebody an Idea? What I did wrong? Some missing ports for internet access?

[2020-05-31T21_43_44_752Z-debug.log](https://github.com/buanet/docker-iobroker/files/4708545/2020-05-31T21_43_44_752Z-debug.log)

KR
Itchy2

**Comment by buanet** [comment]
Sorry, seems like you are running your container under Windows.
As I have no experience with Docker on Windows I can not support this. 

Regards,
André

**Comment by itchy2** [comment]
Hi Andre,

yes. The Issue occurs with the Docker Container on a Windows Host. On a Linux Host it's running without issues.

I assume an issue with NPM and the conversion of permissions between the Windows Host and the Docker Container.

KR
Itchy2

**Comment by buanet** [comment]
Hi,
as I mentioned before I can not support running my container on a Windows host. 
But if you got something specific I can/ should integrate into my image let me know and I will check it. Thanks.
 
Regards,
André
