### ISSUE TITLE
iobroker mit "network_mode host" nicht erreichbar

### ISSUE THREAD

**Issue by fullcavediver** [buanet/docker-iobroker#106]
Liebe Community,

iobroker im Docker funktioniert traumhaft gut. Danke für die tolle Arbeit! Ich habe bereits unter Debian und Windows laufen, die Datenübernahme aus dem RPi hat wunderbar funktioniert.

Leider musste ich feststellen, dass einige Adapter (Logitech Harmony, Shelly) mit multicasts arbeiten, also habe ich meinen docker-compose.yml umgeschrieben und versucht mit "network_mode host" zu starten. Leider vergeblich. Der iobroker wird gestartet (ich sehe es in dem logfile) aber ich kann auf ihn nicht über 8081 zugreifen. Auch die anderen Ports sind tot.

Was habe ich falsch in dem compose file?

version: '3.4'

services:
  iobroker:
    restart: always
    image: buanet/iobroker:latest
    container_name: iobroker
    hostname: iobroker
    network_mode: bridge
    ports:
      - 8081:8081
      - 8082:8082
      - 8091:8091
    volumes:
      - /sharedfolders/iobroker:/opt/iobroker

deCONZ läuft problem bei mir auf der gleichen Maschine als Host mit:

version: "2"
services:
  deconz:
    image: marthoc/deconz
    container_name: deconz
    network_mode: host
    restart: always
    volumes:
      - /opt/deconz:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyUSB0
    environment:
      - DECONZ_WEB_PORT=8080
      - DECONZ_WS_PORT=8443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0

Ich habe sowohl auf Linux als auch Windows probiert, wobei Windows wäre für mich jetzt wichtiger. Wie kann ich dieses Problem selbst lösen? Danke!

**Comment by buanet** [comment]
Hi,
dein compose file ist zwar schön an zu sehen, aber im ersten Step interessiert mich erstmal nur das Logfile deines Containers...

MfG,
André

**Comment by fullcavediver** [comment]
Hallo André,

danke, dass du dich so schnell gemeldet hast.

Das war ein guter Tipp - schau in den Logfile. Anfängerfehler, sorry ;-) Ich habe festgestellt, dass der iobroker den Port 9000 braucht, der vom Portainer defaultmäßig belegt ist. Muss der Port auf 9000 bleiben? Ich kann natürlich den Portainer auf anderes Port verlegen, bei OMV5 weiss ich noch nicht wie, aber das Problem wird öfters vorkommen - Portainer ist mittlerweile Standard.

Auf meinem Windows-Test-Rechner hat es aber leider noch nicht funktioniert. Ich muss noch etwas herumprobieren, vielleicht liegt es an meiner Personal Firewall. Ich bekomme zwar die Rückmeldung im Logfile: Use link "http://localhost:8081" to configure. der Port ist aber tot: ERR_EMPTY_RESPONSE

Danke nochmal für deine Hilfe! Ich melde mich wieder, sobald ich es auf meinem "richtigen" Windows Rechner ausprobiert habe. Vielleicht wäre es möglich, in der nächsten Release den Port 9000 freizubekommen? Im bridged mod braucht man ihn nicht und alles funktioniert wunderbar. Ich habe festgestellt, egal welche Ports ich ihm zuordne oder übersetzte, er nimmt sich sowieso alle, die er braucht. Den 9000 kann ich nicht unterbinden.

**Comment by buanet** [comment]
Hallo,
welche Ports der ioBroker verwendet kann ich nicht beeinflussen. Ich baue ja nur den Container drumrum. Insofern wird es hier kein "Freibekommen im nächsten Release" geben.

Da ich dem ioBroker die höhere Wichtigkeit zuschreibe wäre für mich immer der Weg dem Portainer einen anderen Port zu verpassen. 
Es ist aber auch möglich den Port 9000 vom ioBroker zu ändern. Das Stichwort dazu ist der Befehl "iobroker setup custom". Seitens meines ioBroker Docker Images gibt es für die Änderung des Ports im ioBroker allerdings keinerlei Implementierung.

Was deine Erfahrung mit dem bridged mode angeht, so ist das natürlich so korrekt. Da können sich auch nur die Ports beharken die bei der Erstellung des Containers nach extern freigegeben werden. 
Im MACVLAN oder host mode wird versucht alle Ports die der Container verwendet nach extern zu öffnen. Ist einer belegt = Problem. 
In diesem Zusammenhang kann ich dir nur empfehlen nochmal ein bisschen in der Docker Doku zum Thema Networking zu stöbern. Dann sollte auch klar werden warum das so ist. 

Was das Verwenden meines Containers unter Windows angeht kann es von mir keinen Support geben. Das wäre ein Thema für das ioBroker Forum. Vielleicht gibt es dort Leute die das so im Einsatz haben und dich da unterstützen können. 

MfG,
André

**Comment by Noschvie** [comment]
@fullcavediver : welcher Dienst vom ioBroker belegt den Port 9000 ?

**Comment by fullcavediver** [comment]
@buanet Danke André nochmal für deine Hilfe. Es ist natürlich sauberer, wenn man sich an die Standards hält, was den iobroker betrifft. Ich dachte nur an sowas wie environment variable.

@Noschvie ich habe da was gefunden: https://www.iobroker.net/docu/index-26.htm?page_id=3928&lang=de
Der Port ist tatsächlich belegt. Ich habe mittlerweile herausgefunden, wie ich im OMV5 das GUI auf anderes Port verlegen kann. Natürlich es wäre auch möglich mit docker run... mit anderem Port zu starten, aber ich befürchte, bei der nächsten Aktualisierung über OMV5 GUI wäre es wieder 9000. Wenn ich im Host mode starte, dann ist jede Menge Ports gleich belegt...

**Comment by Noschvie** [comment]
@fullcavediver : warum benötigst du den `host` network mode ?

**Comment by fullcavediver** [comment]
wegen multicast. Die harmony Fernbedienung und Shelly Schalter kommunizieren mit iobroker über multicast. Es gibt leider in der Konfig keine Möglichkeit dedizierte unicast Ports zuzuordnen.

**Comment by Noschvie** [comment]
... verstehe. Dann einfach Portainer mit einem anderen Port starten.

**Comment by fullcavediver** [comment]
ja, das habe ich auch gemacht. Ich befürchte, dass dieses Problem öfters kommen wird. Portainer wurde bereits über 1 Billion mal heruntergeladen...

**Comment by fullcavediver** [comment]
@buanet ich bin voll bei dir und verstehe auch deine Argumentation. Es ist nur so, dass ich in einem Fall den iobroker auf einer Windows-Gurke laufen habe und ich kann den iobroker nicht im host mode betreiben:

"The host networking driver only works on Linux hosts, and is not supported on Docker Desktop for Mac, Docker Desktop for Windows, or Docker EE for Windows Server."

Natürlich, wer kommt ernsthaft auf die Idee, Docker auf Windows zu betreiben? In diesem Fall war das der einfachste Weg einen Windows Desktop mit iobroker zu verheiraten. Umgekehrt geht's leider nicht - Docker auf Linux und Windows im Container wird nicht unterstützt.

Nein, es war nicht das Problem, den Port von Portainer zu verlegen. ich arbeite primär mit docker compose, Portainer nutze ich nur als viewer und weil er bei der OMV5 Docker-Installation dabei war ;-)

Abschließend möchte ich nochmal betonen, du hast tolle Arbeit geleistet und ich freue mich auf die nächsten Releases. Seit der Migration vom RPi3 (ohne Docker) auf den MiniPC mit J5005 / 16GB RAM (mit deinem Docker image) macht echt Spaß damit zu arbeiten!

**Comment by nicedevil007** [comment]
@fullcavediver 

hey muss jetzt doch mal fragen wie du das gelöst hast. Habe zwar kein OMV aber sonst so ziemlich genau das gleiche Problem :(
Will meine Harmony nutzen können im ioBroker und scheitere an der Stelle. Portainer läuft auch, habs auch schon auf anderen Port gelegt, aber auch das führt zu keinem Erfolg.

**Comment by fullcavediver** [comment]
@nicedevil007 

ich habe den Portainer auf einen anderen Port umgelegt und nutze ioBroker im host mode. Auf Experimente mit Windows habe ich komplett verzichtet.

Hier mein docker-compose file für ioBroker container:

```
version: '2'

services:
  iobroker:
    image: buanet/iobroker:latest
    container_name: iobroker
    hostname: iobroker
    network_mode: host
    restart: always
    volumes:
      - /path/to/iobroker:/opt/iobroker
      - /etc/localtime:/etc/localtime:ro
```

**Comment by nicedevil007** [comment]
mhhhh funzt bei mir nach wie vor nicht, hab allerdings auch docker swarm aktiv und da gibts noch den portainer agent der auf 9001 läuft. den hab ich jetzt auch schon auf 8991 umgedengelt, führt aber auch nicht zum gewünschten erfolg :/

**Comment by thoughtgap** [comment]
Vielen Dank für den wertvollen Hinweis! Nachdem ich Portainer nun nur mit Portmapping auf 8000 und 9443 sowie dem Zusatz `--http-disabled` starte ist mein iobroker auch im Host mode erreichbar.

**Comment by hellblue** [comment]
ich hatte auch das Problem, die Lösung war das ich im iobroker in der Datei iobroker.json

bei states den Port von 9000 auf 9100 geändert habe

`  "states": {
    "type": "jsonl",
    "// type": "Possible values: 'file' - [port 9000], 'redis' - [port 6379].",
    "host": "127.0.0.1",
    "port": 9100,
    "connectTimeout": 5000,
    "writeFileInterval": 30000,
    "dataDir": "",
    "options": {
      "auth_pass": null,
      "retry_max_delay": 5000,
      "retry_max_count": 19,
      "db": 0,
      "family": 0
    },
`

daraufhin konnte ich den iobroker auch im host Modus starten und mein Portainer läuft weiterhin auf Port 9000
