### ISSUE TITLE
docker armhf admin0 does not start http listener

### ISSUE THREAD

**Issue by iotfun6** [buanet/docker-iobroker#110]
I ran today my first iobroker docker image. After starting the image (default settings) no service was listening on port 8081. After some investigation on the Internet I found another similar issue where it was mentioned to create a new admin instance. This solved my problem but I couldn't find the cause of this error. I could repeatedly reproduce the problem, restarting the container did not change the situation neither did applying custom settings to admin0 nor changing the port from 8081 to 7000, only adding another admin instances brings the http service online.
 
I'm running the lastest iobroker container (4.2.0) on docker 19.03.11 linux/arm. 
"Image": "sha256:1c5cdd7ba148d5eb8d5466378448560da573e0853179ddea917b54918f68ed13"
"io.balena.architecture": "armv7hf", "io.balena.qemu.version": "4.0.0+balena2-arm"
There is only one warning in the iobroker log: warn: host... does not start any instances on this host

**Comment by buanet** [comment]
Please provide your container log. Thanks.

Regards,
André

**Comment by iotfun6** [comment]
[iobroker.log](https://github.com/buanet/docker-iobroker/files/4767221/iobroker.log)
This log shows the situation after a fresh container deployment where the admin instance is not accessible.

**Comment by buanet** [comment]
Sorry, the log is incomplete or your container gets stuck wenn installing vim...

Whats your system and os?
You talk about "armv7hf" but log says aarch64...

What tag do you use when pulling the image from Docker-Hub?

**Comment by iotfun6** [comment]
Hi André,
the system is running on a 2GB rock64 using Armbian Ubuntu. Honestly I can't remember why I've chosen the armhf over aarch64 version of Docker at install time but it works fine for all my other (rpi) containers.
OS:	Ubuntu 18.04.4 LTS
Kernel: 4.4.192-rockchip64

I pulled yesterday the latest version (docker pull buanet/iobroker), starting the containers using that version: 
docker run -d
   -p 8081:8081
   -v iobroker_data:/opt/iobroker
   --restart unless-stopped
   --name myiobroker_4.2.0 buanet/iobroker
[iobroker.log](https://github.com/buanet/docker-iobroker/files/4769874/iobroker.log)

I attached another log which should now be complete.
Regards,
Thomas

**Comment by buanet** [comment]
Ok.
As I see in your log you are running into a known issue where changing the hostname is buggy with js-controller < v3.1.5.
For this i added a temporary fix in actual beta version. Can you please try if the issue exists when you use the beta tag image? 
When you test it please use a new and empty folder for "-v iobroker_data:/opt/iobroker".
Thank you.

**Comment by iotfun6** [comment]
Hi André,
I tested the beta version, created several containers (always deleting everything including the volume) and it looks stable now. After the setup script completed iobroker is reachable.
Many thanks!
Thomas
