### ISSUE TITLE
iobroker not reachable on Docker with Ubuntu Server 20.04 LTS

### ISSUE THREAD

**Issue by bortim** [buanet/docker-iobroker#111]
Hello,

I have installed docker on an Ubuntu Server 20.04 LTS on a Raspberry pi (arm64) and a VM (amd64).
In both cases I am not able to access the admin dashboard.

the last 3 entries are loading:
- admin
- discovery
- info

I can't see anything else.

`iobroker info` says that iobroker is running.

Can anyone help me or tell me what I have to do to get more information?

Regards
bortim

**Comment by buanet** [comment]
Where is your Log?

As I guess your issue, please try beta tag. I included a fix there. Otherwise add your container log.

Regards,
André

**Comment by jump84** [comment]
Hi,
I had the same issue on a pi4 with buster.
Deleting data volume and using new one did the job.
Create data volume:
sudo docker volume create iobroker_data

Command used to run:
sudo docker run -d -p 8081:8081 -p 8082:8082 --name iobroker --hostname iobroker -e HOST_HOSTNAME='iobroker' -e TZ=Europe/Berlin -v iobroker_data:/opt/iobroker --restart always buanet/iobroker:beta

**Comment by bortim** [comment]
Hey,

the usage of the beta-version works like a charme.

Regards
bortim
