### ISSUE TITLE
Unable to locate package

### ISSUE THREAD

**Issue by Anzic23** [buanet/docker-iobroker#114]
v4.2.4beta
```
Installing additional packages is set by ENV.
The following packages will be installed: ps4-waker ffmpeg...
E: Unable to locate package ps4-waker
```
and what is the difference between ENV PUID, PGID and SETGID, SETUID?

**Comment by buanet** [comment]
Sorry,
I don't know the package ps4-waker. As the error message says apt could not locate it...
When I google it, it seems to be a npm package. So this might be the reason.
ENV PACKAGES is for Linux packages only. 

The difference is easy:
SETGID and SETUID are valid ENVs for my image.
As you can see in readme.md, PUID and PGID do not exist. Not sure where you got this from... 

As there is no issue, this will be closed.

Regards,
André
