### ISSUE TITLE
add libpam0g-dev to avoid gyp issues

### ISSUE THREAD

**Issue by xmace** [buanet/docker-iobroker#12]
Hi, I just installed your docker image and it worked well!! Thank you very much

Only thing i found out, that libpam0g-dev was missing and is used by several adapters like "mihome" and "terminal" during the installation of the adapters itself.

Hopefully I can improve the user experience regarding the installation for newcomers which are facing maybe this issue in the future as well as me :)

Br, Matthias

**Comment by buanet** [comment]
hi matthias,
thx for your feedback. libpam0g-dev is already included in node8beta so it will be part of the next release. 

best regards,
andré
