### ISSUE TITLE
Can't start new container from backup

### ISSUE THREAD

**Issue by Anzic23** [buanet/docker-iobroker#120]
v5.0.0
make a backup by command line ("iobroker backup") and backitup adapter. Place first one file, then another. in both cases, an error appears in the log that the file does not correct.

**Comment by buanet** [comment]
> in both cases, an error appears in the log that the file does not correct

I don't see any log file.

Regards,
André

**Comment by Anzic23** [comment]
> > in both cases, an error appears in the log that the file does not correct
> 
> I don't see any log file.
> 
> Regards,
> André

[iobroker.zip](https://github.com/buanet/docker-iobroker/files/4851108/iobroker.zip)

[docker-compose.txt](https://github.com/buanet/docker-iobroker/files/4851120/docker-compose.txt)

**Comment by buanet** [comment]
Found it. 
Please rename your backup file to: iobroker_2020_06_30-09_26_55_backupiobroker.tar.gz
This should work.

I will have to optimize the startupscript in detecting the iobroker backup file. It actually waits for a file called "iobroker_20***.tar.gz".

Regards,
André

**Comment by Anzic23** [comment]
on step 2:
```
ioBroker backup file detected in /opt/iobroker. Restoring ioBroker... 
Done.
```
But in /opt/iobroker/log/restore.log
```
host.iobroker Using backup file iobroker_2020_06_30-09_26_55_backupiobroker.tar.gz
host.iobroker Cannot find extracted file from file "/opt/iobroker/node_modules/iobroker.js-controller/tmp/backup/backup.json"
 Cannot save /opt/iobroker/iobroker-data/states.json: Error: EACCES: permission denied, open '/opt/iobroker/iobroker-data/states.json.bak'
```
root@iobroker:/opt/iobroker# sudo iob restore 0
```
host.iobroker Using backup file iobroker_2020_06_30-09_26_55_backupiobroker.tar.gz
iobroker controller daemon is not running
host.iobroker OK.
host.iobroker Clear all objects and states...
clean 789 objects...
[Not critical] Cannot delete object 0_userdata.0: "Object is marked as non deletable"
[Not critical] Cannot delete object alias.0: "Object is marked as non deletable"
[Not critical] Cannot delete object system.repositories: "Object is marked as non deletable"
[Not critical] Cannot delete object system.config: "Object is marked as non deletable"
[Not critical] Cannot delete object enum.functions: "Object is marked as non deletable"
[Not critical] Cannot delete object enum.rooms: "Object is marked as non deletable"
clean 651 states...
host.iobroker done.
/opt/iobroker/node_modules/standard-as-callback/built/index.js:6
        throw e;
        ^

Error: EACCES: permission denied, open '/opt/iobroker/iobroker-data/iobroker.json'
    at Object.openSync (fs.js:458:3)
    at Object.writeFileSync (fs.js:1355:35)
    at /opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupBackup.js:642:20
    at /opt/iobroker/node_modules/iobroker.js-controller/lib/setup.js:2156:88
    at /opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:755:47
    at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
    at /opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/opt/iobroker/iobroker-data/iobroker.json'
}
root@iobroker:/opt/iobroker#

```

**Comment by Anzic23** [comment]
iob fix - it seems to have fixed an access error. I try to restore it with the iob restore command

**Comment by buanet** [comment]
I can confirm this restoring issue. This is cused by wrong permissions for iobroker.json file. Will add a fix to the next version. 
You can manually set the permissions and ownership to the file by chmod and chown command. 

Regards,
André

**Comment by buanet** [comment]
I fixed this in new beta version v5.0.1beta. Build is running now. Should be available to download in a few minutes. 

Regards,
André

**Comment by Anzic23** [comment]
I think you also need to consider the file name that is created by the backup adapter - "iobroker_2020_07_02-02_30_10_backupiobroker.tar.gz"
iobroker backup - creat "2020_06_30-09_26_55_backupiobroker.tar.gz"

**Comment by buanet** [comment]
It's already included. See beta readme.md:

https://github.com/buanet/docker-iobroker/tree/beta#mounting-folder-volume

Changelog:
https://github.com/buanet/docker-iobroker/tree/beta#v501beta-2020-07-01
