### ISSUE TITLE
PhantomJS does not work out-of-the-box

### ISSUE THREAD

**Issue by christofkac** [buanet/docker-iobroker#124]
When trying to start PhantomJS, the following error message is displayed:
`
root@ioBrokerProductive:/opt/iobroker/node_modules/phantomjs-prebuilt/bin# ./phantomjs
Auto configuration failed
140414610972288:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libssl_conf.so): libssl_conf.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
140414610972288:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
140414610972288:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=ssl_conf, path=ssl_conf
140414610972288:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=ssl_conf
`

After searching via google I found this post:
[https://stackoverflow.com/questions/50585038/phantomjs-crashes-on-jenkins-auto-configuration-failed](url)

This recommends to set an environment variable:
`export OPENSSL_CONF=$WORKSPACE/openssl.cnf`

Apparently, the variable does not need to point to anything reasonable (as $WORKSPACE is not defined) but needs only to exist as after adding this variable, everything works.

A "standard" problem with PhantomJS is, that you have to install a library upfront:
`apt-get install libfontconfig`

After installation of libfontconfig and setting OPENSSL_CONF, PhantomJs works.

How can this variable be created automatically?

**Comment by buanet** [comment]
> This recommends to set an environment variable:
export OPENSSL_CONF=$WORKSPACE/openssl.cnf

Think this may be covered by using "Userdefined startup scripts (https://github.com/buanet/docker-iobroker/blob/master/README.md#userdefined-startup-scripts)

> apt-get install libfontconfig

For this please use ENV packages (https://github.com/buanet/docker-iobroker/blob/master/README.md#environment-variables)

Does this work for you?

Regards,
André

**Comment by christofkac** [comment]
Hi,
thanks for the hints. 
Especially the user scripts are very useful.

Now everything is sorted.
Bye
Christof
