### ISSUE TITLE
Is it safe to update the docker-iobroker with watchtower automatically? 

### ISSUE THREAD

**Issue by mtoensing** [buanet/docker-iobroker#127]
Hi, 

I update all my container automatically with watchtower https://github.com/containrrr/watchtower This includes mariadb, minecraft servers for java and bedrock, grafana, filebot, jdownloader and so on. This works fine since a few years. Is this the best practice for iobroker and the "latest" tag? Does it migrate my settings in case of an update?

**Comment by buanet** [comment]
No. I won't do that using the latest tag as there could be issues within ioBroker when changing the major node version. With js-controller 3 ioBroker should rebuild the adapters by itself when a change of major node version is detected. But as far as I know, there are still some adapters which have problems with that. 

More information regarding node js upgrade here: https://forum.iobroker.net/topic/22867/how-to-node-js-f%C3%BCr-iobroker-richtig-updaten

Please close this issue when your question is answered, Thank you.

Regards,
André

**Comment by mtoensing** [comment]
Thank you. I switched from latest to 5.0.0
