### ISSUE TITLE
Enable passwordless sudo for certain commands as a non-root user

### ISSUE THREAD

**Issue by kennymc-c** [buanet/docker-iobroker#128]
I want to use the backitup adapter to copy my iobroker backup per cifs to my nas. Unfortunately this does not seem to work properly even after installing the cifs-utils. The mout command used by the adapter can only be executed with sudo. Since I run my container as a non-root user, it might be useful to be able to define commands in the enviroment variable where the user does not need a password for sudo.

**Comment by kennymc-c** [comment]
I just realized that this probably isn't a problem with sudo but with using the mount command inside containers itself.
Adding 
```
cap_add:
    - SYS_ADMIN
    - DAC_READ_SEARCH
```
to my docker-compose file seems to work. But using a non-root user now doesn't make sense anymore if I have understood the meaning of the used options correctly.
Is there a way to use this adapter with a non-root user?

**Comment by buanet** [comment]
Hi, sorry for the late response. Did you find a solution for this?
I have never tried to use cifs inside a container cause i always use mountpoints for transferring data between container and host. 

If you still want to use cifs, you may use the ["userdefined startup scripts"](https://github.com/buanet/docker-iobroker#userdefined-startup-scripts). The will be executed as root at startup and may solve your problem connecting to a cifs endpoint. 

If this solves your problem (or you still got a solution) please close this issue. 
Thank you.

Regards,
André

**Comment by kennymc-c** [comment]
Since the backup and the mount and unmount process should be executed while the container is running, a startup script makes little sense. The mount would be there all the time, which would work, but I could also solve that with an external script including unmount.
The problem is the mount command inside docker containers, which is only possible with SYS_ADMIN.

**Comment by buanet** [comment]
Sorry, don't know how cifs is integrated in backitup adapter. And also don't know how this is working in general...

For me you mount a cifs target to your container and backitup pushes the backup there. Nearly the same procedure as you connect to ftp oder store the backup to a local folder. If you mount your cifs target on container startup you should be good. I think this you can reach with a user defined startup script.
How backitup then pushes/ stores the backup to your target is not my task. This is something the adapter has to do. If this could not be handled with the given permissions of the iobroker user, there must be a change to iobroker itself, cause ioBroker setup is setting up iobroker user and its permissions.

So this is why I still see no task for iobroker docker image here. 

Regards,
André

**Comment by kennymc-c** [comment]
I originally assumed that it was just a permission problem from the mount command and created the issue. I am now closing the issue, as this will probably work better for me via the `smclient` command, which has to be included in the adapter itself.
