### ISSUE TITLE
dir .docker_config not created on first startup

### ISSUE THREAD

**Issue by gregor-samosir** [buanet/docker-iobroker#130]
Beta 5.0.2

Starting ioBroker...
/opt/scripts/iobroker_startup.sh: Zeile 501: /opt/iobroker/.docker_config/.healthcheck: Datei oder Verzeichnis nicht gefunden

**Comment by buanet** [comment]
Thank you. There was an issue with some new paths. :) I just corrected it. Beta Branch is now building. Think a new build v5.0.2beta will be available for download in 30 minutes. 

Regards,
André
