### ISSUE TITLE
How to use backitup with CIFS/SMB-Network-Share

### ISSUE THREAD

**Issue by dklinger** [buanet/docker-iobroker#133]
Hi.
When using backitup to backup to a network share I get the error: Permission denied.
My guess was a permission issue with the docker-container so I added the the Container capability SYS_ADMIN to allow the mount-command.

But now I get this one: mount: /opt/iobroker/backups: cannot mount //server/Public/ioBroker-Backup/Standard read-only.
According to google-research this can be related to problems with the cifs-utils-Package.

So, just one question: Should a backup using backitup and a network-share just work or is it something which does need some kind of configuration using iobroker within docker?

**Comment by fzzybllz** [comment]
maybe not fixing this particular issue but as a solution to the problem i would suggest to use the adapter to do local backup and then run a cronjob within you're host-instance to move the file from the docker-volume to your NAS or the location you want to store it

**Comment by dklinger** [comment]
Yeah. After some research I got that mounting within a docker-container seems not be a common thing. So I wrote a service for the host which mounts the SMB-backup-location into the iobroker/backup-folder.
I tried to avoid this as I want my containers to be as host-independent as possible.

**Comment by dklinger** [comment]
And it doesn't work on reboot because the docker-container is starting up to fast. So I'm going @fzzybllz way using a cronjob.
Looks like this is more reliable then a service which starts maybe/maybe not in time.
