### ISSUE TITLE
BLE "Terminating because EAFNOSUPPORT, Address family not supported by protocol"

### ISSUE THREAD

**Issue by C4mp3r-Grey** [buanet/docker-iobroker#134]
As stated in https://github.com/AlCalzone/ioBroker.ble/issues/422#issue-677958385 I have a problem with bluetooth low energy access (running the BLE adapter from within iobroker) in docker container on a Raspi 4 4GB (Raspian Buster).

It might be a general Docker+NOBLE problem, but the issue that AlCalzone referred to is as of February 2020  (https://github.com/abandonware/noble/issues/43#issue-567050740) and there is little conversation on this. I believe Docker+NoBLE is a common setup, whether on Raspi4 or not, no?

Can anyone report the setup working in his environment? A report whether that should work would be awesome to avoid investigation in the wrong direction ;-)

Maybe it is a problem, that can be solved through a change in the container build or parameters?

Cheers!

**Comment by buanet** [comment]
Hi,
please let me know what you did already and how you start your container.  Maybe i can reproduce it and check. 

Regards,
André

**Comment by buanet** [comment]
BTW, my first research gives me the information, that you need to run your container in network mode host to access Bluetooth from inside a container because Bluetooth is a network device.. As I read in you ble issue this seems not to be the case in your setup.

Regards,
André

**Comment by C4mp3r-Grey** [comment]
Thanks for that advice! Would be a simple and reasonable fault by me! Started with the docker command (bridge) from your readme, and did not expect I would need to alter it.

Unfortunately, I was not yet able to access iobroker port 8081 when running the container in host mode (connection refused on 8081 and vis port 8082), but that is another issueI need to solve now first.

I believe it is not an issue then? Would like to keep it open for the moment, but will then likely be closed ;-)

Since I am not a docker expert, you might give me a hint? Would that command be right? 

> docker run -it --net host  --name myIObrokerHost2  --restart unless-stopped -v iobrokerdata:/opt/iobroker -e IOB_OBJECTSDB_PORT:10000 -e IOB_STATESDB_PORT:10001 buanet/iobroker:v5.0.0


Portainer runs on 9000, so I changed the db ports, which seems to be running fine.

**Comment by buanet** [comment]
I'm not sure if changing the database ports on a master is working that way. Never tested this....
Think it would be a better choice to redirect the portainer port and keep the iob database defaults....

But what ever. Without the ioBroker container log I have nothing to analyze. :)

Regards,
André

**Comment by C4mp3r-Grey** [comment]
Hi André,

I also had that impression, but thanks for looking on this again! The redirect of portainer ports indeed was the easier way. I finally chose to change portainer! By the way: Changing the _iobroker database ports_ indeed had no effect ;-) They still ran on 9000 and iobroker searched on 9000 etc. as well ...

What works now is:

`docker run -d -p 9500:9000 -p 8500:8000 --name portainer --restart always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer:arm`

and 

`docker run --privileged  --net host  --name myIObroker  --restart unless-stopped --mount src=/home/pi/iobroker,target=/opt/iobroker,type=bind -v  buanet/iobroker:v5.0.0`

Erased the data folder of iobroker container before and started from scratch then again.


We can close this issue. It was neiter a noble bug nor ioboker or docker container problem, but just false configuration. Seems to work like a charm now! Thanks for your efforts and contributions!

May I sugggest to add a remark in your readme, that BLE adapter will not run when not running your container in _host mode_? 


Cheers!
C4mper
