### ISSUE TITLE
vis and mobile not working on Synology

### ISSUE THREAD

**Issue by Kefut** [buanet/docker-iobroker#135]
Just tried installing and running the docker image multiple times, but the vis and mobile instances are not working anymore.

Vis gets stuck in "Loading values..." and the browser console shows:
[Veraltet] Application Cache is restricted to secure contexts. Please consider migrating your application to HTTPS, and eventually shifting over to Service Workers. See https://go.microsoft.com/fwlink/?linkid=2047885 for more details.
info.js:21 Version Info-Adapter-Widget: 0.0.9
:8082/vis.0/main/vis-user.css?_=1598298503909:1 Failed to load resource: the server responded with a status of 404 (Not Found)
conn.js:1142 Error: Cannot load /vis.0/main/vis-user.css - Not Found
conn.js:273 2020-08-24T19:48:24.231Z Connected => authenticate
info.js:13 Uncaught (in promise) SyntaxError: Unexpected token } in JSON at position 247990
    at JSON.parse (<anonymous>)
    at getTranslation (info.js:13)
conn.js:293 2020-08-24T19:48:24.326Z Authenticated: true
Fehler beim Laden der Quell Zuordnung durch devtools: Der Inhalt für http://MYURL:8082/lib/js/socket.io.js.map konnte nicht geladen werden: HTTP Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
Fehler beim Laden der Quell Zuordnung durch devtools: Der Inhalt für chrome-extension://dafgdjggglmmknipkhngniifhplpcldb/browser-polyfill.min.js.map konnte nicht geladen werden: HTTP Fehler: Statuscode 404, net::ERR_UNKNOWN_URL_SCHEME

Mobile shows white page. Browser console shows:
[Veraltet] Application Cache is restricted to secure contexts. Please consider migrating your application to HTTPS, and eventually shifting over to Service Workers. See https://go.microsoft.com/fwlink/?linkid=2047885 for more details.
conn.js:263 2020-08-24T19:49:03.434Z Connected => authenticate
conn.js:278 2020-08-24T19:49:03.497Z Authenticated: true
mobile.js:343 Loading data values...
Fehler beim Laden der Quell Zuordnung durch devtools: Der Inhalt für chrome-extension://dafgdjggglmmknipkhngniifhplpcldb/browser-polyfill.min.js.map konnte nicht geladen werden: HTTP Fehler: Statuscode 404, net::ERR_UNKNOWN_URL_SCHEME
Fehler beim Laden der Quell Zuordnung durch devtools: Der Inhalt für http://MYURL:8082/lib/js/socket.io.js.map konnte nicht geladen werden: HTTP Fehler: Statuscode 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

Did the same install last week and it worked in the same setup.

**Comment by buanet** [comment]
Hi,
did you solve it? If yes, what was the problem? 
Maybe this information will help other users googling your error messages. 
Thank you.

Regards,
André

**Comment by chaot2000** [comment]
Hi, 
i have the same poblem. Please let us know your solution.

Regards,
C2k

**Comment by Kefut** [comment]
Hi,
I forced the upgrad of Web to 3.0.12, VIS 1.2.10 and mobile 1.0.1. Afterwards it worked as before!
Best!

**Comment by chaot2000** [comment]
Yeah, i upgraded of the latent Version. It works finde. Thx
