### ISSUE TITLE
Restore not working on latest (5.0.0.) Image

### ISSUE THREAD

**Issue by dschaedl** [buanet/docker-iobroker#137]
Hi

Restore does not work on 5.0.0 image. (using arm64 image)
It catches the backup on startup and does a restore (see log)
and afterwards identifies the installation as new and overwrites the backup (see log)
The same process works fine on v4.2.0

regards
Daniel

P.S.
and 10000thanks for your great job providing this image!!

log:
`
------------------------------------------------------------
---------------     2020-10-05 20:41:23      ---------------
------------------------------------------------------------
 
------------------------------------------------------------
-----       Welcome to your ioBroker-container!        -----
-----          Startupscript is now running.           -----
-----                Please be patient!                -----
------------------------------------------------------------
 
------------------------------------------------------------
-----              Debugging information               -----
-----                                                  -----
-----                      System                      -----
-----               arch:      aarch64                 -----
-----                                                  -----
-----                     Versions                     -----
-----               image:     v5.0.0                  -----
-----               node:      v12.18.4                -----
-----               npm:       6.14.6                  -----
-----                                                  -----
-----                       ENV                        -----
-----               AVAHI:     false                   -----
-----               PACKAGES:  vim                     -----
-----               SETGID:    1000                    -----
-----               SETUID:    1000                    -----
------------------------------------------------------------
 
------------------------------------------------------------
-----         Step 1 of 5: Preparing container         -----
------------------------------------------------------------
 
Installing additional packages is set by ENV.
The following packages will be installed: vim...
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
Selecting previously unselected package xxd.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 21945 files and directories currently installed.)
Preparing to unpack .../xxd_2%3a8.1.0875-5_arm64.deb ...
Unpacking xxd (2:8.1.0875-5) ...
Selecting previously unselected package vim-common.
Preparing to unpack .../vim-common_2%3a8.1.0875-5_all.deb ...
Unpacking vim-common (2:8.1.0875-5) ...
Selecting previously unselected package libgpm2:arm64.
Preparing to unpack .../libgpm2_1.20.7-5_arm64.deb ...
Unpacking libgpm2:arm64 (1.20.7-5) ...
Selecting previously unselected package vim-runtime.
Preparing to unpack .../vim-runtime_2%3a8.1.0875-5_all.deb ...
Adding 'diversion of /usr/share/vim/vim81/doc/help.txt to /usr/share/vim/vim81/doc/help.txt.vim-tiny by vim-runtime'
Adding 'diversion of /usr/share/vim/vim81/doc/tags to /usr/share/vim/vim81/doc/tags.vim-tiny by vim-runtime'
Unpacking vim-runtime (2:8.1.0875-5) ...
Selecting previously unselected package vim.
Preparing to unpack .../vim_2%3a8.1.0875-5_arm64.deb ...
Unpacking vim (2:8.1.0875-5) ...
Setting up libgpm2:arm64 (1.20.7-5) ...
Setting up xxd (2:8.1.0875-5) ...
Setting up vim-common (2:8.1.0875-5) ...
Setting up vim-runtime (2:8.1.0875-5) ...
Setting up vim (2:8.1.0875-5) ...
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/vim (vim) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/vimdiff (vimdiff) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/rvim (rvim) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/rview (rview) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/vi (vi) in auto mode
update-alternatives: warning: skip creation of /usr/share/man/da/man1/vi.1.gz because associated file /usr/share/man/da/man1/vim.1.gz (of link group vi) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/de/man1/vi.1.gz because associated file /usr/share/man/de/man1/vim.1.gz (of link group vi) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/fr/man1/vi.1.gz because associated file /usr/share/man/fr/man1/vim.1.gz (of link group vi) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/it/man1/vi.1.gz because associated file /usr/share/man/it/man1/vim.1.gz (of link group vi) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/ja/man1/vi.1.gz because associated file /usr/share/man/ja/man1/vim.1.gz (of link group vi) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/pl/man1/vi.1.gz because associated file /usr/share/man/pl/man1/vim.1.gz (of link group vi) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/ru/man1/vi.1.gz because associated file /usr/share/man/ru/man1/vim.1.gz (of link group vi) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/vi.1.gz because associated file /usr/share/man/man1/vim.1.gz (of link group vi) doesn't exist
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/view (view) in auto mode
update-alternatives: warning: skip creation of /usr/share/man/da/man1/view.1.gz because associated file /usr/share/man/da/man1/vim.1.gz (of link group view) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/de/man1/view.1.gz because associated file /usr/share/man/de/man1/vim.1.gz (of link group view) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/fr/man1/view.1.gz because associated file /usr/share/man/fr/man1/vim.1.gz (of link group view) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/it/man1/view.1.gz because associated file /usr/share/man/it/man1/vim.1.gz (of link group view) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/ja/man1/view.1.gz because associated file /usr/share/man/ja/man1/vim.1.gz (of link group view) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/pl/man1/view.1.gz because associated file /usr/share/man/pl/man1/vim.1.gz (of link group view) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/ru/man1/view.1.gz because associated file /usr/share/man/ru/man1/vim.1.gz (of link group view) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/view.1.gz because associated file /usr/share/man/man1/vim.1.gz (of link group view) doesn't exist
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/ex (ex) in auto mode
update-alternatives: warning: skip creation of /usr/share/man/da/man1/ex.1.gz because associated file /usr/share/man/da/man1/vim.1.gz (of link group ex) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/de/man1/ex.1.gz because associated file /usr/share/man/de/man1/vim.1.gz (of link group ex) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/fr/man1/ex.1.gz because associated file /usr/share/man/fr/man1/vim.1.gz (of link group ex) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/it/man1/ex.1.gz because associated file /usr/share/man/it/man1/vim.1.gz (of link group ex) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/ja/man1/ex.1.gz because associated file /usr/share/man/ja/man1/vim.1.gz (of link group ex) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/pl/man1/ex.1.gz because associated file /usr/share/man/pl/man1/vim.1.gz (of link group ex) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/ru/man1/ex.1.gz because associated file /usr/share/man/ru/man1/vim.1.gz (of link group ex) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/ex.1.gz because associated file /usr/share/man/man1/vim.1.gz (of link group ex) doesn't exist
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/editor (editor) in auto mode
update-alternatives: warning: skip creation of /usr/share/man/da/man1/editor.1.gz because associated file /usr/share/man/da/man1/vim.1.gz (of link group editor) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/de/man1/editor.1.gz because associated file /usr/share/man/de/man1/vim.1.gz (of link group editor) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/fr/man1/editor.1.gz because associated file /usr/share/man/fr/man1/vim.1.gz (of link group editor) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/it/man1/editor.1.gz because associated file /usr/share/man/it/man1/vim.1.gz (of link group editor) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/ja/man1/editor.1.gz because associated file /usr/share/man/ja/man1/vim.1.gz (of link group editor) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/pl/man1/editor.1.gz because associated file /usr/share/man/pl/man1/vim.1.gz (of link group editor) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/ru/man1/editor.1.gz because associated file /usr/share/man/ru/man1/vim.1.gz (of link group editor) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/editor.1.gz because associated file /usr/share/man/man1/vim.1.gz (of link group editor) doesn't exist
Processing triggers for libc-bin (2.28-10) ...
Processing triggers for mime-support (3.62) ...
Done.
 
------------------------------------------------------------
-----   Step 2 of 5: Detecting ioBroker installation   -----
------------------------------------------------------------
 
ioBroker backup file detected in /opt/iobroker. Restoring ioBroker...
Done.
 
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!                             IMPORTANT NOTE                             !!!!!
!!!!!        The sartup script restored iobroker from a backup file.         !!!!!
!!!!! Check /opt/iobroker/log/restore.log to see if restore was successful.  !!!!!
!!!!! When ioBroker now starts it will reinstall all Adapters automatically. !!!!!
!!!!!         This might be take a looooong time! Please be patient!         !!!!!
!!!!!  You can view installation process by taking a look at ioBroker log.   !!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 
------------------------------------------------------------
-----   Step 3 of 5: Checking ioBroker installation    -----
------------------------------------------------------------
 
(Re)Setting folder permissions (This might take a while! Please be patient!)...
Done.
 
Fixing "sudo-bug" by replacing sudo in iobroker with gosu...
Done.
 
Looks like this is a new and empty installation of ioBroker.
Hostname needs to be updated to  iobroker-69b945ffd9-qtpw8...
The host for instance "system.adapter.admin.0" was changed from "b12eb7896b5c" to "iobroker-69b945ffd9-qtpw8".
The host for instance "system.adapter.discovery.0" was changed from "b12eb7896b5c" to "iobroker-69b945ffd9-qtpw8".
The host for instance "system.adapter.info.0" was changed from "b12eb7896b5c" to "iobroker-69b945ffd9-qtpw8".
Done.
 
------------------------------------------------------------
-----      Step 4 of 5: Applying special settings      -----
------------------------------------------------------------
 
Some adapters have special requirements/ settings which can be activated by the use of environment variables.
For more information take a look at readme.md on Github!
 
------------------------------------------------------------
-----          Step 5 of 5: ioBroker startup           -----
------------------------------------------------------------
 
Starting ioBroker...
 
host.iobroker-69b945ffd9-qtpw8 check instance "system.adapter.admin.0" for host "iobroker-69b945ffd9-qtpw8"
host.iobroker-69b945ffd9-qtpw8 check instance "system.adapter.discovery.0" for host "iobroker-69b945ffd9-qtpw8"
host.iobroker-69b945ffd9-qtpw8 check instance "system.adapter.info.0" for host "iobroker-69b945ffd9-qtpw8"
Send diag info: {"uuid":"7abd3182-d399-f7bd-da19-9550d8babede","language":"","country":"","hosts":[{"version":"3.1.6","platform":"Javascript/Node.js","type":"linux"}],"node":"v12.18.4","arch":"arm64","adapters":{"admin":{"version":"4.0.10","platform":"Javascript/Node.js"},"discovery":{"version":"2.3.7","platform":"Javascript/Node.js"},"info":{"version":"1.7.2","platform":"Javascript/Node.js"}},"statesType":"file","objectsType":"file","model":"unknown","cpus":4,"mem":4035047424,"ostype":"Linux","city":""}
hash changed or no sources cached => force download of new sources
Send diag info: {"uuid":"7abd3182-d399-f7bd-da19-9550d8babede","language":"en","country":"","hosts":[{"version":"3.1.6","platform":"Javascript/Node.js","type":"linux"}],"node":"v12.18.4","arch":"arm64","adapters":{"admin":{"version":"4.0.10","platform":"Javascript/Node.js"},"discovery":{"version":"2.3.7","platform":"Javascript/Node.js"},"info":{"version":"1.7.2","platform":"Javascript/Node.js"}},"statesType":"file","objectsType":"file","model":"unknown","cpus":4,"mem":4035047424,"ostype":"Linux","city":""}
================================== > LOG REDIRECT system.adapter.admin.0 => false [system.adapter.admin.0.logging]
================================== > LOG REDIRECT system.adapter.admin.0 => true [system.adapter.admin.0.logging]
Send diag info: {"uuid":"7abd3182-d399-f7bd-da19-9550d8babede","language":"en","country":"Switzerland","hosts":[{"version":"3.1.6","platform":"Javascript/Node.js","type":"linux"}],"node":"v12.18.4","arch":"arm64","adapters":{"admin":{"version":"4.0.10","platform":"Javascript/Node.js"},"discovery":{"version":"2.3.7","platform":"Javascript/Node.js"},"info":{"version":"1.7.2","platform":"Javascript/Node.js"}},"statesType":"file","objectsType":"file","model":"unknown","cpus":4,"mem":4035047424,"ostype":"Linux","city":"meilen"}
hash unchanged, use cached sources
================================== > LOG REDIRECT system.adapter.admin.0 => false [system.adapter.admin.0.logging]
================================== > LOG REDIRECT system.adapter.admin.0 => true [system.adapter.admin.0.logging]
================================== > LOG REDIRECT system.adapter.admin.0 => false [system.adapter.admin.0.logging]
`

**Comment by buanet** [comment]
You mean this?

```
Looks like this is a new and empty installation of ioBroker.
Hostname needs to be updated to iobroker-69b945ffd9-qtpw8...
The host for instance "system.adapter.admin.0" was changed from "b12eb7896b5c" to "iobroker-69b945ffd9-qtpw8".
The host for instance "system.adapter.discovery.0" was changed from "b12eb7896b5c" to "iobroker-69b945ffd9-qtpw8".
The host for instance "system.adapter.info.0" was changed from "b12eb7896b5c" to "iobroker-69b945ffd9-qtpw8".
Done.
```

I think this is just the Log output for the renaming procedure (which is needed).

Do not see any other errors. So how does the admin looks after that? Does it look like a new installation?

Regards,
André

**Comment by dschaedl** [comment]
Hi André

Yes, that's waht I meant.
And Yes, the installation afterwards looks the same as a new installation.

current workaround: Stop/kill iobroker within the container, restore using "iobroker restore"; then restart the container. Afterwards (and some patient) all is restored.

br
Daniel

**Comment by buanet** [comment]
Did you check the restore.log? Does it look like the one in #138 ?

Regards,
André

**Comment by dschaedl** [comment]
Hi

No, I did not check the log and it's not available anymore - too bad.
I only relied on the output:
"
ioBroker backup file detected in /opt/iobroker. Restoring ioBroker...
Done.
"

so it could be a privilege issue... 
(I got it running and do currently not have the time to further investigate - pls feel free to close this issue)

regards
Daniel

**Comment by buanet** [comment]
Ok, thank you. I'll close this. Let me know if you got more information or problems with that.

Regards,
André
