### ISSUE TITLE
redis-database

### ISSUE THREAD

**Issue by unltdnetworx** [buanet/docker-iobroker#14]
Please add redis-server, because in images of iobroker, redis is standard.

`apt-get install redis-server`

and on startup something like
`service redis-server start`
to start.

**Comment by buanet** [comment]
Hi,
as Docker is made for running every application in its own Container I will not add redis to the iobroker-image.
A Docker container is NOT a virtual machine. Setting up different applications in a single container is senseless when you are running a Docker-environment.
Please use the official redis image and setup a separate container or feel free to fork my project. 

Regards, 
André 

closed #14
