### ISSUE TITLE
mysql-client als PACKAGE

### ISSUE THREAD

**Issue by adieball** [buanet/docker-iobroker#142]
Hi.

würde gerne mysqldump nutzen um über den back-up adapter auch die mysql DB zu sichern.
Leider ist mysqldump per default nicht im container und PACKAGES um mysql-client zu erweitern funktioniert auch nicht, kein Installationskandidat gefunden :-(

Wie bekomme ich mysqldump in den Container?

Danke

**Comment by buanet** [comment]
Hast du dazu mal Google befragt? 
Das ist kein Problem vom ioBroker Container. Du musst nur das passende Linux Paket finden. 
Bei mir hat der erste Google Treffer eine mögliche Lösung ausgespuckt die es zu testen gilt...

Kleiner Hinweis: Verbinde dich auf die Konsole des Containers und versuche über `apt-get install [paketname]` zu installieren. Wenn es da klappt, klappt es auch in der in der env PACKAGES.

Da ich hier keinen Fehler sehe, schließe ich den Issue.

MfG,
André

PS: Bitte beim nächsten Mal erst Google oder das ioBroker Forum befragen...
