### ISSUE TITLE
Not possible to enable Multihost inside the container

### ISSUE THREAD

**Issue by HB-F** [buanet/docker-iobroker#143]
I tried to activate the multihost inside the latest container version, but it is not possible and comes back with the following error:

root@ioBroker_Container:/opt/iobroker# sudo iobroker multihost enable
Multihost discovery server activated on this host. If iobroker is currently not running please start befeore trying to discover this host.
Important: Multihost discovery works with UDP packets. Make sure they are routed correctly in your network. If you use Docker you also need to configure this correctly.
Discovery authentication activated.
Enter secret phrase for connection: 
Repeat secret phrase for connection: 
(node:1377) [DEP0106] DeprecationWarning: crypto.createCipher is deprecated.
internal/fs/utils.js:269
    throw err;
    ^

Error: EACCES: permission denied, open '/opt/iobroker/iobroker-data/iobroker.json'
    at Object.openSync (fs.js:462:3)
    at Object.writeFileSync (fs.js:1384:35)
    at showMHState (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupMultihost.js:91:16)
    at /opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupMultihost.js:157:37
    at Cipher.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:168:28)
    at Cipher.emit (events.js:314:20)
    at endReadableNT (_stream_readable.js:1223:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/opt/iobroker/iobroker-data/iobroker.json'
}

Docker is running on a NAS system.
All variables inside the container are set according to the documentation.
The owner of the iobroker.json file is root, but it should not be a problem because the command will be performed with SUDO.

-rw-r--r--  1 root     root        4728 Okt 23 18:19 iobroker.json

The container is running with the macvlan.

Is there a error regarding the multihost with the latest version ?

**Comment by buanet** [comment]
No.
`sudo` in docker container is 👿 
`iobroker multihost enable` is not tested.

Please check readme.md of actual beta. Multihost support is still under development (but still running fine in my own production setup):
https://github.com/buanet/docker-iobroker/tree/beta#environment-variables
https://github.com/buanet/docker-iobroker/tree/beta#multihost-beta

If this solves your problem, please close this issue. 
Thank you.

Regards,
André

**Comment by HB-F** [comment]
OK, I think the problem is related to the permissions of the file iobroker.json. If I change the owner of the file to iobroker it is possible to change the parameter without problems. The problem is, as soon as the container will be recreated the owner of this file will be changed back to root. Also if I change the environment variables inside the container configuration. This will also set back the owner to root. Means after manual intervention regarding the owner of the file it will work.
