### ISSUE TITLE
vs code devcontainer with buanet

### ISSUE THREAD

**Issue by oweitman** [buanet/docker-iobroker#148]
hi, can you please check the following thread. in some cases (atm we can not determine the exactly cases) in the process of creation of the devcontainer, that is based on the buanet container, something is going wrong.
the renaming of the hostname fails sometimes, but only if some commands in the devcontainer ist executed.
more details in german in the following thread
https://forum.iobroker.net/topic/36034/visualstudio-code-und-devcontainer/86
more informations before and after this post
thanks

**Comment by buanet** [comment]
As I'm now reading the linked ioBroker forum thread, i will close this issue. 

Regards,
André
