### ISSUE TITLE
Fresh container restarts permanentely

### ISSUE THREAD

**Issue by TheMiller2015** [buanet/docker-iobroker#15]
Hello, I am new to ioBroker and do not have any preexisting installations. I tried to use your image on a home-server (non-nas) and extended my docker-compose with your image. No matter if I mount any volumes or not, the container restarts all the time with these logs

    iobroker     | Process 21 died: No such process; trying to remove PID file. (/var/run/avahi-daemon//pid)
    iobroker     | Stopping Avahi mDNS/DNS-SD Daemon: avahi-daemon.
    iobroker     | Starting Avahi mDNS/DNS-SD Daemon: avahi-daemon.

My docker-compose.yml looks like this

    iobroker:
      image: buanet/iobroker:latest
      container_name: iobroker
      volumes:
      - /etc/localtime:/etc/localtime:ro
    #      - /root/docker/data/iobroker/iobroker:/opt/iobroker
    #      - /root/docker/data/iobroker/transfer:/tmp
        hostname: homeserver
    # privileged: true
        network_mode: host
        ports:
          - 8081-8084:8081-8084
        restart: always

I don't know if we should write in english or german here. I hope you can help me getting this to work. All my other containers work.

Thanks for your help and work

**Comment by buanet** [comment]
Hallo,
kann mir das Verhalten leider nicht erklären. Habe eben mal das aktuelle (latest-)Image geladen und einen  Container erstellt. Läuft wunderbar. Deine Parameter sehen gut aus. Wenn du allerdings network_mode: host nutzt, brauchst du keine Ports angeben. Oder du verwendesT "bridge". Als Hostname könntest du mal iobroker versuchen. 
Die Logeinträge vom Avahi sind normal. Habe ich auch. Das kommt weil ich da was basteln musste damit der Dienst läuft. 
Mehr fällt mir leider nicht ein. Habe es noch nie mit Docker Compose getestet. Sorry.

MfG,
André

**Comment by buanet** [comment]
Hallo,
habe mir das Thema nochmal angeschaut und konnte das Verhalten reproduzieren. Offenbar gibt es Unterschiede bei den Docker Environments, sodass es in einigen Umgebungen vorkommen kann, dass der Container nach einem erfolgreichen Durchlauf des Stat-Scriptes automatisch beendet wird. Habe in das Start-Script nun eine Funktion eingebaut, die den Container am Leben erhalten sollte. 
Ist im aktuellen **Beta** enthalten. Build auf dem Docker-Hub läuft gerade. Bitte einmal testen!

MfG,
André

**Comment by TheMiller2015** [comment]
Hallo,

vielen Dank für die schnelle Rückmeldung. Ich habe die aktuelle beta gezogen und iobroker startet. Vielen Dank, du hast mich davor bewahrt, ein weiteres Image erstellen zu müssen ;)

Aber noch eine Anmerkung: Mappt man gleich zum ersten Start das Verzeichnis /opt/iobroker, startet dieser nicht durch. Also muss man erst ein Volume auf /tmp mappen, den Container starten, innerhalb des Containers die Daten von /opt/iobroker in /tmp kopieren, den Container stoppen, die Daten aus dem Transferverzeichnis in das neue zu mappende Verzeichnis kopieren und den Container mit gemapptem Verzeichnis für /opt/iobroker neu erstellen. Hier ein kleines walkthrough.

**docker-compose.yml** (zum Erstellen der ioBroker-Daten

    .. .. ..
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/docker/data/iobroker/transfer:/tmp

Dann in der shell weiterarbeiten:

    ** Container erstellen und starten **
    docker-compose up -d [containername]

    ** Shell des Containers aufrufen**
    docker exec -ti [containername] /bin/bash

    ** Erstellte ioBroker-Daten nach tmp kopieren **
    cp -r /opt/iobroker /tmp

    ** Shell des Containers verlassen**
    exit

    ** Container stoppen und verwerfen**
    docker-compose stop [containername]
    docker-compose rm [containername]

    **Daten auf dem Host kopieren**
    cp -r /root/docker/data/iobroker/transfer/. /root/docker/data/iobroker/data

Nun die docker-compose.yml dahingehend anpassen, dass das ioBroker-Verzeichnis gemappt wird:

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/docker/data/iobroker/data:/opt/iobroker

Nun startet ioBroker durch und schreibt die Daten direkt auf den Host in ein Verzeichnis, welches mitgesichert werden kann. Ich hoffe, ich habe mich jetzt mit den Pfaden nicht vertippt.

**Comment by buanet** [comment]
Hallo,
Kennst du das hier: https://buanet.de/2017/09/iobroker-unter-docker-auf-der-synology-diskstation/
Da steht es beschrieben. Eigentlich ist das Image für Docker auf der Synology DiskStation gedacht. Ziel war es weitgehend ohne Kommandozeile aus zu kommen um es auch Anfängern zu ermöglichen iobroker unter Docker in Betrieb zu nehmen...

MfG, 
André 

Closed #15

**Comment by TheMiller2015** [comment]
Hey. Ja, kenne ich. Ich wollte es hier aber nochmal erwähnen, falls jemand anderes selbiges vor hat, aber dein Tutorial nicht kennt. Danke für deine Arbeit.

**Comment by buanet** [comment]
Hallo,
leider verstehe ich die Anforderung nicht. Wenn du mit Docker-Compose arbeitest, dann erstellst du doch einfach mehrere Container gleichzeitig. Also hoffentlich einen für ioBroker, einen für Asterisk usw... Oder installierst du im ioBroker Container einen Asterisk? Sorry, komme da gerade nicht mit...

MfG,
André

**Comment by schmupu** [comment]
Du hast Recht. Ich habe es jetzt geändert. Es laufen ioBroker (dein cooler Container), Redis und Asterisk in jeweils eigenen Docker Containern. Mit Docker Composer überhaupt kein Problem und auf Knopfdruck erstellt. Selbst die paar zusätzlichen Pakete wie vim zu installieren passiert automatisch. Echt sehr cool.
