### ISSUE TITLE
Adapter updates on a installation with docker container does not work

### ISSUE THREAD

**Issue by nkleber78** [buanet/docker-iobroker#150]
I have serious problems with my installation inside a docker container. The main problem is, that on every update of a adapter, the rest of the installation is destroyed in a way that the adapters continuous needs reinstalling. See one sample in screenshot. To get the system running stable the only way is to execute the reinstall.js script, but then all the adapters are again on the previous version. 
<img width="1021" alt="Screenshot 2020-11-19 at 23 57 05" src="https://user-images.githubusercontent.com/35381530/99734355-fb1dfa80-2ac2-11eb-9c0f-3674c8acf5da.png">

Is there any idea what could cause such behaviour and how to solve this?

here a complete log of the reinstall.js log created [2020-11-19T23_36_15_330Z-debug.log](https://github.com/ioBroker/ioBroker.docs/files/5570331/2020-11-19T23_36_15_330Z-debug.log)

**Comment by Apollon77** [comment]
According to the log something is wrong with the npm reposirory ... In my eyes one idea wouldbe to use the backup and start fresh so that all adapters are installed fresh once

**Comment by nkleber78** [comment]
I did such a fresh installation already before. That means I started a new docker container and just mount the folders to the container. Following is mounted to the container
![image](https://user-images.githubusercontent.com/35381530/99940616-d0ef6580-2d6c-11eb-8d5f-032442880c42.png)

**Comment by buanet** [comment]
NOPE! No way that this will work! You simply have to mount one single folder, in your case:

docker/IOBroker/    to    /opt/iobroker

...if you really need you might be mount the userscripts folder too.

Please keep your backup file and start over with a new and empty folder für /opt/iobroker (only place the backup there).
Then start your new container and let him restore your backup...

For details see readme.md.

Regards,
André

**Comment by nkleber78** [comment]
Why do i need to mount everything from /opt/iobroker? For me it would better if I am able to mount another share for the Backsups. Otherwise it is everything in one folder on diskstation. And I think it does not really makes sense to mount the node_modules folder to a fresh installation where might some packages are outdated due to newer iobroker installation...

**Comment by nkleber78** [comment]
Btw. i just did a start with the backup and found out that the instances are not installed. As I can see my backup seems to be ok. The Backup is made with iobroker.Backitup
[iobroker_2020_11_22-02_00_13_StandardBackup_backupiobroker.tar.gz](https://github.com/buanet/docker-iobroker/files/5584088/iobroker_2020_11_22-02_00_13_StandardBackup_backupiobroker.tar.gz)

**Comment by buanet** [comment]
> Why do i need to mount everything from /opt/iobroker? For me it would better if I am able to mount another share for the Backsups. 

Short: It is not designed to work that way.

> Otherwise it is everything in one folder on diskstation. 

It will be the same when you use a raspberry pi or something.

> And I think it does not really makes sense to mount the node_modules folder to a fresh installation where might some packages are outdated due to newer iobroker installation...

Don't get it. 

> Btw. i just did a start with the backup and found out that the instances are not installed. As I can see my backup seems to be ok. The Backup is made with iobroker.Backitup

Ya, after restore ioBroker has to install the instances. It will do it automatically. But after that you will have a clean new ioBroker Installation which absolutely fits you node version... 

BTW. I removed your Backup File from your post. Doesn't make sense to post that here in public...

Regards,
André

**Comment by nkleber78** [comment]
Ok, got it so far. But in my case the Instances are not installed by iobroker. The created package.json just contains admin, discovery, info and js_controler but nothing else. The restore log shows some errors but I don't understand the reason...
[restore.log](https://github.com/buanet/docker-iobroker/files/5584552/restore.log)

**Comment by buanet** [comment]
Restore log says, that restore was not successful. 

1. Seems as there is a problem with sudo. Are you running your container in network mode "Host"? If yes, it is caused by a known kernel issue in Synology DSM. Something I can not fix...
2. There is a permission issue while accessing states.json. This should be fixed in v5.1.0. As I didn't see any container log, I can not determine your image version... 

If automatic restore does not work in your case, you can try to restore it manually. just set up a new container. After a successful start of the container put your backup back to your ioBroker folder. Then you can restore it by backitup adapter or command line. 

Regads,
André

BTW: Do you know the iobroker forum thread (also linked in readme.md) or my tutorials from smarthome.buanet.de? As I do not see any real issue here I would request you using the regular ways for getting answers to support questions. 
If you agree feel free to close this issue. 
Thank you.

**Comment by nkleber78** [comment]
Hi Andre,
many thanks for your help. It seems that the issue was caused by the host mode of the container. Does this mean on DSM host mode is not possible for iobroker because of this kernel issue? I updated to the latest docker container, started with backup in non host mode and the backup was successful.
The hint with the host mode did the job. Again many thanks

**Comment by buanet** [comment]
> Does this mean on DSM host mode is not possible for iobroker because of this kernel issue?

It is possible, but with limitations. I would clearly not recommend that on Synology Disk Stations at the moment.

As it looks like you got it running, you agree in closing this issue?  

Regards,
André

**Comment by nkleber78** [comment]
Ok, thanks. It clear now
