### ISSUE TITLE
Admin/Vis/Flot very slow @ Synology DS 412+

### ISSUE THREAD

**Issue by Fatmax1982** [buanet/docker-iobroker#153]
Hi,
i am using Iobroker with Docker on Synology Diskstation 412+ with upgraded RAM to 4 GB.

All works fine but Admin, Vis-Edit and Flot are very slow.
Opening takes up to 1 Minute until all is loaded.
e.g. at Admin, the frame and background is loaded with in one or two seconds, the content and the menu takes then up to one minute.
CPU and RAM loadings are very low, this should not be the problem

It makes no difference on using host or bridge mode. 
Whats wrong here? 
Thanks for help. 

Fatmax1982

**Comment by Apollon77** [comment]
Network connection? Client webbrowser?

**Comment by Fatmax1982** [comment]
> Network connection? Client webbrowser?

Wired Network connection, 100Mbit, no other problems with diskstation network speed but what i see is that speed at ressource monitor on diskstation is only at KBit/s when i load the iobroker in browser.

Browser is Google Chrome.

**Comment by Apollon77** [comment]
Yes with Client I more meaned the PC/laptop that has the browser running

**Comment by Fatmax1982** [comment]
> Yes with Client I more meaned the PC/laptop that has the browser running

Client is on a PC with Intel Core I7, 16GB RAM, Win10, Wired connection 100Mbit.
I had before iobroker running on Rock64, it worked well with this PC.

**Comment by buanet** [comment]
Hi,
do you use any other containers? How is the speed there? 
What about your resources? CPU/ RAM highly used? How does it look like in the Docker Admin Panel on the Disk Station Manager? 

What about the DSM interface? Is it in normal speed?

Did you test connecting from other Devices? Are they slow too? 

Don't know what's wrong here. Tested the image, See no general issue with it. 
If you speak German it might be helpful to post your question to the [ioBroker forum thread](https://forum.iobroker.net/topic/4733/howto-iobroker-unter-docker-auf-synology-diskstation). There are some DiskStation (pro)users reading :), maybe someone has other ideas. 

Regards,
André

**Comment by buanet** [comment]
Hi, as my questions are still unanswered and I saw your post at the ioBroker Forum thread, I'll close this issue. 

Regrads,
André
