### ISSUE TITLE
discovery adapter does not find devices

### ISSUE THREAD

**Issue by wernersv** [buanet/docker-iobroker#154]
Is there a way to get discovery working when using docker?
I've tried to use smcroute but did not get it working.

**Comment by buanet** [comment]
Hi,
it's depending on you network. I think you have to run the container in MACVLAN mode to get discovery working.
But I never used the adapter. So no guarantee it then discovers every service...

Regards,
André

**Comment by wernersv** [comment]
Thx for the answer. Although I was hoping to get it working without MACVLAN. It just doesn't feel right to expose the container completely.

**Comment by buanet** [comment]
I'm sorry, it's not my fault. It's a Docker thing.
But if you think about it's gonna be logical that you can't receive multicast packages to a container running in bridged mode. This not only affects the discovery adapter. There are some other Adapters which work with multicast packages to discover smart home devices. 

If you don't want to run your container in MACVLAN or host mode, you can use a multihost slave like a raspberry pi to run adapters which need this kind of communication. Just think about. 

If your question/ problem is solved, please close this issue. Thank you.

Regards,
André
