### ISSUE TITLE
backitup not working

### ISSUE THREAD

**Issue by neoristic** [buanet/docker-iobroker#155]
Hi,

looks like backitup is not working correct. i got all the time this error message and the settings are exactly the same as on my ubuntu server: 468) Error: Command failed: sudo mount -t cifs -o username=admin,password=****,rw,file_mode=0777,dir_mode=0777 //192.168.0.9/Home/iobroker_backup /opt/iobroker/backups mount: /opt/iobroker
permission denied.

to avoid the mount issue i just mounted the folder directly over docker adding path. so far it worked now as local drive. but now the next issue. after i started the recovery it opens a new webbrowser page on the iobroker server with port 8091. so not working. i tried to map this port also in the docker variables but it want work, page cannot be found and the restore is not starting (working). 

btw im using unraid server with your docker app.
ich sprech auch deutsch ;-)

Best Regards
Neo

**Comment by buanet** [comment]
Hallo Neo,
erster Punkt: sudo im Container = grundsätzlich nix gut. (Wird aber leider in vielen Adaptern standardmäßig verwendet.)

Das Thema mounten einer Netzwerkfreigabe im Container hängt von vielen Faktoren ab. Der Container ist nun mal nicht als Virtuelle Maschine zu betrachten, sondern vielmehr als einzelner Prozess auf dem Host. Aus dieser Definition ergibt sich, dass der Backup Prozess eigentlich nicht in den Container gehört, sondern als eigener Prozess auf den Host. Die für ein Backup relevanten Daten sollten ja in volumes oder mounts sowieso auf dem Host liegen...

Was bei deinem Mount innerhalb des Containers schief läuft kann ich nicht beurteilen. Mit diesem Thema habe ich mich, zumindest innerhalb des Containers, noch nicht auseinander gesetzt. 

Den Fehler mit der Webbrowser Page auf Port 8091 habe ich auch schonmal gehört. Bisher konnte mir noch niemand sagen was der Backitup Adapter da tut. Vielleicht kannst du das (z.B. über das ioBroker Forum) in Erfahrung bringen?

Ich selbst nutze den Backitup Adapter nur zum Erstellen des Backups für meine Container Upgrades ([Details siehe hier](https://smarthome.buanet.de/2020/10/iobroker-docker-container-backup-restore/)). Meine Haupt Backupstrategie (für alle meine Container) läuft logischer Weise komplett über den Host. Wenn ich also mal zurück muss, stelle ich das ioBroker Verzeichnis aus dem Backup auf dem Host wieder her.

MfG,
André

**Comment by buanet** [comment]
Leider habe ich hier jetzt zwei Wochen lang nichts gehört, daher schließe ich den Issue. 
Sollte es weiter Probleme geben melde dich gerne.

MfG,
André
