### ISSUE TITLE
Question regarding Backup

### ISSUE THREAD

**Issue by uwe72** [buanet/docker-iobroker#156]
I am new to docker and also to this image.

I have a iobroker backup of my old computer done by backitup adapter. When i put this file (iobroker_2021_01_06-20_18_09_backupiobroker.tar.gz) to the folder /opt/iobroker while starting the container it regognized that there is a backup file. But after started up iobroker was like totally "fresh", i didn't see my "old backuped files". What i am doing wrong? I started the container like this:
`
docker run -p 8081:8081 --name iobroker -v iobrokerdata:/opt/iobroker bua-net/iobroker:latest
`

Second question: The second attemp was without this backup file, i wanted to see that all new created files/datas are stored in /opt/iobroker. But the directory was empty, everything was inside: /var/lib/docker/volumes/iobrokerdata/_data/iobroker-data

Do i think wrong?

Auch ich spreche deutsch :-)

Best Regards
Uwe

**Comment by buanet** [comment]
Hallo Uwe,

dein docker run Befehl sieht mir nicht korrekt aus.  
`bua-net/iobroker:latest`
das dürfte nich mein Image sein. Der Bindestrich ist zuviel
`buanet/iobroker:latest`

Dann die Frage: Wird beim Start denn dein, bis auf das Backup, leere ioBroker-Verzeichnis bzw. Volume auf dem Host mit Daten gefüllt? 
Um zu sehen ob alles Ordnungsgemäß läuft benötige ich das Log aus dem Container. Kannst du das bereit stellen? 

Manchmal funktioniert der automatische restore vom Startup Script leider nicht. Dann könntest du auch versuchen den Restore in der frischen ioBroker Installation über die Kommandozeile des Containers zu erledigen. 

`pkill -u iobroker`
`iobroker restore 0`
Und dann ein Neustart des Containers...

MfG.
André

**Comment by uwe72** [comment]
Hallo Andre,

habe nun mal alles nochmals gelöscht. Mit dem Verzeichnis habe ich generell nun mal besser verstanden, ohne das Thema Backup verstehe ich es nun, insbesondere wo die Daten landen.

Mein Iobroker Datenverzeichnis liegt nun unter:
`/home/uwe72/iobrokerdata`

Wenn ich dieses anlege und das Backup-File reinlege und den Container das erste mal starte, bekomme ich folgende Fehlermeldung:
![image](https://user-images.githubusercontent.com/61848539/104092896-42d12f00-5287-11eb-9c0d-c597b00f8d2c.png)

(Was Du vorgeschlagen hast, pkill.... habe ich noch nicht ausprobiert. Prinzipiell wäre es nun auch nicht schlimm wenn das Einspielen des Backups nicht funktioniert. Bin grad am Wechseln von einem alten NUC auf einen neuen. Ich richte dies nun gerne auch nochmals neu ein, nun ja auch mit Docker. Mir gehts eher darum wie ich zukünftig ein Backup mache. Es würde ja dann auch reichen, das o.g. Verzeichis wegzusichern und danach wieder befüllen?)

**Comment by buanet** [comment]
Hallo Uwe,

dein Backupfile hat einen falschen Namen. 
> Since v4.1.0 it is also possible mount a folder filled up with an iobroker backup file created using iobroker backup command or backitup adapter. Please make sure the name of your backup file ends like this: *_backupiobroker.tar.gz".

Siehe: https://github.com/buanet/docker-iobroker#mounting-folder-volume

MfG,
André

**Comment by uwe72** [comment]
Danke Dir Andre,
hatte es parallel auch selber festgestellt. Es hat nun alles out-of-the-box mit dem Backup funktioniert.

DANKE!
