### ISSUE TITLE
Frage zu Shelly Adapter mit COAP

### ISSUE THREAD

**Issue by uwe72** [buanet/docker-iobroker#157]
Hallo, weiß nicht, ob ich diese Frage hier auch stellen kann.

Iobroker läuft super über diesen Container.

Betreibe den über ein docker-compose file:
![image](https://user-images.githubusercontent.com/61848539/104451997-a2d71680-55a2-11eb-85a3-feb12ad3a9e1.png)

Habe nun nur das Problem, dass keine Shellys über COAP gefunden werden können. Es wird gesucht und gesucht, aber nichts gefunden:
![image](https://user-images.githubusercontent.com/61848539/104452070-c4380280-55a2-11eb-9a4e-1c3a58f676b0.png)

Muss man da auch irgendwie noch was beachten oder ein Port-Mapping, o.ä. machen?

Wenn Thema nicht zum eigentlich Adapter gehört, dann Ticket bitte entfernen.

Danke und Grüße
Uwe

**Comment by fzzybllz** [comment]
Hallo Uwe,

das ist schnell beantwortet. Der COAP Mode ist nicht per Bridge-Container möglich. Auch nicht per Port-Mapping. Schau mal in die Shelly-Adapter Doku, dort müsste es drin stehen.

Entweder du wechselst auf den MQTT Modus oder du verwendest den iobroker im MACVLAN, dann funktioniert auch COAP.

Viele Grüße,
Dominik

**Comment by uwe72** [comment]
Danke Dir Dominik. Werde mich in beide Varianten mal einlesen und dann schauen was besser für mich ist. MQTT wollte ich mir schon lange mal anschauen, vielleicht ist dies nun eine gute Gelegenheit!

DANKE!

**Comment by fzzybllz** [comment]
Gerne,

für Shelly ist das MQTT-Thema eigentlich recht 'langweilig'/einfach. Du kannst den Shelly-Adapter selbst einfach als MQTT-Broker benutzen in dem du den Adapter auf MQTT umstellst.
Danach einfach im Shelly die Adressdaten aus dem Adapter eingeben. Achtung: Das entsprechende MQTT Menü im Shelly ist nur via Browser erreichbar, nicht per App. Portfreigabe Container nicht vergessen + Vorsicht wegen dem Port, falls du noch den Sonoff oder MQTT Adapter benutzen willst.

Wenn du allerdings gleich auf eine 'richtige' MQTT-Umgebung wechseln möchtest, brauchst du einen Broker (evtl. extern) und einen Subscriber im iobroker. Dann brauchst du keinen Shelly-Adapter. Der ist selbst Broker. Ich würde allerdings erstmal bei Variante 1) bleiben. Ist deutlich einfacher.

**Comment by uwe72** [comment]
Hallo Dominik,

das Ganze Vorhaben (ioBroker auf docker) übersteigt glaub leider meine Kenntnisse.

Habe zwar ioBroker ohne Probleme im Docker am Laufen, auch der Shelly Adapter läuft mit MQTT. Habe mal ein Shelly Device testweise auf MQTT umgestellt. Läuft.

Was ich aber auch brauche ist, dass ich über Alexa meine Shellys steuere (Licht ein/aus). Das geht ja dann nicht mehr so einfach, da die Shelly-Cloud abgeschaltet werden muss für MQTT.

Bin dann den Weg gegangen über den iobroker-skill von Alexa.

Dazu benötige den Alexa2 Adapter in Alexa (so oder so hätte ich den Alexa Adapter wieder). Da habe ich dann wohl auch das Problem, dass dieser Adapter nicht mehr so einfach läuft im "docker iobroker". Hier wird dann auch wieder das MACVLAN als Lösung genannt.

Aber genau beim Aufsetzen des MACVLAN verlassen sich meine Kenntnisse :-(

Gibts da einen "einfachen Befehl" wie man dies anlegt. Ich gehe davon aus, dass dann im yml-File im Bereich iobroker auf dieses MACVLAN verwiesen werden muss.

VG Uwe

**Comment by buanet** [comment]
Hallo Uwe, 
diese Fragen solltet ihr eher im ioBroker Forum besprechen.
deine MACVLAN Config sieht auf den ersten Blick gut aus.. 

Meine Tutorials dazu kennst du? https://smarthome.buanet.de/2020/09/macvlan-ueber-portainer-einrichten/ 

MfG,
André

**Comment by uwe72** [comment]
Alles klar, danke. Habe die Frage im ioBroker Forum auch nun gestellt.
Dein Tutorial kenne ich, mein aktueller Stand ist basierend auf deinem docker-compose Beispiel im Tutorial.

Danke und Grüße!

**Comment by ruhlandm1** [comment]
@uwe72 : Kannst du den Link zum entsprechenden Iobroker Thread posten? bzw. konntest du das Problem lösen? Ich stehe vor genau dem gleichen Problem.
