### ISSUE TITLE
Das Depot »http://deb.debian.org/debian buster-updates InRelease« ist nicht signiert

### ISSUE THREAD

**Issue by fs-plugins** [buanet/docker-iobroker#158]
edit: installiert per :latest

Hallo,

leider kann ich samba nicht installieren, Fehlermeldungen wie
_Durch Clearsign signierte Datei ist nicht gültig, »NOSPLIT« erhalten (erfordert das Netzwerk eine Authentifizierung?)_
_E: Das Depot »http://security.debian.org/debian-security buster/updates InRelease« ist nicht signiert._
kommen bei 
curl -sL https://deb.nodesource.com/setup_12.x | bash -
apt-get update && apt-get -y upgrade
und bei 
apt-get install samba-common
_E: Paket samba-common kann nicht gefunden werden._

**Comment by fs-plugins** [comment]
evtl helfen die Detailausgaben weiter:
`grep -P '^[ \t]*[^#[ \t]+' /etc/apt/sources.list /etc/apt/sources.list.d/*.list 
/etc/apt/sources.list:deb http://deb.debian.org/debian buster main
/etc/apt/sources.list:deb http://security.debian.org/debian-security buster/updates main
/etc/apt/sources.list:deb http://deb.debian.org/debian buster-updates main
/etc/apt/sources.list.d/nodesource.list:deb https://deb.nodesource.com/node_12.x buster main
/etc/apt/sources.list.d/nodesource.list:deb-src https://deb.nodesource.com/node_12.x buster main

apt update
OK:4 https://deb.nodesource.com/node_12.x buster InRelease    
Holen:1 http://security.debian.org/debian-security buster/updates InRelease
Holen:2 http://deb.debian.org/debian buster InRelease
Holen:3 http://deb.debian.org/debian buster-updates InRelease
Fehl:1 http://security.debian.org/debian-security buster/updates InRelease
  Durch Clearsign signierte Datei ist nicht gültig, »NOSPLIT« erhalten (erfordert das Netzwerk eine Authentifizierung?)
Fehl:2 http://deb.debian.org/debian buster InRelease
  Durch Clearsign signierte Datei ist nicht gültig, »NOSPLIT« erhalten (erfordert das Netzwerk eine Authentifizierung?)
Fehl:3 http://deb.debian.org/debian buster-updates InRelease
  Durch Clearsign signierte Datei ist nicht gültig, »NOSPLIT« erhalten (erfordert das Netzwerk eine Authentifizierung?)
Paketlisten werden gelesen... Fertig
N: Weitere Details zur Erzeugung von Paketdepots sowie zu deren Benutzerkonfiguration finden Sie in der Handbuchseite apt-secure(8).
N: Eine Aktualisierung von solch einem Depot kann nicht auf eine sichere Art durchgeführt werden, daher ist es standardmäßig deaktiviert.
E: Das Depot »http://security.debian.org/debian-security buster/updates InRelease« ist nicht signiert.
E: Fehlschlag beim Holen von http://security.debian.org/debian-security/dists/buster/updates/InRelease Durch Clearsign signierte Datei ist nicht gültig, »NOSPLIT« erhalten (erfordert das Netzwerk eine Authentifizierung?)
E: Fehlschlag beim Holen von http://deb.debian.org/debian/dists/buster/InRelease Durch Clearsign signierte Datei ist nicht gültig, »NOSPLIT« erhalten (erfordert das Netzwerk eine Authentifizierung?)
E: Das Depot »http://deb.debian.org/debian buster InRelease« ist nicht signiert.
N: Eine Aktualisierung von solch einem Depot kann nicht auf eine sichere Art durchgeführt werden, daher ist es standardmäßig deaktiviert.
N: Weitere Details zur Erzeugung von Paketdepots sowie zu deren Benutzerkonfiguration finden Sie in der Handbuchseite apt-secure(8).
E: Fehlschlag beim Holen von http://deb.debian.org/debian/dists/buster-updates/InRelease Durch Clearsign signierte Datei ist nicht gültig, »NOSPLIT« erhalten (erfordert das Netzwerk eine Authentifizierung?)
E: Das Depot »http://deb.debian.org/debian buster-updates InRelease« ist nicht signiert.
N: Eine Aktualisierung von solch einem Depot kann nicht auf eine sichere Art durchgeführt werden, daher ist es standardmäßig deaktiviert.
N: Weitere Details zur Erzeugung von Paketdepots sowie zu deren Benutzerkonfiguration finden Sie in der Handbuchseite apt-secure(8).`

**Comment by buanet** [comment]
Hallo,
ein paar mehr Infos wären schick. Image version? Log vom Container start? Hast du mal versucht das Paket "samba-common" über die ENV "PACKAGES" zu installieren? Wie sieht das Log dazu aus? 

MfG,
André

**Comment by fs-plugins** [comment]
sorry, ich nutze portainer weil es mir zur einfachen Nutzung von Docker-Contaienern allenthalben anempfohlen wird (nicht, weil ich mich auskenne...)
Image-Version 5.1.x
ich hatte den funktionierenden container per Recreate (latest) wie immer aktualisieren wollen, danach funktioniert ja leider jedesmal samba nicht mehr
habe gestern (da hier die Haussteuerung drauf läuft) einen neuen container angelegt und den Ordner-Inhalt iobroker-data übertragen, alten container gestoppt und den neuen wieder komplett am laufen (hier funktioneren auch update/upgrade und install samba wieder), einige Stunden Arbeit und nicht sicher ob ich alle Anzeigen mit geänderter Datenquelle wirklich gefunden habe, ist ein umfangreiches System...
da das container-Netzwerk immer noch auf host steht weil mir die Netzwerkgeschichte nicht gelingen will ist eine parallel laufende instanz leider nicht möglich, sonst würde ich gerne Vergleichen bzw Test duchführen

meine Hoffnung war eine Rep. des Systems
von Recreate werde ich jedoch wohl künftig die Finger lassen, hat zwar vielmals seinen Dienst getan aber besser ich update im terminal (und sehe die Ausgaben) als dass ich zwei Tage später ein Problem bemerke :)

start-log im parallel-Start (sieht am Anfang komplett anders aus als im funktionierenden System):

-----               ZWAVE:     false                   -----,
-----               USBDEVICES: none                    -----,
-----               SETUID:    1000                    -----,
-----               SETGID:    1000                    -----,
-----               PACKAGES:  nano                    -----,
-----               AVAHI:     false                   -----,
-----                       ENV                        -----,-----                                                  -----,
------------------------------------------------------------,
Installing additional packages is set by ENV.,
-----         Step 1 of 5: Preparing container         -----,
 ,
The following packages will be installed: nano...,
E: Das Depot »http://security.debian.org/debian-security buster/updates InRelease« ist nicht signiert.

den rest habe ich mal weggelassen...

**Comment by buanet** [comment]
Wird geschlossen wegen: #161 .

MfG,
André
