### ISSUE TITLE
WLan Wetterstation

### ISSUE THREAD

**Issue by bertl83** [buanet/docker-iobroker#159]
Servus!
Ich bin mit Linux leider ned ganz so fit.
Hab mir nun mein WLan Wetterstation https://github.com/SBorg2014/WLAN-Wetterstation
eingebunden, und passt so weit auch. Was ich aber nicht hinbekommen, den Dienst zu installieren:

"
Einstellung als Autostart (Möglichkeit #1 per systemd): Sofern möglich sollte diese Variante benutzt werden, da sie wesentlich Anwender freundlicher ist. Wir legen zuerst im Terminalfenster die nötige Datei an sudo nano /etc/systemd/system/wetterstation.service
Diese bekommt folgenden Inhalt:

[Unit]
Description=Service für ioBroker Wetterstation

[Service]
ExecStart=/home/iobroker/wetterstation.sh

[Install]
WantedBy=multi-user.target

Die Beschreibung ist frei wählbar, der Service muss ggf. entsprechend Eurem Pfades angepasst werden, je nach dem wo Ihr das Skript liegen habt. Speichern und mittels sudo chmod +x /etc/systemd/system/wetterstation.service ausführbar machen.
Damit das Skript verfügbar ist den Daemon neu laden: sudo systemctl daemon-reload
Damit es beim booten automatisch geladen wird: sudo systemctl enable wetterstation.service

Steuern kann man das Skript dann folgendermaßen:
Start: sudo systemctl start wetterstation
Stop: sudo systemctl stop wetterstation
Neustart (zB. bei Änderungen): sudo systemctl restart wetterstation
Status: sudo systemctl status wetterstation

Einstellung als Autostart (Möglichkeit #2 per cronjob): Wir benutzen im Terminalfenster einen beliebigen Editor (z.B. nano) und bearbeiten den Autostart mit crontab -e (als Benutzer mit root-Rechten) oder sudo crontab -e (falls keine root-Rechte) und erweitern das Dokument zB. ganz am Ende, oder an einer gewünschten Stelle, mit folgenden Zeilen:

@reboot /home/iobroker/wetterstation.sh &
2 0 * * * pkill -9 wetterstation.sh && /home/iobroker/wetterstation.sh &

(/home/iobroker ist das Installationsverzeichnis, ersichtlich in der debug-Ausgabe, wetterstation.sh ist der Name des Skriptes). Die zweite Zeile beendet und startet jede Nacht um 0:02 Uhr das Skript neu.

Wichtig ist hierbei, falls es am Ende eingefügt wurde, dass nach dem & noch mindestens eine Leerzeile folgt, sonst laufen sämtliche cronjobs nicht mehr!

Nach dem Speichern der Datei und einem Neustart des Linux-Clients läuft die Datenübertragung automatisch und die Wetterdaten werden im eingestellten Zeitintervall übermittelt (dies kann im Datenpunkt Zeitstempel überprüft werden). Kleiner Hinweis am Rande: Es funktioniert nicht das Skript in einer Putty-Session dauerhaft zu starten. Solange die Sitzung aktiv ist läuft es zwar, mit beenden der Sitzung wird dann aber auch das Skript beendet...
"

systemctl bekomm ich nicht ans laufen und mit dem crontab befehlt passiert leider auch nix.
Kannst du mir da weiterhelfen?

**Comment by bertl83** [comment]
hat sich erledigt, danke. Cron musste erst noch per apt-get geholt werden

**Comment by buanet** [comment]
Hallo,
auch wenn sich dein Problem offenbar von allein gelöst hat. :) Ich würde das Script für die Wetterstation nicht manuell mit in den Container installieren. Das ist einfach völlig entgegen des Docker gedanken und wird spätestens beim Update des Containers zu Problemen (eine notwendigen Neuinstalltion des Scripts) führen. 
Eleganter wäre da die Verwendung eines separaten Containers. Da ich das Projekt leider nicht kenne, kann ich aber nicht beurteilen ob es da schon was gibt. Habe mich mal im verlinkten Forum Thread zu Wort gemeldet.

MfG,
André

**Comment by bertl83** [comment]
Moing.

Danke dir für den Hinweis.

Das ich den Container von dir ziemlich verwüstet hab ist mir schon klar, liegt aber einfach daran

das ich bis dahin absolut nix mit Linux Docker und Container zu tun hatte.

Bin da eher n Microsoft Kind :)

 

Aber ich denke wenn man ein leeres Linux nimmt, Ubunto oä. dann sollte man da durchaus alleine

das Script laufen lassen können.

Der ioBroker muss ja ned auf der gleichen Maschine laufen, sondern wird auch nur per IP angesprochen.

 

Influx und Grafana laufen ja auch in eigenen Dockern, daher denke ich sollte das wohl auch gehen.

 

Ich hab in deinen Docker ja einiges per apt-get nachgeholt, und auch das Mount auf ein Share der QNAP

war n ganz schöner kampf :) aber wie gesagt, alles geschuldet der fehlenden Erfahrung.

 

Gruß

Albert

 
 

Gesendet: Montag, 18. Januar 2021 um 21:50 Uhr
Von: "André Germann" <notifications@github.com>
An: "buanet/docker-iobroker" <docker-iobroker@noreply.github.com>
Cc: "bertl83" <albertmiethaner@gmx.de>, "State change" <state_change@noreply.github.com>
Betreff: Re: [buanet/docker-iobroker] WLan Wetterstation (#159)


 

Hallo,
auch wenn sich dein Problem offenbar von allein gelöst hat. :) Ich würde das Script für die Wetterstation nicht manuell mit in den Container installieren. Das ist einfach völlig entgegen des Docker gedanken und wird spätestens beim Update des Containers zu Problemen (eine notwendigen Neuinstalltion des Scripts) führen.
Eleganter wäre da die Verwendung eines separaten Containers. Da ich das Projekt leider nicht kenne, kann ich aber nicht beurteilen ob es da schon was gibt. Habe mich mal im verlinkten Forum Thread zu Wort gemeldet.

MfG,
André

**Comment by bertl83** [comment]
Hat sich wohl erledigt das Thema mit dem WLan Wetter Adapter.

Was wär denn deine Empfehlung nun?

Soll ich mir n Ubuntu Docker nehmen und darin nur das Script laufen lassen, damit

Ich deinen Docker wieder „Clear“ laufen lassen kann?

 

Danke dir schonmal für deine Hilfe!

 

Gruß

Albert

 

Von: André Germann <notifications@github.com> 
Gesendet: Montag, 18. Januar 2021 21:50
An: buanet/docker-iobroker <docker-iobroker@noreply.github.com>
Cc: bertl83 <albertmiethaner@gmx.de>; State change <state_change@noreply.github.com>
Betreff: Re: [buanet/docker-iobroker] WLan Wetterstation (#159)

 

Hallo,
auch wenn sich dein Problem offenbar von allein gelöst hat. :) Ich würde das Script für die Wetterstation nicht manuell mit in den Container installieren. Das ist einfach völlig entgegen des Docker gedanken und wird spätestens beim Update des Containers zu Problemen (eine notwendigen Neuinstalltion des Scripts) führen.
Eleganter wäre da die Verwendung eines separaten Containers. Da ich das Projekt leider nicht kenne, kann ich aber nicht beurteilen ob es da schon was gibt. Habe mich mal im verlinkten Forum Thread zu Wort gemeldet.

MfG,
André

**Comment by buanet** [comment]
Ja, Adapter war da wohl kein Thema. Siehe Forum.
Hätte nicht gedacht dass ich da mit Heugabeln und Fackeln vertrieben werde weil ich das Thema anfrage. :)
Verständlicher Weise habe ich gerade nicht mehr so richtig Bock das Script in einen eigenen Docker Container zu portieren... 
Für dich wäre es also das Beste wenn du einen separaten Container erstellst und das Script dort installierst. Im Forum Thread war auch einer der ein paar Infos dazu gepostet hat. 
Sorry.

Von einer Installation des Scripts im ioBroker Container würde ich auf jeden Fall abraten. Auch wenn das technisch natürlich funktioniert.

MfG,
André

**Comment by bertl83** [comment]
Versteh ich scho, finds auch für n Unding was die da abziehen bloß weil jemand ggf hilfe anbieten will...

Na ja ich werd mich wohl mal in das docker thema einlesen müssen um des iwie hinzubekommen.
So wie ich mir des in meinen halbwissen vorgestellt hab hauts auch ned hin.

Ja ich hoffe das mir der andere User evtl seinen docker exportiert.

Die scripte darin lesen und verstehen is kein Thema.
Momentan scheiter ich daran den leeren docker zu erstellen in dem ich dann die paar code Zeilen einfügen kann.

Na ja, aber danke auf jeden Fall für deinen io docker!

⁣Gesendet von meinem Huawei ​

**Comment by bertl83** [comment]
Ahhh
Hier glaub ich is des ganz gut beschrieben
https://pages.cms.hu-berlin.de/cms-webtech/gitlab-documentation/docs/image-erzeugen/

Aber hast du n tip für mich wie ich es mit dem System bzw systemctl schaffe die .sh als autostart Dienst hinzubekommen.
Oder sollte das besser über den cron gehen?

⁣Gesendet von meinem Huawei ​

**Comment by mcdhrts** [comment]
An sich sage ich natürlich auch das der Docker Gedanke daraufhin geht das die Dienste als einzelne Container laufen.
Aber worauf ich noch hinweisen wollte ist das eigentlich das doch mit den Startup Scripts erledigt werden könnte, das würde dann auch eine neu Erstellung vom Container immer überleben:

https://github.com/buanet/docker-iobroker#user-defined-startup-scripts

Ich hab so eine Zeit ein Python Umgebung im Container mit aufgebaut um ein paar Python Skripte auszuführen die ich direkt in Verbindung mit ioBroker genutzt habe.

Sollte ich das Thema falsch verstanden habe dann sorry :-)

**Comment by buanet** [comment]
@bertl83 Das ist schwierig das jetzt in ein paar Zeilen zu erläutern. Hast du diese Anmerkung im ioBroker Forum gesehen? 

https://forum.iobroker.net/topic/28384/linux-shell-skript-wlan-wetterstation/2068?_=1611127384608

@mcdhrts Ja, die user scripts waren ja eigentlich genau für sowas gedacht. Allerdings ist hier die Integration des Scripts wohl etwas umfangreicher. Bin mir nicht sicher ob man das mit dem start script in der Form mit vertretbarem Aufwand hin bekommt. 
Besser wäre es einen eigenen Docker Container als "Wetterstation Broker" einzusetzen....

MfG,
André

**Comment by bertl83** [comment]
Habs nun hinbekommen nen eigenen Docker zu erstellen.

Danke euch allen!

 

Von: André Germann <notifications@github.com> 
Gesendet: Mittwoch, 20. Januar 2021 08:29
An: buanet/docker-iobroker <docker-iobroker@noreply.github.com>
Cc: bertl83 <albertmiethaner@gmx.de>; Mention <mention@noreply.github.com>
Betreff: Re: [buanet/docker-iobroker] WLan Wetterstation (#159)

 

@bertl83 <https://github.com/bertl83>  Das ist schwierig das jetzt in ein paar Zeilen zu erläutern. Hast du diese Anmerkung im ioBroker Forum gesehen?

https://forum.iobroker.net/topic/28384/linux-shell-skript-wlan-wetterstation/2068?_=1611127384608

@mcdhrts <https://github.com/mcdhrts>  Ja, die user scripts waren ja eigentlich genau für sowas gedacht. Allerdings ist hier die Integration des Scripts wohl etwas umfangreicher. Bin mir nicht sicher ob man das mit dem start script in der Form mit vertretbarem Aufwand hin bekommt.
Besser wäre es einen eigenen Docker Container als "Wetterstation Broker" einzusetzen....

MfG,
André

**Comment by buanet** [comment]
Super. 👍 

Ich habe jetzt mittlerweile auch gelernt dass es dazu einen Adaptern Ansatz gibt. Ist wohl aber noch nicht ganz fertig.
Ich persönlich würde immer eine Lösung über einen Adapter bevorzugen. Sofern es denn zuverlässig funktioniert. 

MfG,
André

**Comment by bertl83** [comment]
Mir bleibt iwie jeden Tag der iobroker kontainer stehen. Wie bekomm ich denn raus warum?

**Comment by buanet** [comment]
Ich würde mal im Log schauen. Wenn du da nichts findest stell die Frage am Besten mal im ioBroker Forum Thread zum ioBroker Container. 

MfG,
André
