### ISSUE TITLE
systemctl fehlt im Image

### ISSUE THREAD

**Issue by jogicom** [buanet/docker-iobroker#16]
Ich benutze zum automatischen Backup von ioBroker "backitup".
Da ioBroker in diesem Image nicht als Dienst läuft (warum eigentlich?) kann ioBroker ja nicht durch iobroker stop/start gestoppt/gestartet werden.

Ich wollte nun die Shellscripte von backitup anpassen, dabei ist mir aufgefallen (Achtung bin Linuxmässig ein Anfänger) dass anscheinend _systemctl_, mit dem das script den Status von ioBroker prüft (läuft/läuft nicht) nicht funktioniert, weil anscheinend das Programm im image fehlt.
Also das kommando _systemctl status iobroker_ funktioniert wohl nicht, kann das sein???

**Comment by schmupu** [comment]
Als Tipp, mir fehlen auch ein paar Pakte die wahrscheinlich nur ich benötige. Ich habe mir ein Dockerfile erstellt um das Image von Buanet für meine Ansprüche zu erweitern. Da kannst du z.B. auch den apt-get install systemd für systemctl erweitern.

```
FROM buanet/iobroker:beta 
MAINTAINER yourname <name@foo.local>

RUN apt-get -y update && apt-get install -y vim libavahi-compat-libdnssd-dev ffmpeg net-tools dnsutils procps pkg-config libudev-dev build-essential curl unzip

```

**Comment by buanet** [comment]
Im November 2017 habe ich den Start von ioB als Dienst raus genommen weil einige User Probleme hatten dass ioB nach einem restart des Containers nicht zuverlässig startete. Allerdings da noch ohne systemctl. Seither hat sich viel getan. Zuletzt wurde die komplette Setup-routine von ioB geändert, was ich aktuell zu kompensieren versuche...
Ich nehme das Thema gerne mit auf meine Liste, aber mit low low priority. Meines Erachtens ist die Verwendung von backitup nicht zwingend notwendig, da es auch andere Möglichkeiten des Backups gibt.
Für eine Diskussion und Lösungsvorschläge bin ich wie immer offen. :) 
Danke für euren Support! 

MfG,
André

**Comment by jogicom** [comment]
Danke für die Tips und Erklärungen! Ich bleibe dran!

**Comment by buanet** [comment]
Hallo,
ich habe mich gestern ein wenig über systemd belesen und werde es nicht offiziell in das Image aufnehmen. 

Meine gestrigen Tests mit der aktuellen Beta haben allerdings gezeigt, dass die Befehle "iobroker stop", "iobroker start" und "iobroker status" seit dem neuen Setup  wieder funktionieren sollten und iobroker durchaus als Dienst im Container laufen kann.

Trotzdem werde ich aufgrund der vergangenen Erfahrungen mit den Problemen beim Container neustart an der aktuellen Startoption (Start von iobroker per Script) festhalten.

Zusätzlich habe ich im neuen Beta Image eine Option eingebaut, die es möglich macht im Rahmen des Startscripts zusätzliche Pakete nachzuinstallieren. Dazu beim Start des Containers einfach die Umgebungsvariable "PACKAGES" mit dem Wert "paket1 paket3 paket3" (eine Liste der zu installierenden Pakete, durch Komma getrennt) anlegen. Beim Start werden die Pakete dann nachinstalliert.
Doku dazu ist gerade in Arbeit.

MfG,
André

**Comment by jogicom** [comment]
Hallo, das hört sich ja gut an!
Ursprünglich bin ich auf die Thematik gestoßen, weil BackitUp in einigen Scripts auf systemd angewiesen ist, das Thema habe ich aber, was das Vollbackup betrifft, erledigt. Dann war für mich die Frage aufgetaucht, warum ioBroker nicht richtig beendet wird, wenn der Container gestoppt wird. Allerdings ist das für mich, mangels Linux Kenntnissen, immer noch nicht klar, ob es an Docker generell liegt oder an deinem Image. Deshalb dachte ich, dass wenn ioBroker als Dienst ausgeführt wird, beim stoppen des Containers richtig runter gefahren wird, scheint aber nicht so zu sein. Da muss ich mich mal demnächst, sobald die Zeit dazu da ist, in Linux/Docker mal einarbeiten.....

MfG
Jürgen
