### ISSUE TITLE
IoBroker-Docker auf Synology DS220+

### ISSUE THREAD

**Issue by PortScanner** [buanet/docker-iobroker#160]
Immer wenn ich den ioBroker im Docker der NAS laufen lasse, hängt sich das VPN der Station auf und keine Verbindungen sind von aussen mehr möglich. Versuche mit dem VPN auf das zweite LAN der Station zu gehen, brachten keine Besserung.
Für den Broker habe ich folgende Ports für diverse Adater definiert: 1983, 2000, 2001, 8081, 8082, 8087.
Hat jemand eine Erklärung für die Sache?

**Comment by buanet** [comment]
Lass mich nur kurz in meine Kristallkugel schauen... Nein, bekomme leider keine Verbindung... :)
Sorry, so wird dir keiner helfen können. Es gibt viele Wege den ioBroker auf der DS zu betreiben. Da musst du schon ein bisschen mehr über dein Setup verraten. Außerdem wäre auch das Container Log hilfreich. Und gibt es nicht auf der Disk Station auch ein Logging? Hast du da mal rein geschaut? Eventuell beißt sich da was...

MfG,
André

**Comment by PortScanner** [comment]
Testweise habe ich alle Instanzen abgeschaltet, worauf die VPN-Verbindung nicht mehr gestört wurde.
Dann habe ich die Adapter der Reihe nach wieder zugeschaltet. Siehe da, der Owntracks Adapter ist der Verursacher des Problems. Wie ich das jetzt löse muss ich mal schauen.
