### ISSUE TITLE
Paket samba-common nicht verfügbar (apt)

### ISSUE THREAD

**Issue by fs-plugins** [buanet/docker-iobroker#161]
in der 5.1.0 fehlt das Paket samba-common

es wäre sehr nett, dieses verfügbar zu machen

(habe alle installierbaren Paket aufgelistet, nachdem 
apt-get install samba-common
nur ein
Paket samba-common kann nicht gefunden werden.
geliefert hatte

ob/wie ich (wie im anderen issue angemerkt) in einem bereits angelegten Container etwas per ENV (nach-)installieren kann konnte mir der Herr Internet leider nicht sagen, meine Suche blieb erfolglos

**Comment by buanet** [comment]
Hallo,
 warum machst du einen neuen issue auf? Ist dein Problem mit dem nicht signierten Repo aus #158 beseitigt?

MfG,
André

**Comment by fs-plugins** [comment]
ich bin nur Laie - aber wenn ich die Liste der Pakete abrufen kann und dieses nicht dabei ist - wie ließe es sich denn dann irgendwie installieren? 
die Signatur-Sache aus dem anderen Thread konnte ich wieder beheben (habe ich wohl selbst verursacht durch meine Versuche, welche ja gar nicht funktionieren konnten
`root@Diskstation716:/opt/iobroker# apt-cache search .
nodejs - Node.js event-based server-side javascript engine
acl - access control list - utilities
adduser - add and remove users and groups
apt - commandline package manager
apt-utils - package management related utility programs
avahi-daemon - Avahi mDNS/DNS-SD daemon
base-files - Debian base system miscellaneous files
base-passwd - Debian base system master password and group files
bash - GNU Bourne Again SHell
bind9-host - DNS lookup utility (deprecated)
binutils - GNU assembler, linker and binary utilities
binutils-common - Common files for the GNU assembler, linker and binary utilities
binutils-x86-64-linux-gnu - GNU binary utilities, for x86-64-linux-gnu target
bsdutils - basic utilities from 4.4BSD-Lite
build-essential - Informational list of build-essential packages
bzip2 - high-quality block-sorting file compressor - utilities
ca-certificates - Common CA certificates
coreutils - GNU core utilities
cpp - GNU C preprocessor (cpp)
cpp-8 - GNU C preprocessor
curl - command line tool for transferring data with URL syntax
dash - POSIX-compliant shell
dbus - simple interprocess messaging system (daemon and utilities)
debconf - Debian configuration management system
debian-archive-keyring - GnuPG archive keys of the Debian archive
debianutils - Miscellaneous utilities specific to Debian
diffutils - File comparison utilities
dirmngr - GNU privacy guard - network certificate management service
distro-info-data - information about the distributions' releases (data files)
dpkg - Debian package management system
dpkg-dev - Debian package development tools
e2fsprogs - ext2/ext3/ext4 file system utilities
fakeroot - tool for simulating superuser privileges
fdisk - collection of partitioning utilities
file - Recognize the type of data in a file using "magic" numbers
findutils - utilities for finding files--find, xargs
g++ - GNU C++ compiler
g++-8 - GNU C++ compiler
gcc - GNU C compiler
gcc-8 - GNU C compiler
gcc-8-base - GCC, the GNU Compiler Collection (base package)
geoip-database - IP lookup command line tools that use the GeoIP library (country database)
git - fast, scalable, distributed revision control system
git-man - fast, scalable, distributed revision control system (manual pages)
gnupg - GNU privacy guard - a free PGP replacement
gnupg-l10n - GNU privacy guard - localization files
gnupg-utils - GNU privacy guard - utility programs
gnupg2 - GNU privacy guard - a free PGP replacement (dummy transitional package)
gosu - Simple Go-based setuid+setgid+setgroups+exec
gpg - GNU Privacy Guard -- minimalist public key operations
gpg-agent - GNU privacy guard - cryptographic agent
gpg-wks-client - GNU privacy guard - Web Key Service client
gpg-wks-server - GNU privacy guard - Web Key Service server
gpgconf - GNU privacy guard - core configuration utilities
gpgsm - GNU privacy guard - S/MIME version
gpgv - GNU privacy guard - signature verification tool
grep - GNU grep, egrep and fgrep
gzip - GNU compression utilities
hostname - utility to set/show the host name or domain name
init-system-helpers - helper tools for all init systems
iproute2 - networking and traffic control tools
iputils-ping - Tools to test the reachability of network hosts
jq - lightweight and flexible command-line JSON processor
krb5-locales - internationalization support for MIT Kerberos
less - pager program similar to more
libacl1 - access control list - shared library
libalgorithm-diff-perl - module to find differences between files
libalgorithm-diff-xs-perl - module to find differences between files (XS accelerated)
libalgorithm-merge-perl - Perl module for three-way merge of textual data
libapparmor1 - changehat AppArmor library
libapt-inst2.0 - deb package format runtime library
libapt-pkg5.0 - package management runtime library
libasan5 - AddressSanitizer -- a fast memory error detector
libassuan0 - IPC library for the GnuPG components
libatomic1 - support library providing __atomic built-in functions
libattr1 - extended attribute handling - shared library
libaudit-common - Dynamic library for security auditing - common files
libaudit1 - Dynamic library for security auditing
libavahi-client-dev - Development files for the Avahi client library
libavahi-client3 - Avahi client library
libavahi-common-data - Avahi common data files
libavahi-common-dev - Development files for the Avahi common library
libavahi-common3 - Avahi common library
libavahi-compat-libdnssd-dev - Development headers for the Avahi Apple Bonjour compatibility library
libavahi-compat-libdnssd1 - Avahi Apple Bonjour compatibility library
libavahi-core7 - Avahi's embeddable mDNS/DNS-SD library
libbind9-161 - BIND9 Shared Library used by BIND
libbinutils - GNU binary utilities (private shared library)
libblkid1 - block device ID library
libbsd0 - utility functions from BSD systems - shared library
libbz2-1.0 - high-quality block-sorting file compressor library - runtime
libc-bin - GNU C Library: Binaries
libc-dev-bin - GNU C Library: Development binaries
libc-l10n - GNU C Library: localization files
libc6 - GNU C Library: Shared libraries
libc6-dev - GNU C Library: Development Libraries and Header Files
libcap-ng0 - An alternate POSIX capabilities library
libcap2 - POSIX 1003.1e capabilities (library)
libcap2-bin - POSIX 1003.1e capabilities (utilities)
libcc1-0 - GCC cc1 plugin for GDB
libcom-err2 - common error description library
libcurl3-gnutls - easy-to-use client-side URL transfer library (GnuTLS flavour)
libcurl4 - easy-to-use client-side URL transfer library (OpenSSL flavour)
libdaemon0 - lightweight C library for daemons - runtime library
libdb5.3 - Berkeley v5.3 Database Libraries [runtime]
libdbus-1-3 - simple interprocess messaging system (library)
libdbus-1-dev - simple interprocess messaging system (development headers)
libdebconfclient0 - Debian Configuration Management System (C-implementation library)
libdns1104 - DNS Shared Library used by BIND
libdpkg-perl - Dpkg perl modules
libedit2 - BSD editline and history libraries
libelf1 - library to read and write ELF files
liberror-perl - Perl module for error/exception handling in an OO-ish way
libexpat1 - XML parsing C library - runtime library
libexpat1-dev - XML parsing C library - development kit
libext2fs2 - ext2/ext3/ext4 file system libraries
libfakeroot - tool for simulating superuser privileges - shared libraries
libfdisk1 - fdisk partitioning library
libffi6 - Foreign Function Interface library runtime
libfile-fcntllock-perl - Perl module for file locking with fcntl(2)
libfstrm0 - Frame Streams (fstrm) library
libgcc-8-dev - GCC support library (development files)
libgcc1 - GCC support library
libgcrypt20 - LGPL Crypto library - runtime library
libgdbm-compat4 - GNU dbm database routines (legacy support runtime version) 
libgdbm6 - GNU dbm database routines (runtime version) 
libgeoip1 - non-DNS IP-to-country resolver library
libglib2.0-0 - GLib library of C routines
libglib2.0-data - Common files for GLib library
libgmp10 - Multiprecision arithmetic library
libgnutls30 - GNU TLS library - main runtime library
libgomp1 - GCC OpenMP (GOMP) support library
libgpg-error0 - GnuPG development runtime library
libgpm2 - General Purpose Mouse - shared library
libgssapi-krb5-2 - MIT Kerberos runtime libraries - krb5 GSS-API Mechanism
libhogweed4 - low level cryptographic library (public-key cryptos)
libicu63 - International Components for Unicode
libidn2-0 - Internationalized domain names (IDNA2008/TR46) library
libisc1100 - ISC Shared Library used by BIND
libisccc161 - Command Channel Library used by BIND
libisccfg163 - Config File Handling Library used by BIND
libisl19 - manipulating sets and relations of integer points bounded by linear constraints
libitm1 - GNU Transactional Memory Library
libjq1 - lightweight and flexible command-line JSON processor - shared library
libjson-c3 - JSON manipulation library - shared library
libk5crypto3 - MIT Kerberos runtime libraries - Crypto Library
libkeyutils1 - Linux Key Management Utilities (library)
libkmod2 - libkmod shared library
libkrb5-3 - MIT Kerberos runtime libraries
libkrb5support0 - MIT Kerberos runtime libraries - Support library
libksba8 - X.509 and CMS support library
libldap-2.4-2 - OpenLDAP libraries
libldap-common - OpenLDAP common files for libraries
liblmdb0 - Lightning Memory-Mapped Database shared library
liblocale-gettext-perl - module using libc functions for internationalization in Perl
liblsan0 - LeakSanitizer -- a memory leak detector (runtime)
liblwres161 - Lightweight Resolver Library used by BIND
liblz4-1 - Fast LZ compression algorithm library - runtime
liblzma5 - XZ-format compression library
libmagic-mgc - File type determination library using "magic" numbers (compiled magic file)
libmagic1 - Recognize the type of data in a file using "magic" numbers - library
libmnl0 - minimalistic Netlink communication library
libmount1 - device mounting library
libmpc3 - multiple precision complex floating-point library
libmpdec2 - library for decimal floating point arithmetic (runtime library)
libmpfr6 - multiple precision floating-point computation
libmpx2 - Intel memory protection extensions (runtime)
libncurses6 - shared libraries for terminal handling
libncursesw6 - shared libraries for terminal handling (wide character support)
libnettle6 - low level cryptographic library (symmetric and one-way cryptos)
libnghttp2-14 - library implementing HTTP/2 protocol (shared library)
libnpth0 - replacement for GNU Pth using system threads
libnss-mdns - NSS module for Multicast DNS name resolution
libonig5 - regular expressions library
libp11-kit0 - library for loading and coordinating access to PKCS#11 modules - runtime
libpam-modules - Pluggable Authentication Modules for PAM
libpam-modules-bin - Pluggable Authentication Modules for PAM - helper binaries
libpam-runtime - Runtime support for the PAM library
libpam0g - Pluggable Authentication Modules library
libpam0g-dev - Development files for PAM
libpcre2-8-0 - New Perl Compatible Regular Expression Library- 8 bit runtime files
libpcre3 - Old Perl 5 Compatible Regular Expression Library - runtime files
libperl5.28 - shared Perl library
libprocps7 - library for accessing process information from /proc
libprotobuf-c1 - Protocol Buffers C shared library (protobuf-c)
libpsl5 - Library for Public Suffix List (shared libraries)
libpython-dev - header files and a static library for Python2
libpython-stdlib - interactive high-level object-oriented language (Python2)
libpython2-dev - header files and a static library for Python2
libpython2-stdlib - interactive high-level object-oriented language (Python2)
libpython2.7 - Shared Python runtime library (version 2.7)
libpython2.7-dev - Header files and a static library for Python (v2.7)
libpython2.7-minimal - Minimal subset of the Python language (version 2.7)
libpython2.7-stdlib - Interactive high-level object-oriented language (standard library, version 2.7)
libpython3-stdlib - interactive high-level object-oriented language (default python3 version)
libpython3.7-minimal - Minimal subset of the Python language (version 3.7)
libpython3.7-stdlib - Interactive high-level object-oriented language (standard library, version 3.7)
libquadmath0 - GCC Quad-Precision Math Library
libreadline7 - GNU readline and history libraries, run-time libraries
librtmp1 - toolkit for RTMP streams (shared library)
libsasl2-2 - Cyrus SASL - authentication abstraction library
libsasl2-modules - Cyrus SASL - pluggable authentication modules
libsasl2-modules-db - Cyrus SASL - pluggable authentication modules (DB)
libseccomp2 - high level interface to Linux seccomp filter
libselinux1 - SELinux runtime shared libraries
libsemanage-common - Common files for SELinux policy management libraries
libsemanage1 - SELinux policy management library
libsepol1 - SELinux library for manipulating binary security policies
libsmartcols1 - smart column output alignment library
libsqlite3-0 - SQLite 3 shared library
libss2 - command-line interface parsing library
libssh2-1 - SSH2 client-side library
libssl1.1 - Secure Sockets Layer toolkit - shared libraries
libstdc++-8-dev - GNU Standard C++ Library v3 (development files)
libstdc++6 - GNU Standard C++ Library v3
libsystemd0 - systemd utility library
libtasn1-6 - Manage ASN.1 structures (runtime)
libtinfo6 - shared low-level terminfo library for terminal handling
libtsan0 - ThreadSanitizer -- a Valgrind-based detector of data races (runtime)
libubsan1 - UBSan -- undefined behaviour sanitizer (runtime)
libudev-dev - libudev development files
libudev1 - libudev shared library
libunistring2 - Unicode string library for C
libuuid1 - Universally Unique ID library
libx11-6 - X11 client-side library
libx11-data - X11 client-side library
libxau6 - X11 authorisation library
libxcb1 - X C Binding
libxdmcp6 - X11 Display Manager Control Protocol library
libxext6 - X11 miscellaneous extension library
libxml2 - GNOME XML library
libxmuu1 - X11 miscellaneous micro-utility library
libxtables12 - netfilter xtables library
libzstd1 - fast lossless compression algorithm
linux-libc-dev - Linux support headers for userspace development
locales - GNU C Library: National Language (locale) data [support]
login - system login tools
lsb-base - Linux Standard Base init script functionality
lsb-release - Linux Standard Base version reporting utility
make - utility for directing compilation
manpages - Manual pages about using a GNU/Linux system
manpages-dev - Manual pages about using GNU/Linux for development
mawk - a pattern scanning and text processing language
mime-support - MIME files 'mime.types' & 'mailcap', and support programs
mount - tools for mounting and manipulating filesystems
ncurses-base - basic terminal type definitions
ncurses-bin - terminal-related programs and man pages
net-tools - NET-3 networking toolkit
netbase - Basic TCP/IP networking system
openssh-client - secure shell (SSH) client, for secure access to remote machines
openssl - Secure Sockets Layer toolkit - cryptographic utility
passwd - change and administer password and group data
patch - Apply a diff file to an original
perl - Larry Wall's Practical Extraction and Report Language
perl-base - minimal Perl system
perl-modules-5.28 - Core Perl modules
pinentry-curses - curses-based PIN or pass-phrase entry dialog for GnuPG
pkg-config - manage compile and link flags for libraries
procps - /proc file system utilities
psmisc - utilities that use the proc file system
publicsuffix - accurate, machine-readable list of domain name suffixes
python - interactive high-level object-oriented language (Python2 version)
python-dev - header files and a static library for Python2
python-minimal - minimal subset of the Python2 language
python2 - interactive high-level object-oriented language (Python2 version)
python2-dev - header files and a static library for Python2
python2-minimal - minimal subset of the Python2 language
python2.7 - Interactive high-level object-oriented language (version 2.7)
python2.7-dev - Header files and a static library for Python (v2.7)
python2.7-minimal - Minimal subset of the Python language (version 2.7)
python3 - interactive high-level object-oriented language (default python3 version)
python3-minimal - minimal subset of the Python language (default python3 version)
python3.7 - Interactive high-level object-oriented language (version 3.7)
python3.7-minimal - Minimal subset of the Python language (version 3.7)
readline-common - GNU readline and history libraries, common files
sed - GNU stream editor for filtering/transforming text
shared-mime-info - FreeDesktop.org shared MIME database and spec
sudo - Provide limited super user privileges to specific users
sysvinit-utils - System-V-like utilities
tar - GNU version of the tar archiving utility
tzdata - time zone and daylight-saving time data
udev - /dev/ and hotplug management daemon
unzip - De-archiver for .zip files
util-linux - miscellaneous system utilities
wget - retrieves files from the web
xauth - X authentication utility
xdg-user-dirs - tool to manage well known user directories
xz-utils - XZ-format compression utilities
zlib1g - compression library - runtime`

**Comment by buanet** [comment]
Hallo,

was willst du mir damit sagen? 

> (ich wundere mich aber, das nach meiner Anfrage eben dies nicht bemerkt wurde)

Ich hoffe nicht das, wonach es sich anhört...
Falls doch, nur zur Info: Ich mache das hier in meiner Freizeit!

Habe mir das natürlich schon angeschaut bevor ich drauf [geantwortet](https://github.com/buanet/docker-iobroker/issues/158#issuecomment-762469524)  habe und in einem frischen Container geprüft. Da im frischen Container ALLES wunderbar funktioniert hat (kein generelles Problem mit dem Container), und dein Problem kein ioBroker Problem, sondern ein Linux Problem ist, ist die PRIO leider abgerutscht auf: "Schaue ich mir an wenn ich Zeit habe".

Aber zurück zum Problem, im frischen Container ist alles i.O.
```
root@iobrokertest:/opt/iobroker# apt-get update
Holen:1 http://security.debian.org/debian-security buster/updates InRelease [65,4 kB]
Holen:2 http://deb.debian.org/debian buster InRelease [121 kB]                                                                                   
Holen:3 https://deb.nodesource.com/node_12.x buster InRelease [4.584 B]                                                                          
Holen:4 http://deb.debian.org/debian buster-updates InRelease [51,9 kB]                                           
Holen:5 http://security.debian.org/debian-security buster/updates/main amd64 Packages [268 kB]
Holen:6 http://deb.debian.org/debian buster/main amd64 Packages [7.907 kB]
Holen:7 https://deb.nodesource.com/node_12.x buster/main amd64 Packages [767 B]
Holen:8 http://deb.debian.org/debian buster-updates/main amd64 Packages [7.860 B]
Es wurden 8.427 kB in 4 s geholt (2.342 kB/s).        
Paketlisten werden gelesen... Fertig
root@iobrokertest:/opt/iobroker# apt-get install samba-common
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Die folgenden zusätzlichen Pakete werden installiert:
  libcups2 libgpgme11 libjansson4 libldb1 libpopt0 libtalloc2 libtdb1 libtevent0 libwbclient0 python-crypto python-gpg python-ldb python-samba python-talloc python-tdb
  samba-common-bin samba-dsdb-modules samba-libs sensible-utils ucf
Vorgeschlagene Pakete:
  cups-common python-crypto-doc heimdal-clients
Die folgenden NEUEN Pakete werden installiert:
  libcups2 libgpgme11 libjansson4 libldb1 libpopt0 libtalloc2 libtdb1 libtevent0 libwbclient0 python-crypto python-gpg python-ldb python-samba python-talloc python-tdb
  samba-common samba-common-bin samba-dsdb-modules samba-libs sensible-utils ucf
0 aktualisiert, 21 neu installiert, 0 zu entfernen und 2 nicht aktualisiert.
Es müssen 10,6 MB an Archiven heruntergeladen werden.
Nach dieser Operation werden 49,8 MB Plattenplatz zusätzlich benutzt.
Möchten Sie fortfahren? [J/n] 
```
Ich würde sagen du hast ein Problem mit deinen repositories im Container. Weiß der Geier was da schief gelaufen ist.
Meine Empfehlung: Lege den Container einmal neu an.

Wie du Pakete per ENV installierst, musst du nicht "Herrn Internet" fragen, sondern mal einen Blick in die Doku werfen: 
https://github.com/buanet/docker-iobroker#environment-variables

Tipp: Die ENV heißt "PACKAGES".

MfG,
André

**Comment by fs-plugins** [comment]
>>Meine Empfehlung: Lege den Container einmal neu an.

bin deiner Empfehlung gefolgt, habe den container ein weiteres mal absolut und komplett neu angelegt inkl. neuem leeren Pfad
das Ergebnis ist leider unverändert
da der Fehler ja offenbar bei mir liegt und ich absolut keine Ahnung habe, warum dies so auftritt (außer Volume und Network (Host) habe ich nichts gesetzt) muss ich mich wohl nach einer Alternative für die iobroker-Installation umsehen
 
------------------------------------------------------------

---------------     2021-01-21 07:37:29      ---------------

------------------------------------------------------------

 

------------------------------------------------------------

-----       Welcome to your ioBroker-container!        -----

-----          Startupscript is now running.           -----

-----                Please be patient!                -----

------------------------------------------------------------

 

------------------------------------------------------------

-----              Debugging information               -----

-----                                                  -----

-----                      System                      -----

-----               arch:      x86_64                  -----

-----                                                  -----

-----                     Versions                     -----

-----               image:     v5.1.0                  -----

-----               node:      v12.20.1                -----

-----               npm:       6.14.10                 -----

-----                                                  -----

-----                       ENV                        -----

-----               SETGID:    1000                    -----

-----               SETUID:    1000                    -----

------------------------------------------------------------

 

------------------------------------------------------------

-----         Step 1 of 5: Preparing container         -----

------------------------------------------------------------

 

Registering maintenance script as command.

Done.

 

------------------------------------------------------------

-----   Step 2 of 5: Detecting ioBroker installation   -----

------------------------------------------------------------

 

There is no data detected in /opt/iobroker. Restoring initial ioBroker installation...

Done.

 

------------------------------------------------------------

-----   Step 3 of 5: Checking ioBroker installation    -----

------------------------------------------------------------

 

(Re)Setting folder permissions (This might take a while! Please be patient!)...

Done.

 

Fixing "sudo-bug" by replacing sudo in iobroker with gosu...

Done.

 

Looks like this is a new and empty installation of ioBroker.

Hostname needs to be updated to  Diskstation716...

The host for instance "system.adapter.admin.0" was changed from "3ef9c5ed2d57" to "Diskstation716".

The host for instance "system.adapter.discovery.0" was changed from "3ef9c5ed2d57" to "Diskstation716".

The host for instance "system.adapter.info.0" was changed from "3ef9c5ed2d57" to "Diskstation716".

Done.

 

------------------------------------------------------------

-----      Step 4 of 5: Applying special settings      -----

------------------------------------------------------------

 

Some adapters have special requirements/ settings which can be activated by the use of environment variables.

For more information take a look at readme.md on Github!

 

------------------------------------------------------------

-----          Step 5 of 5: ioBroker startup           -----

------------------------------------------------------------

 

Starting ioBroker...

 

host.Diskstation716 check instance "system.adapter.admin.0" for host "Diskstation716"

host.Diskstation716 check instance "system.adapter.discovery.0" for host "Diskstation716"

host.Diskstation716 check instance "system.adapter.info.0" for host "Diskstation716"

Send diag info: {"uuid":"7abd3182-d399-f7bd-da19-9550d8babede","language":"","country":"","hosts":[{"version":"3.1.6","platform":"Javascript/Node.js","type":"linux"}],"node":"v12.20.1","arch":"x64","adapters":{"admin":{"version":"4.1.11","platform":"Javascript/Node.js"},"discovery":{"version":"2.4.1","platform":"Javascript/Node.js"},"info":{"version":"1.7.10","platform":"Javascript/Node.js"}},"statesType":"file","objectsType":"file","model":"Intel(R) Celeron(R) CPU  N3160  @ 1.60GHz","cpus":4,"mem":8287653888,"ostype":"Linux","city":""}

================================== > LOG REDIRECT system.adapter.admin.0 => true [system.adapter.admin.0.logging]

hash changed or no sources cached => force download of new sources

root@Diskstation716:/opt/iobroker# apt-get update
Holen:4 https://deb.nodesource.com/node_12.x buster InRelease [4.584 B]                             
Holen:1 http://security.debian.org/debian-security buster/updates InRelease
Holen:2 http://deb.debian.org/debian buster InRelease
Holen:3 http://deb.debian.org/debian buster-updates InRelease
Fehl:1 http://security.debian.org/debian-security buster/updates InRelease
  Durch Clearsign signierte Datei ist nicht gültig, »NOSPLIT« erhalten (erfordert das Netzwerk eine Authentifizierung?)
Fehl:2 http://deb.debian.org/debian buster InRelease
  Durch Clearsign signierte Datei ist nicht gültig, »NOSPLIT« erhalten (erfordert das Netzwerk eine Authentifizierung?)
Fehl:3 http://deb.debian.org/debian buster-updates InRelease
  Durch Clearsign signierte Datei ist nicht gültig, »NOSPLIT« erhalten (erfordert das Netzwerk eine Authentifizierung?)
Holen:5 https://deb.nodesource.com/node_12.x buster/main amd64 Packages [767 B]
Paketlisten werden gelesen... Fertig
N: Weitere Details zur Erzeugung von Paketdepots sowie zu deren Benutzerkonfiguration finden Sie in der Handbuchseite apt-secure(8).
N: Eine Aktualisierung von solch einem Depot kann nicht auf eine sichere Art durchgeführt werden, daher ist es standardmäßig deaktiviert.
E: Das Depot »http://security.debian.org/debian-security buster/updates InRelease« ist nicht signiert.
E: Fehlschlag beim Holen von http://security.debian.org/debian-security/dists/buster/updates/InRelease Durch Clearsign signierte Datei ist nicht gültig, »NOSPLIT« erhalten (erfordert das Netzwerk eine Authentifizierung?)
E: Fehlschlag beim Holen von http://deb.debian.org/debian/dists/buster/InRelease Durch Clearsign signierte Datei ist nicht gültig, »NOSPLIT« erhalten (erfordert das Netzwerk eine Authentifizierung?)
E: Das Depot »http://deb.debian.org/debian buster InRelease« ist nicht signiert.
N: Eine Aktualisierung von solch einem Depot kann nicht auf eine sichere Art durchgeführt werden, daher ist es standardmäßig deaktiviert.
N: Weitere Details zur Erzeugung von Paketdepots sowie zu deren Benutzerkonfiguration finden Sie in der Handbuchseite apt-secure(8).
E: Fehlschlag beim Holen von http://deb.debian.org/debian/dists/buster-updates/InRelease Durch Clearsign signierte Datei ist nicht gültig, »NOSPLIT« erhalten (erfordert das Netzwerk eine Authentifizierung?)
E: Das Depot »http://deb.debian.org/debian buster-updates InRelease« ist nicht signiert.
N: Eine Aktualisierung von solch einem Depot kann nicht auf eine sichere Art durchgeführt werden, daher ist es standardmäßig deaktiviert.
N: Weitere Details zur Erzeugung von Paketdepots sowie zu deren Benutzerkonfiguration finden Sie in der Handbuchseite apt-secure(8).
root@Diskstation716:/opt/iobroker#

**Comment by buanet** [comment]
> bin deiner Empfehlung gefolgt, habe den container ein weiteres mal absolut und komplett neu angelegt inkl. neuem leeren Pfad
> 
> das Ergebnis ist leider unverändert

Hast du auch das Image mal neu geladen? Das Image wird regelmäßig automatisch neu generiert (damit die Pakete immer aktuell sind). Es ist nicht ausgeschlossen, dass auch mal ein faules Image dabei ist....

BTW: Gib mal in der Kommandozeile deines Containers `date` ein und checke deine Uhrzeit und das Datum. Korrekt? 
Nicht dass deine Systemzeit nicht stimmt und daher das Repo als ungültig angesehen wird...

> da der Fehler ja offenbar bei mir liegt und ich absolut keine Ahnung habe, warum dies so auftritt (außer Volume und Network (Host) habe ich nichts gesetzt) muss ich mich wohl nach einer Alternative für die iobroker-Installation umsehen

Wenn das deine bevorzugte Problemlösungsstrategie ist, kann ich da auch nichts machen... Ich persönlich halte das aber für den falschen Weg.

MfG,
André

**Comment by fs-plugins** [comment]
Do 21. Jan 10:36:52 CET 2021
Always pull the image ist enabled

>>Wenn das deine bevorzugte Problemlösungsstrategie ist, kann ich da auch nichts machen
nein ist es nicht (da dann die NAS-recurce nicht ausgenutzt wird und ein weiterer Stromverbraucher online), aber ich kann mir leider in dieser Beziehung nicht selbst helfen

**Comment by fs-plugins** [comment]
bin mal auf die eigentlich naheliegende Idee gekommen, ins log vom portainer zu sehen:
2021/01/21 10:10:15 http error: Invalid JWT token (err=Invalid JWT token) (code=401)

**Comment by buanet** [comment]
Kann es vielleicht sein, dass du von dem Container/ von der DS nicht ins Internet kommst?

Versuche mal aus dem container einen ping www.google.de

MfG,
André

**Comment by fs-plugins** [comment]
PING www.google.de(fra15s16-in-x03.1e100.net (2a00:1450:4001:81b::2003)) 56 data bytes
From p200300efdfff19aa464e6dfffe696320.dip0.t-ipconnect.de (2003:ef:dfff:19aa:464e:6dff:fe69:6320): icmp_seq=1 Destination unreachable: Administratively prohibited
From p200300efdfff19aa464e6dfffe696320.dip0.t-ipconnect.de (2003:ef:dfff:19aa:464e:6dff:fe69:6320): icmp_seq=2 Destination unreachable: Administratively prohibited

**Comment by buanet** [comment]
Ich würde sagen du hast ein Problem im Netzwerk oder beim Zugriff auf das Internet.

Das hier habe ich auf die schnelle gefunden. Bin aber nur mobil. 

https://debianforum.de/forum/viewtopic.php?t=166587

Sonst müssen wir heute Abend noch mal schauen. 

MfG, 
André

**Comment by fs-plugins** [comment]
kein IPv6 am laufen, Anbieter ist Telekom mit völlig normalem Anschluss

**Comment by buanet** [comment]
Sehr seltsam. Fakt ist, dass bei dir auch google IPv6 aufgelöst wird und der Ping dann abgewiesen wird. Bei mir sieht das nämlich so aus:
```
root@vm-nas:/opt/iobroker# ping www.google.de
PING www.google.de (216.58.213.227) 56(84) bytes of data.
64 bytes from ham04s01-in-f3.1e100.net (216.58.213.227): icmp_seq=1 ttl=116 time=21.6 ms
64 bytes from ham04s01-in-f3.1e100.net (216.58.213.227): icmp_seq=2 ttl=116 time=21.6 ms
64 bytes from ham04s01-in-f3.1e100.net (216.58.213.227): icmp_seq=3 ttl=116 time=20.2 ms
```
Portainer ist korrekt, hab ich exakt genauso, spielt aber für die kommunikation keine Rolle. Portainer ist nur eine Verwaltungsoberfläche...
Muss ich heute Abend nochmal in Ruhe Google befragen.

MfG,
André

**Comment by fs-plugins** [comment]
das IPv6 kam von der Syno, habe ich abgestellt und sieht nun aus wie bei dir - ändert leider nichts am Problem

root@Diskstation716:/opt/iobroker# apt-get install samba-common
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
E: Paket samba-common kann nicht gefunden werden.

**Comment by buanet** [comment]
läuft das apt-get update denn fehlerfrei durch?

**Comment by fs-plugins** [comment]
root@iobroker:/opt/iobroker# apt-get update
Holen:1 http://security.debian.org/debian-security buster/updates InRelease [65,4 kB]
Holen:2 http://deb.debian.org/debian buster InRelease [121 kB]                                 
Holen:3 http://deb.debian.org/debian buster-updates InRelease [51,9 kB]                                  
Holen:4 https://deb.nodesource.com/node_12.x buster InRelease [4.584 B]               
Holen:5 http://security.debian.org/debian-security buster/updates/main amd64 Packages [268 kB]
Holen:6 http://deb.debian.org/debian buster/main amd64 Packages [7.907 kB]
Holen:7 https://deb.nodesource.com/node_12.x buster/main amd64 Packages [767 B]
Holen:8 http://deb.debian.org/debian buster-updates/main amd64 Packages [7.860 B]
Es wurden 8.427 kB in 5 s geholt (1.693 kB/s).             
Paketlisten werden gelesen... Fertig
root@iobroker:/opt/iobroker#

**Comment by fs-plugins** [comment]
HEUREKA!

nach einem heutigen apt-get update && apt-get -y upgrade (mit 0 Paketen usw) ließ sich samba problemlos installieren
egal wer es war - vielen Dank dafür!

**Comment by buanet** [comment]
Sorry, bei mir war gestern die Luft raus.
Schön dass es jetzt zumindest mit der Installation geklappt hat. 

Was die ENV "PACKAGES" angeht, da bräuchte ich zur Analyse das Logfile vom Container Start (Wenn du es hier postst, bitte nach dem einfügen markieren und auf den Button "<>" vom Editor klicken. Dann kommt es einigemaßen übersichtlich als Code. :)

Grundsätzlich gab es mal einem Bug beim Editieren der Container über Portainer. Dabei wurden neu hinzugefügte ENV nicht übernommen. Hier half es nur den Container zu entfernen und neu anzulegen. Vielleicht ist das ja auch dein Problem. Im Log sollte man beim Start sehen welche ENV gesetzt sind. Das kannst du auch selbst aus dem Log heraus lesen. 

Beispiel:
```
--------------- 2021-01-21 07:37:29 ---------------

----- Welcome to your ioBroker-container! -----

----- Startupscript is now running. -----

----- Please be patient! -----

----- Debugging information -----

----- System -----

----- arch: x86_64 -----

----- Versions -----

----- image: v5.1.0 -----

----- node: v12.20.1 -----

----- npm: 6.14.10 -----

----- ENV -----

----- SETGID: 1000 -----

----- SETUID: 1000 -----

----- Step 1 of 5: Preparing container -----
```

MfG,
André

**Comment by fs-plugins** [comment]
den Bug scheint es immer noch zu geben (oder wieder)
container neu erstellt - voila
(hoffentlich funktioniert es beim recreate dann auch, war eines meiner Hauptprobleme das nach diesem das Paket immer neu installiert werden musste)

wäre natürlich interessant, die Ursache des install-Problems zu kennen - da wüsset man wohin sich bei erneutem Auftreten wenden oder was/wie tun

möchte mich herzlichst für die Unterstützung bedanken!

**Comment by buanet** [comment]
Gerne. Freut mich dass es jetzt klappt. 

Was da falsch war ist schwer zu sagen . Vielleicht auch eine Verkettung von unglücklichen Umständen. Am besten weiter beobachten.

Wenn sonst alles gut ist, schließe doch bitte den Issue. 
Danke.

MfG,
André
