### ISSUE TITLE
Mounted /opt/iobroker stays empty after installation

### ISSUE THREAD

**Issue by Shogun1978** [buanet/docker-iobroker#19]
I experimented with the image without binding to a local folder. Everything works fine, inside the container the /opt/iobroker is populated with data. Now I would like to bind a local folder (/docker_data/iobroker_unifi) to /opt/iobroker, but the folder keeps empty and the web interface is not available. I use docker on ubuntu 18.04 (Intel platform).

**Comment by buanet** [comment]
Sure. You still have to copy the files manually!

If you are using BETA you will be able to mount an empty folder and startup script will do the rest (restore an initial ioBroker-Installation to the empty mounted folder).
But it's not yet included in LATEST (stable). Need to do some more tests and scenarios to get it work in every situation. 
As I see not bug here, i will close this issue. 

regards,
André

**Comment by Shogun1978** [comment]
Sorry, as I read the documentation, it would already be integrated. I will try the beta. Thanks for clarifying
