### ISSUE TITLE
Apple Homekit adapter yahka doesn't install (image: buanet/iobroker:beta)

### ISSUE THREAD

**Issue by Jack187** [buanet/docker-iobroker#20]
Hello dear developer,

I use a ubuntu 14.04.6 server installation and was able to run your beta image (buanet/iobroker:beta).
I was able to install and setup the homematic adapters and can controll my heaters. Also some other adpaters installed flawlessly.
Now I want to setup the yahka homekit adapter. But always getting the following errors.

> `$ ./iobroker add yahka  --host iobroker
NPM version: 6.4.1
npm install iobroker.yahka --production --save --prefix "/opt/iobroker" (System call)
gyp
 WARN 
EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/8.15.1"
gyp
 WARN
 
>EACCES attempting to reinstall using temporary dev dir "/tmp/.node-gyp"
gyp
 ERR! 
configure error gyp ERR! stack Error: EACCES: permission denied, mkdir '/opt/iobroker/node_modules/curve25519-n/build'
gyp ERR! System Linux 4.4.0-143-generic

>gyp ERR!
 command
 "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"gyp ERR! 
cwd /opt/iobroker/node_modules/curve25519-ngyp
 ERR!
 node -v
 v8.15.1gyp ERR!
 node-gyp -v
 v3.8.0gyp
 ERR!
 not ok 
npm
 ERR! code
 ELIFECYCLEnpm ERR! errno 1
npm ERR! curve25519-n@1.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the curve25519-n@1.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

>npm ERR! A complete log of this run can be found in:npm ERR!     /root/.npm/_logs/2019-03-31T10_02_26_084Z-debug.log

>host.iobroker install adapter yahka
NPM version: 6.4.1
npm install iobroker.yahka --production --save --prefix "/opt/iobroker" (System call)
gyp
 WARN 
EACCES
 user "root" does not have permission to access the dev dir "/root/.node-gyp/8.15.1"
gyp 
WARN
 EACCES
 attempting to reinstall using temporary dev dir "/tmp/.node-gyp"
gyp
 
>ERR!
 
>configure error
 
>gyp
 
>ERR!
 
>stack
 Error: EACCES: permission denied, mkdir '/opt/iobroker/node_modules/curve25519-n/build'
gyp
 
>ERR!
 
>System Linux 4.4.0-143-generic
gyp
 ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"gyp ERR! cwd /opt/iobroker/node_modules/curve25519-n
gyp ERR! node -v
 v8.15.1gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

>npm ERR! code ELIFECYCLEnpm ERR! errno 1

>npm ERR! curve25519-n@1.4.0 install: `node-gyp rebuild`npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the curve25519-n@1.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

>npm ERR! A complete log of this run can be found in:npm ERR!     /root/.npm/_logs/2019-03-31T10_02_32_410Z-debug.log

>host.iobroker install adapter yahka
NPM version: 6.4.1
npm install iobroker.yahka --production --save --prefix "/opt/iobroker" (System call)
gyp
 WARN
 
>EACCES
 user "root" does not have permission to access the dev dir "/root/.node-gyp/8.15.1"
gyp
 
>WARN
 EACCES attempting to reinstall using temporary dev dir "/tmp/.node-gyp"
gyp
 
>ERR!
 
>configure error
 gyp 
ERR! stack Error: EACCES: permission denied, mkdir '/opt/iobroker/node_modules/curve25519-n/build'gyp
 ERR! System Linux 4.4.0-143-genericgyp ERR! 
command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"gyp ERR! cwd /opt/iobroker/node_modules/curve25519-n
gyp ERR! node -v v8.15.1
gyp
 ERR! node-gyp -v v3.8.0gyp ERR! not ok 

>npm
 ERR! code ELIFECYCLEnpm ERR! errno 1
npm ERR! curve25519-n@1.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the curve25519-n@1.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

>npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-03-31T10_02_38_784Z-debug.log

>host.iobroker install adapter yahka
ERROR: host.iobroker Cannot install yahka
ERROR: process exited with code 13`

Also tried to installt the newest version 0.92 via Github link. But that didn't work either.
I also destroyed the container and used a fresh mount for /opt/iobroker mapping to start a fresh system. But the log is the same. 
It would be great if you could help me.

**Comment by buanet** [comment]
Hi, not sure whats wrong. Try `sudo iobroker add yahka` on the containers commandline. Works in my testing environment. 

Regards, 
André

**Comment by Jack187** [comment]
Thank you for the reply. I tried it with "iobroker install yahka"
I'm able to install, but the plugin doesn't work. Was it working in your test environment?

`
2019-04-06 16:54:29.114 - error: Caught by controller[0]: /opt/iobroker/node_modules/bindings/bindings.js:96
--
2019-04-06 16:54:29.114 - error: Caught by controller[0]: throw err
2019-04-06 16:54:29.114 - error: Caught by controller[0]: ^
2019-04-06 16:54:29.114 - error: Caught by controller[0]: Error: Could not locate the bindings file. Tried:
2019-04-06 16:54:29.114 - error: Caught by controller[0]: → /opt/iobroker/node_modules/ed25519-hap/build/ed25519.node
2019-04-06 16:54:29.114 - error: Caught by controller[0]: → /opt/iobroker/node_modules/ed25519-hap/build/Debug/ed25519.node
2019-04-06 16:54:29.114 - error: Caught by controller[0]: → /opt/iobroker/node_modules/ed25519-hap/build/Release/ed25519.node
2019-04-06 16:54:29.114 - error: Caught by controller[0]: → /opt/iobroker/node_modules/ed25519-hap/out/Debug/ed25519.node
2019-04-06 16:54:29.114 - error: Caught by controller[0]: → /opt/iobroker/node_modules/ed25519-hap/Debug/ed25519.node
2019-04-06 16:54:29.114 - error: Caught by controller[0]: → /opt/iobroker/node_modules/ed25519-hap/out/Release/ed25519.node
2019-04-06 16:54:29.114 - error: Caught by controller[0]: → /opt/iobroker/node_modules/ed25519-hap/Release/ed25519.node
2019-04-06 16:54:29.114 - error: Caught by controller[0]: → /opt/iobroker/node_modules/ed25519-hap/build/default/ed25519.node
2019-04-06 16:54:29.114 - error: Caught by controller[0]: → /opt/iobroker/node_modules/ed25519-hap/compiled/8.15.1/linux/x64/ed25519.node
2019-04-06 16:54:29.114 - error: Caught by controller[0]: at bindings (/opt/iobroker/node_modules/bindings/bindings.js:93:9)
2019-04-06 16:54:29.114 - error: Caught by controller[0]: at Object. (/opt/iobroker/node_modules/ed25519-hap/index.js:1:99)
2019-04-06 16:54:29.114 - error: Caught by controller[0]: at Module._compile (module.js:653:30)
2019-04-06 16:54:29.114 - error: Caught by controller[0]: at Object.Module._extensions..js (module.js:664:10)
2019-04-06 16:54:29.114 - error: Caught by controller[0]: at Module.load (module.js:566:32)
2019-04-06 16:54:29.115 - error: Caught by controller[0]: at tryModuleLoad (module.js:506:12)
2019-04-06 16:54:29.115 - error: Caught by controller[0]: at Function.Module._load (module.js:498:3)
2019-04-06 16:54:29.115 - error: Caught by controller[0]: at Module.require (module.js:597:17)
2019-04-06 16:54:29.115 - error: Caught by controller[0]: at require (internal/module.js:11:18)
2019-04-06 16:54:29.115 - error: Caught by controller[0]: at Object. (/opt/iobroker/node_modules/hap-nodejs/lib/HAPServer.js:8:15)
2019-04-06 16:54:29.115 - error: host.iobroker instance system.adapter.yahka.0 terminated with code 1 ()`

Regards,
Jack

**Comment by Apollon77** [comment]
This error means that the installation was not successfull for ed25519 module. The installation log would be helpful

**Comment by Jack187** [comment]
Hi Apollon77,

please excuse the late reply.

Here ist the output of the iobroker install yahka command

`/opt/iobroker$ iobroker install yahka

NPM version: 6.4.1
npm install iobroker.yahka --production --save --prefix "/opt/iobroker" (System call)
../authenticate_pam.cc: In function ‘void after_doing_auth(uv_work_t*, int)’:
../authenticate_pam.cc:107:87: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
   Nan::MakeCallback(Nan::GetCurrentContext()->Global(), Nan::New(m->callback), 1, args);
                                                                                       ^
In file included from ../authenticate_pam.cc:23:0:
../../nan/nan.h:959:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
host.17794c7348ba object system.adapter.yahka created
host.17794c7348ba object yahka.meta._accessoryCategories created
got /opt/iobroker/node_modules/iobroker.yahka/admin
upload [19] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/yahka.png yahka.png image/png
upload [18] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/yahka.admin.js.map yahka.admin.js.map application/json
upload [17] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/yahka.admin.js yahka.admin.js application/javascript
upload [16] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/words.js words.js application/javascript
upload [15] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/index_m.html index_m.html text/html
upload [14] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/index.html index.html text/html
upload [13] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/home_icon_large.png home_icon_large.png image/png
upload [12] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/js/metro.min.js ext/metroui/js/metro.min.js application/javascript
upload [11] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/selection.json ext/metroui/fonts/selection.json application/json
upload [10] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/metro.woff ext/metroui/fonts/metro.woff application/font-woff
upload [9] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/metro.ttf ext/metroui/fonts/metro.ttf application/x-font-ttf
upload [8] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/metro.svg ext/metroui/fonts/metro.svg image/svg+xml
upload [7] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/fonts/metro.eot ext/metroui/fonts/metro.eot application/vnd.ms-fontobject
upload [6] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro.min.css ext/metroui/css/metro.min.css text/css
upload [5] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-schemes.min.css ext/metroui/css/metro-schemes.min.css text/css
upload [4] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-rtl.min.css ext/metroui/css/metro-rtl.min.css text/css
upload [3] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-responsive.min.css ext/metroui/css/metro-responsive.min.css text/css
upload [2] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-icons.min.css ext/metroui/css/metro-icons.min.css text/css
upload [1] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/ext/metroui/css/metro-colors.min.css ext/metroui/css/metro-colors.min.css text/css
upload [0] yahka.admin /opt/iobroker/node_modules/iobroker.yahka/admin/css/yahka.admin.css css/yahka.admin.css text/css
/opt/iobroker$  
`

after that I'm able to add the yahka adapter via the web interface:
here the log of that step:
`
$ ./iobroker add yahka  --host 17794c7348ba
host.17794c7348ba create instance yahka
host.17794c7348ba object system.adapter.yahka.0.outputCount created
host.17794c7348ba object system.adapter.yahka.0.inputCount created
host.17794c7348ba object system.adapter.yahka.0.uptime created
host.17794c7348ba object system.adapter.yahka.0.memRss created
host.17794c7348ba object system.adapter.yahka.0.memHeapTotal created
host.17794c7348ba object system.adapter.yahka.0.memHeapUsed created
host.17794c7348ba object system.adapter.yahka.0.connected created
host.17794c7348ba object system.adapter.yahka.0.alive created
host.17794c7348ba object system.adapter.yahka.0 created
process exited with code 0
`

**Comment by Jack187** [comment]
I just saw that the adapter is now started (v0.9.2). But I don't know what I did differently...
It seems as if it is working with this workaround. 
Thank you both for helping.

**Comment by buanet** [comment]
Ok, so I close this issue now.
