### ISSUE TITLE
add libfontconfig for PhantomJS

### ISSUE THREAD

**Issue by BenSchweikert** [buanet/docker-iobroker#21]
Hi,
could you please add libfontconfig so I can use the PhantomJS plugin for iobroker?

Thanks!
Ben

**Comment by buanet** [comment]
Hi Ben,
as libfontconfig is not needed for running ioBroker in standard installation, I will not add this package to the docker-image.
The sought solution for adding additional packages needed by adapters is to add these packages "as you need them" by using an environment variable. This is already included in actual beta and will become stable (latest) soon. For details please see readme.md. 

Best regards,
André
