### ISSUE TITLE
libpcap.so.0.8 is missing

### ISSUE THREAD

**Issue by stauraum** [buanet/docker-iobroker#22]
amazon-dash needs libpcap.so.0.8:

iobroker.2019-05-15.log:2019-05-15 07:41:23.396  - error: Caught by controller[0]: Error: libpcap.so.0.8: cannot open shared object file: No such file or directory
iobroker.2019-05-15.log:2019-05-15 07:41:23.396  - error: Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/pcap/pcap.js:3:21)
iobroker.2019-05-15.log:2019-05-15 07:41:53.829  - error: amazon-dash.0 uncaught exception: libpcap.so.0.8: cannot open shared object file: No such file or directory
iobroker.2019-05-15.log:2019-05-15 07:41:53.831  - error: amazon-dash.0 Error: libpcap.so.0.8: cannot open shared object file: No such file or directory

**Comment by buanet** [comment]
RTFM... 
Please use environment variable "PACKAGES".
For more details see readme.md.

Regards,
André
