### ISSUE TITLE
run iobroker process in foreground

### ISSUE THREAD

**Issue by b2un0** [buanet/docker-iobroker#23]
hi, you can run ioBrokler with `tee` so we can read the logs in docker (or `portainer`) and you can remove the useless `tail` command at the end.

https://github.com/buanet/docker-iobroker/blob/8bb400270d54e9dc229758395b3aad4b22d1225e/scripts/iobroker_startup.sh#L79

```bash
sudo -u iobroker node node_modules/iobroker.js-controller/controller.js | tee --output-error=warn /opt/scripts/iobroker.log
```

**Comment by buanet** [comment]
thx for your feedback. i will give it a try...

**Comment by buanet** [comment]
As you can see in the actual beta I'm running ioBroker in foreground now... Tests seem to be good so far. 

But I still have the `tail` command inside the startup-script. This will prevent the container to stop wenn doing some actions like updating js-controller or running `iobroker setup custom` where you have to stop ioBroker before.

Another change i made is to remove the additional logging to file when iobroker is started. This is not needed as ioBroker writes its own logs.

This issue will be closed. Thank you.

Regards,
André
