### ISSUE TITLE
How to stop iobroker

### ISSUE THREAD

**Issue by m50434** [buanet/docker-iobroker#24]
I have some troubles with your backup-script.
Sometimes it fails. That means that my Diskstation stucks in making a backup of the iobroker-container... and nothing helps: I have to restart my Diskstation by pressing on the on/off-button. And this hurts. 
Suprisly the backup doesnt fail every day... only one or two times a week.
Anyway: I read that you suggest to stop iobroker before the backup start.

How can I do this.
You write: 
>Einfaches Script zum Stoppen von ioBroker. 
> Kann zum Beispiel aus ioBroker heraus aufgerufen werden um ioBroker zu stoppen. 

Where do I have to put the script and how can I execute the script in iobroker??

**Comment by buanet** [comment]
Hi,
you can simply put the stop-script into your iobroker-folder (opt/iobroker) and call it with javascript from inside iobroker by using exec command:
```
   exec('/opt/iobroker/iobroker_stop.sh', function(err, stdout, stderr) {
    if (err) {
       log(stderr,'error');
       return;
        }
    });
```
BUT
I think stopping iobroker inside your container is not your problem. 
Maybe there is a Problem with Docker on your DS. If you use my backup-script, the script does a simple
`docker stop [yourcontainername]`
Make sure this command works by using the comandline in your DSM.  
You can also activate e-mail notifications in your synology taskplaner to see if the task gets some errors during execution.

**Comment by buanet** [comment]
If there are still any questions please visit us at iobroker forum thread.

Regards,
André
