### ISSUE TITLE
Radar2 adapter fails to start due to missing net-tools package

### ISSUE THREAD

**Issue by dwm66** [buanet/docker-iobroker#27]
The new "Radar 2.0" adapter fails, as it cannot spawn the arp program (contained in net-tools).

I propose to include net-tools in the container.
See https://forum.iobroker.net/topic/23164/radar-2-adpater-will-einfach-nicht-laufen

Regards
Werner

**Comment by Apollon77** [comment]
Then you need to install it in the container before?

**Comment by dwm66** [comment]
Yes - before installing Radar 2.0, you have to install the net-tools package to the container.

I'm fully aware of the fact, that it's quite easy to install it - in fact it's a simple 
apt-get update && apt-get install net-tools
but you have to do every time you update the image/container to a new version.
This is why i thought it convenient to have it in the base image and opened the issue, as net-tools also is not really big.

Other solutions are of course creating an own, adapted image.

Well, the tradeoff IMHO on one side to support as many adapters as possible without creating an image carrying lots of unnecessary stuff ... that i happily leave to the maintainers to decide ;)

**Comment by buanet** [comment]
RTFM...
Please use env "PACKAGES" to install additional packages! For more informations see readme.md.

If I would add every requested package for every adapter it would blow up the image a lot... So i decided to add the PACKAGES variable and only include packages needed to run iobroker core to the image by default...

Regards,
André
