### ISSUE TITLE
no webservice and other things in new container image

### ISSUE THREAD

**Issue by Surfer2010** [buanet/docker-iobroker#28]
Hello, since the new update 3 Days ago ... the new container image is not working at all anymore. It installs some files, but there is no instance running:
```
 1 root      20   0   21172   3312   3024 S   0,0  0,1   0:00.05 iobroker_startu
  303 root      20   0   21400   3876   3328 S   0,0  0,1   0:00.04 bash
  309 root      20   0   52716   3684   3272 S   0,0  0,1   0:00.00 sudo
  310 root      20   0    7404    720    656 S   0,0  0,0   0:00.00 tail
  311 iobroker  20   0  924068  50152  23208 S   0,0  1,3   0:00.42 iobroker.js-con
  327 root      20   0   44232   3564   3064 R   0,0  0,1   0:00.06 top
```
here are the files:
```
root@dffd1b76db6d:/opt/iobroker# ls -l
insgesamt 284
-rw-rwxr--+   1 iobroker iobroker   1049 Jun 17 03:37 CHANGELOG_FIXER_LINUX.md
-rw-rwxr--+   1 iobroker iobroker   3556 Jun 17 03:37 CHANGELOG_INSTALLER_LINUX.md
-rw-rwxr--+   1 iobroker iobroker  23988 Jun 17 03:37 fix_installation.sh
drwxrwxr-x+   3 iobroker iobroker   4096 Jun 17 03:37 install
-rwxrwxrwx+   1 iobroker iobroker    149 Jun 17 03:40 INSTALLER_INFO.txt
lrwxrwxrwx    1 iobroker iobroker     22 Jun 17 03:40 iob -> /opt/iobroker/iobroker
-rwxrwxr-x+   1 iobroker iobroker    102 Jun 17 03:40 iobroker
drwxrwxr-x+   4 iobroker iobroker   4096 Jun 20 15:30 iobroker-data
drwxrwxr-x+   2 iobroker iobroker   4096 Jun 17 03:37 lib
-rw-rwxr--+   1 iobroker iobroker   1137 Jun 17 03:37 LICENSE
drwxrwxr-x+   2 iobroker iobroker   4096 Jun 20 15:55 log
drwxrwxr-x+ 456 iobroker iobroker  20480 Jun 17 03:40 node_modules
-rw-rwxr--+   1 iobroker iobroker    569 Jun 17 03:37 package.json
-rw-rwxr--+   1 iobroker iobroker 166066 Jun 17 03:40 package-lock.json
-rw-rwxr--+   1 iobroker iobroker   6101 Jun 17 03:37 README.md
-rw-rwxr--+   1 iobroker iobroker   5868 Jun 17 03:38 reinstall.js
```
new Installation today, with the new image, empty mounted host-folder, ports 8081 passed thru, bridge mode ...!?

Please help!!!!

**Comment by buanet** [comment]
What about logs/ protocol of the iobroker container?

**Comment by Surfer2010** [comment]
```
---------------------------------------
-----   Image-Version: 3.0.2beta   -----
-----      2019-06-20 16:37:57     -----
----------------------------------------

Startupscript running...

Installing additional packages...
The following packages will be installed: nano
Installing additional packages done...

Directory /opt/iobroker is empty!
Restoring data from image...
Restoring done...

This is the first run of an new installation...
Hostname given is a07001fa7a86...
Renaming ioBroker...
/opt/scripts/iobroker_startup.sh: Zeile 53: /usr/bin/iobroker: Keine Berechtigung
Renaming ioBroker done...

Changing permissions upon first run (This might take a while! Please be patient!)...
Changing permissions done...

Starting ioBroker...

----------------------------------------
-------     ioBroker Logging     -------
----------------------------------------

host.a07001fa7a86 check instance "system.adapter.admin.0" for host "6a152b308ff2"
host.a07001fa7a86 check instance "system.adapter.discovery.0" for host "6a152b308ff2"
```
top (exec into container)
```
 PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
    1 root      20   0   21176   3340   3048 S   0,0  0,1   0:00.07 iobroker_startu
  310 iobroker  20   0  931584  54256  23056 S   0,0  1,4   0:08.54 iobroker.js-con
  332 root      20   0   21400   3480   3060 S   0,0  0,1   0:00.03 bash
  484 root      20   0   21400   3572   3152 S   0,0  0,1   0:00.04 bash
  489 root      20   0   44220   3556   3068 R   0,0  0,1   0:00.00 top

```
What else would help? Just tell me what/where and i will post it

**Comment by buanet** [comment]
There is an issue during the renaming part of the startup script....
`/opt/scripts/iobroker_startup.sh: Zeile 53: /usr/bin/iobroker: Keine Berechtigung`
Something there is not working properly. Will try to reproduce it tomorrow.

**Comment by Surfer2010** [comment]
```
root@a07001fa7a86:/opt/iobroker# pkill io
root@a07001fa7a86:/opt/iobroker# iobroker host this
bash: /usr/bin/iobroker: Keine Berechtigung
root@a07001fa7a86:/opt/iobroker#
root@a07001fa7a86:/opt/iobroker# iobroker start
bash: /usr/bin/iobroker: Keine Berechtigung
```
obwohl ich mittels docker exec -it iobroker /bin/bash   eigentlich doch root sein müsste? Vielleicht hilft das

**Comment by buanet** [comment]
Sorry, I can not reproduce this issue. Think there is something wrong with your permissions.
How do you run the container? Which System and versions do you use?
At the moment I don't think that there is a problem with the image...

**Comment by Surfer2010** [comment]
#1 SMP Debian 4.19.28-2~bpo9+1 (2019-03-27)
OpenMediaVault v4.1.22-1

What else would help you to check? You could also check it out on my system if you want

**Comment by buanet** [comment]
Please try to setup a container without mounting any directories to it or use a docker created volume.
Think there is a problem with the directory permissions of the mounted folder.

**Comment by Surfer2010** [comment]
i still don't get it to work ... would be great to get some help ... i really need this container

**Comment by Surfer2010** [comment]
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
    1 root      20   0   21176   3520   3228 S   0,0  0,0   0:00.07 iobroker_startu
  304 root      20   0    7404    696    632 S   0,0  0,0   0:00.00 tail
  311 root      20   0   21404   3620   3192 S   0,0  0,0   0:00.05 bash
  316 root      20   0   44220   3640   3168 R   0,0  0,0   0:00.00 top

```
here you can see the processes running ... there should be some more to have it run ?!!

**Comment by Surfer2010** [comment]
drwxrwxr-x+  7 1000 users 4096 Jun 23 00:07 ioBroker
is the mounted folder in the host system

**Comment by Surfer2010** [comment]
> Please try to setup a container without mounting any directories to it or use a docker created volume.
> Think there is a problem with the directory permissions of the mounted folder.

doesn't change anything

where can i find logs that will help?

**Comment by buanet** [comment]
Hi,
Wenn ich mich recht erinnere, dann hatten wir es im iobroker Forum schonmal, deshalb versuche ich es jetzt einfach mal auf deutsch...
Ich weiß nicht so recht wie ich dir helfen soll. Für mich sieht das nach einem Berechtigungsproblem aus.
Ich sehe in deinem Protokoll, dass dein iobroker daran scheitert den Hostnamen anzupassen. Das macht das Startup-Script per "iobroker host this". Wenn du das auf der Kommandozeile tust bekommst du ebenfalls "Keine Berechtigung". Sogar beim "iobroker Start" kommt dieser Fehler.
Das bedeutet, dein Problem ist, dass du die folgende Datei nicht ausführen darfst "/opt/iobroker/iobroker". Die Berechtigungen passen allerdings. Und zusätzlich bist du in der Kommandozeile ja auch noch root...
Kurzum, ich weiß nicht wo es klemmt. Habe den Container auf der DS und meinem Debian System getestet, bekomme dein Problem nicht reproduziert.
Und wenn der Container nichtmal läuft wenn du kein Verzeichnis mountest (dann passiert ja alles nur noch innerhalb des Containers) dann weiß ich echt nicht mehr was ich dir noch zum ausprobieren an die Hand geben soll...

MfG,
André

**Comment by Surfer2010** [comment]
If i copy my old <iobroker-config files> into the mounted folder and start the container, it works, but has a lot of errors like this

```
host.1868f6c458bf | 2019-06-23 00:37:08.238 | info | Restart adapter system.adapter.sql.0 because enabled
-- | -- | -- | --
host.1868f6c458bf | 2019-06-23 00:37:08.237 | error | instance system.adapter.sql.0 terminated with code 1 ()
host.1868f6c458bf | 2019-06-23 00:37:08.237 | error | Caught by controller[0]: at Module.load (module.js:566:32)
host.1868f6c458bf | 2019-06-23 00:37:08.237 | error | Caught by controller[0]: at Object.Module._extensions..js (module.js:664:10)
host.1868f6c458bf | 2019-06-23 00:37:08.237 | error | Caught by controller[0]: at Module._compile (module.js:653:30)
host.1868f6c458bf | 2019-06-23 00:37:08.237 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/mmmagic/lib/index.js:1:75)
host.1868f6c458bf | 2019-06-23 00:37:08.237 | error | Caught by controller[0]: at require (internal/module.js:11:18)
host.1868f6c458bf | 2019-06-23 00:37:08.237 | error | Caught by controller[0]: at Module.require (module.js:597:17)
host.1868f6c458bf | 2019-06-23 00:37:08.237 | error | Caught by controller[0]: at Function.Module._load (module.js:498:3)
host.1868f6c458bf | 2019-06-23 00:37:08.237 | error | Caught by controller[0]: at tryModuleLoad (module.js:506:12)
host.1868f6c458bf | 2019-06-23 00:37:08.237 | error | Caught by controller[0]: at Module.load (module.js:566:32)
host.1868f6c458bf | 2019-06-23 00:37:08.237 | error | Caught by controller[0]: at Object.Module._extensions..node (module.js:682:18)
host.1868f6c458bf | 2019-06-23 00:37:08.237 | error | Caught by controller[0]: Error: /opt/iobroker/node_modules/mmmagic/build/Release/magic.node: failed to map segment from shared object
host.1868f6c458bf | 2019-06-23 00:37:08.237 | error | Caught by controller[0]: ^
host.1868f6c458bf | 2019-06-23 00:37:08.237 | error | Caught by controller[0]: return process.dlopen(module, path._makeLong(filename));
host.1868f6c458bf | 2019-06-23 00:37:08.237 | error | Caught by controller[0]: module.js:682
host.1868f6c458bf | 2019-06-23 00:37:07.856 | info | instance system.adapter.sql.0 started with pid 8263
```
So this is no solution ... the container runs, is accesable but no way to really use it

**Comment by Surfer2010** [comment]
ok danke für deine Antwort, ich stimme dir zu dass es wohl ein Rechte-Problem sein muss.
Ich frage trotzdem weiter, du dein Image usw. besser kennst als ich.

Gibt es irgendwelche Verzeichnisse die ersteltl werden müssen? Weil die Tatsache dass ich ein altes Mounted Volume in den Ordner rein kopiere und sofort läuft das ganze deutet ja darauf hin, dass iwas nicht erstellt werden kann. Welche Rechte braucht man denn auf dem Host? Werden Subfolders erstellt die zwingend nötig sind?
Kannst du vielleicht von einer Neu-Installation des Containers die Verzeichnisstruktur mit allem 2 Level mal posten dann schaue ich was fehlt?

**Comment by Surfer2010** [comment]
/opt/scripts/iobroker_startup.sh: Zeile 49: /usr/bin/iobroker: Keine Berechtigung

**Comment by buanet** [comment]
Ich glaube nicht dass etwas fehlt.
Hast du mal das leere Verzeichnis dass du mountest gelöscht und ein neues erstellt?
Du kannst auch im Container mal ein `chmod 777 /opt/iobroker/iobroker` machen um die Berechtigungen hoch zu setzen...

**Comment by Surfer2010** [comment]
root@9d16591a7ba6:/opt/iobroker# chmod +x reinstall.sh
root@9d16591a7ba6:/opt/iobroker# ./reinstall.sh
bash: ./reinstall.sh: Keine Berechtigung

Woran kann es liegen, dass ich im container keine Rechte habe?
https://pastebin.com/4w5Lw13c
https://pastebin.com/eJNMW0Ff

Alternativer Weg könnte noch sein, dass ich den alten mounted Folder nehme, damit läuft der Container ja doch (warum auch immeR) ... und ich dort den iobroker NEU installiere, weil ohne neuinstallation habe ich sql-Adapter usw. die sich nicht starten lassen vermutlich aufgrund von altlasten

**Comment by Surfer2010** [comment]
if i run
docker run -it -p 8081:8081 buanet/iobroker:latest sh

it will stop at
`Changing permissions upon first run (This might take a while! Please be patient!)...`
i can only continue with CTRL+C then it "stops" again at
`Starting ioBroker done...`
and i have no possibility to do something again ?!
Maybe that helps?

**Comment by buanet** [comment]
Die Anpassung der Berechtigungen kann eine, Weile dauern... Wie lange hast du gewartet?
Wenn du in einer bestehenden Installation "reparieren" willst, könntest du `npm rebuild` machen.
Oder du probierst mal den installation fixer. (hab ich selbst aber noch nie probiert)
Hast du denn jetzt mal probiert einen ganz neuen Ordner auf dem host zu erstellen? Eventuell dann die Rechte auf 777 ändern und dann den Container neu erstellen und den neuen, leeren Ordner einhängen...

**Comment by Surfer2010** [comment]
> npm rebuild

ergibt folgendes:

https://pastebin.com/yVGYp3EM

(neuer Container) ... ?! bekomm es einfach nicht zum laufen, auch 777 hilft nichts

Ein weiterer Versuch hier:
docker run -d --network dockernet --name=iobroker -p 1880:1880 -p 1883:1883 -p 1887:1887 -p 8081:8081 -p 8082:8082 --restart=always -e PUID=1000 -e PGID=100 -e TZ=Europe/Berlin -v /sharedfolders/DockerData/ioBroker:/opt/iobroker/  buanet/iobroker:latest
327e0c01e82003f4850b55892687330a770a249eb57de85caa738246ca91a9b1
root@FriedbergServer:/sharedfolders/DockerData# docker logs -f iobroker

----------------------------------------
-----     Image-Version: 3.0.0     -----
-----      2019-06-25 00:10:03     -----
----------------------------------------

Startupscript running...

Installing additional packages...
The following packages will be installed: nano
Installing additional packages done...

Directory /opt/iobroker is empty!
Restoring data from image...
Restoring done...

This is the first run of an new installation...
Hostname given is 327e0c01e820...
Renaming ioBroker...
/opt/scripts/iobroker_startup.sh: Zeile 49: /usr/bin/iobroker: Keine Berechtigung
Renaming ioBroker done...

Changing permissions upon first run (This might take a while! Please be patient!)...
Changing permissions done...

Starting ioBroker...
Starting ioBroker done...

**Comment by buanet** [comment]
Du hast definitiv ein Rechteproblem auf deinem ioBroker-Ordner. 
Hast du denn nun einmal ausprobiert ohne ein gemountetes Verzeichnis zu starten? Also das hier weg lassen: `-v /sharedfolders/DockerData/ioBroker:/opt/iobroker/`...
Wenn das geht, dann musst du mal schauen unter welchem User dein docker daemon läuft und ob dieser User ausrechend Rechte auf den Ordner `/sharedfolders/DockerData/ioBroker` hat. Vielleicht kannst du den Benutzer unter dem dein docker läuft für diesen Ordner auch zum Besitzer machen...

Da es sich meiner Meinung nach nicht um einen Bug im Image handelt, Schließe ich den issue jetzt. Meine Empfehlung: Eröffne ein Thema im ioBroker-Forum (falls noch nicht passiert) und kommentiere den Link hier.
Vielleicht ist im Forum ein User unterwegs der ein ähnliches Setup hat oder das Problem schon mal in irgendeiner Form hatte...

MfG,
André

**Comment by buanet** [comment]
Just for documentation, this message I recived from @Surfer2010 :

> Hi, i solved my "issue" before (i posted on your github) ... the reason is as simple as hard to find ... i tracked it down to permission issues as you also said, but ...
> my folder / the drive it was on, was mounted as    "noexec"    in the fstab ... 
> that was the reason the container couldn't write all the files ....

**Comment by mplogas** [comment]
Das scheint OpenMediaVault-spezifisch zu sein, ich bin da auch drüber gestolpert. 
Ich habs vermutlich ohnehin gefixt in #33 mit ```sh /opt/iobroker/iobroker```. Zumindest wird der Hostname sauber gesetzt und die UI erscheint.
