### ISSUE TITLE
iobroker satart fehler

### ISSUE THREAD

**Issue by Shepherd7** [buanet/docker-iobroker#29]
bekomme beim starten im Log diese Fehler. Mbus und AVHI.
Aber es funktioniert alles auch Yakha habe ich keine Probleme.
`
----------------------------------------
-----     Image-Version: 3.0.0     -----
-----      2019-06-21 08:49:33     -----
----------------------------------------
Startupscript running...
Installing additional packages...
The following packages will be installed: nano
Installing additional packages done...
Changing permissions upon first run (This might take a while! Please be patient!)...
Changing permissions done...
Initializing Avahi-Daemon...
Checking avahi-daemon installation state...
ahi already installed...
Starting dbus...
Failed to start message bus: Failed to bind socket "/var/run/dbus/system_bus_socket": No such file or directory
Starting avahi-daemon...
Starting Avahi mDNS/DNS-SD Daemon: avahi-daemon failed!
Initializing Avahi-Daemon done...
Starting ioBroker...
Starting ioBroker done...`

**Comment by buanet** [comment]
Sehr gut aufgepasst. :) Hatte einen kleinen Fehler eingebaut den ich gerade beseitigt habe.
Ist drin im aktuellen Beta und wird in die nächste Version übernommen. Dann sollte der Fehler weg sein. 

MfG,
André
