### ISSUE TITLE
iobroker doesn´t start automatically

### ISSUE THREAD

**Issue by DocUltra** [buanet/docker-iobroker#3]
Hi,

i installed the docker on qnap and iobroker doesn´t start automatically after I started the image.
I have to always start it manually?

**Comment by buanet** [comment]
Hi,
normally it should start automatically.
Maybe you have to configure your container for running the startup-script?
Btw, this image is made for running in docker on a Synology nas. So no guarantee that it will also work on qnap. Maybe it will need a special configuration?
Try to get support at the official ioBroker forum. Sorry.

This is not an issue. Closed #3.
