### ISSUE TITLE
ARM64 Unterstützung möglich (z.B. QNAP 332x)?

### ISSUE THREAD

**Issue by Monnem** [buanet/docker-iobroker#30]
Hallo zusammen,

ich habe in der Qnap Containerstation (Qnap 332x mit ARM <wasauchimmer> CPU) den Container installiert (latest), bekomme aber in der Containerconsole folgende Fehlermeldung: 
standard_init_linux.go:185: exec user process caused "exec format error"  
Ich vermute mal stark mit meinen begrenzten Docker Kenntnissen, dass der Container kein ARM64/AARCH64 unterstützt. Vermutlich nur Intel, oder?
Die Qnap spuckt als Cpu Info folgendes aus:
processor	: 3
model name	: Annapurna Labs Alpine AL324 Quad-core ARM Cortex-A57 CPU @ 1.70GHz
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0xd07
CPU revision	: 3

Ich hatte mal testweise was gaaanz anderes installiert:
angelnu/iobroker:latest-arm64.
Das läuft auf alle Fälle mal an (falls irgendwie hilfreich)
Fehlen noch Infos?

Danke

**Comment by buanet** [comment]
Ich habe mal ein Image (tag: beta_armhf) auf dem Docker-Hub abgelegt. Kannst du das vielleicht mal testen? Das basiert auf arm32v7. Eventuell läuft das bei dir aber trotzdem.
Habe leider momentan keine Hardware auf der ich ein arm64v8 image erzeugen könnte, daher wird es damit derzeit schwierig...

MfG,
Andre

**Comment by Monnem** [comment]
Moin moin,

danke für das Image. Leider dieselbe Meldung. Ich hätte hier noch nen Raspi 3b+, der sich aktuell langweilt. Das müsste doch eigentlich die passende Plattform sein? Bin zwar generell halbwegs Linuxkompatibel, bin aber nicht drin in Entwicklung/Docker Sachen. Aber wenn das irgendwie hilft?

BG
Daniel

**Comment by mcdhrts** [comment]
@Monnem 
ich habe ein Raspi 3 Docker Image auf Basis von Buanet 3.0 Image:
https://hub.docker.com/r/mcdhrts/iobroker_pi3

Vielleicht hilft dir das weiter.

Grüße

**Comment by Monnem** [comment]
Moin,
läuft leider auch nicht. Ich habe mal fleissig einige Container versucht. Der von Duffbeer läuft prinzipiell. Der hat zusätzlich noch eine aarch64 Variante implementiert. Das wäre dann wohl das passende Format. Wäre natürlich super, wenn irgendwann mal das "Original" hier die entsprechende Unterstützung bekäme :-)
Wenn ich irgendwas helfen/testen kann, immer her mit der Anfrage
Thx
Daniel

**Comment by duffbeer2000** [comment]
Hi Andre,
wenn du magst helf ich dir beim einrichten von ner Build Pipeline die automatisch die Images für die entsprechenden Architekturen baut.
Gruß
Christian

**Comment by buanet** [comment]
Hallo Christian,
darauf komme ich gerne zurück. :) Habe schon fleißig bei dir abgeschaut und wollte das auch mal über Travis zum Laufen bringen. Leider fehlt mit ein bisschen die Zeit. Würde mich gerne da rein arbeiten damit ich auch verstehe was da passiert...

MfG,
André

**Comment by duffbeer2000** [comment]
Alles klar, diese Woche wird es leider nichts mehr aber ab Montag setze ich mich mal ran und mach nen fork. Ich schreib dir dann zusammen was was ist.

**Comment by buanet** [comment]
Schau mal, habe schon ein bisschen was probiert: https://github.com/buanet/travis-testing
Muss noch die Sache mit dem Manifest und dem push machen, aber der Build läuft schonmal durch... Am besten du machst da einen issue bzw forks das, dann können wir da weiter machen... :)

**Comment by buanet** [comment]
@Monnem
Im aktuellen Beta gibt es jetzt auch Images für aarch64 und armv7hf. Bitte testen.
Falls es nicht klappt mache bitte auf deinem QNAP mal ein 'uname -m' und poste das Ergebnis. Danke. 

MfG, 
André

**Comment by Monnem** [comment]
Grandios! :-)
Mangels Zeit erst mal nur "Beta" installiert. -> Startet
Kann gerne Freitag noch mal explizit die einzelnen Versionen der Beta testweise installieren, falls gewünscht.

Bis denne
Daniel

**Comment by buanet** [comment]
Die einzelnen Versionen sind nicht relevant. Wenn du über Docker den Beta-Tag ziehst sollte er immer automatisch das für deine Architektur passende Image ziehen.
Da das schonmal klappt schließe ich den Issue erstmal. Sollte es Probleme geben melde gerne einen neuen...

MfG,
André
