### ISSUE TITLE
IoBroker 

### ISSUE THREAD

**Issue by Jan-2005** [buanet/docker-iobroker#31]
Habe gestern Iobroker im Docker Compose erstellt:

  iobroker:
    restart: always      
    image: buanet/iobroker:latest
    volumes:
      -  /etc/localtime:/etc/localtime:ro
      - ./home/intelnuc/fhem-docker/iobroker:/opt/iobroker
      - ./home/intelnuc/fhem-docker/iobroker/transfer:/tmp
    
    networks:
      macvlan0:
        ipv4_address: 192.168.200.17
      fhem-network: {}

networks:

  fhem-network:
    driver: bridge

  macvlan0:
    driver: macvlan
    driver_opts:
      parent: enp0s3
    ipam:
      config:
      - subnet: 192.168.200.0/24
        gateway: 192.168.200.1
        ip_range: 192.168.200.17/32

IObroker sagt im Log:

Startupscript running...
Installing additional packages...
The following packages will be installed: nano
Installing additional packages done...
Changing permissions upon first run (This might take a while! Please be patient!)...
Changing permissions done...
Starting ioBroker...
Starting ioBroker done...

Aber der Ordner bei dem Host ist leer.

**Comment by buanet** [comment]
Ist der Ordner auf dem Host wirklich leer? Versteckte-/ System-Dateien vielleicht?
Das Startup Script prüft ob der eingehängte Host-Ordner leer ist. Nur dann werden die Dateien dort hinein geschrieben. In deinem Log steht aber nicht, dass das Script einen leeren Ordner erkennt... 

MfG,
André

**Comment by Jan-2005** [comment]
Ja habe alles gecheckt. 
![Screenshot 2019-07-16 09 58 15](https://user-images.githubusercontent.com/31730258/61276215-dff4f980-a7af-11e9-9ff6-fec8dd359e40.png) <<<  ./home/intelnuc/fhem-docker/iobroker
![Screenshot 2019-07-16 09 58 36](https://user-images.githubusercontent.com/31730258/61276224-e5524400-a7af-11e9-8a65-a9a475c2d246.png)
/home/intelnuc/fhem-docker/iobroker/transfer

**Comment by buanet** [comment]
Dein Ordner ist doch gar nicht leer...

In dem Ordner, den du als /opt/iobroker/ einbindest, liegt noch der (Unter-)Ordner "transfer" (den du dann offenbar als /tmp einbindest... Dementsprechend ist der Ordner /opt/iobroker nicht leer...

MfG,
André

**Comment by Jan-2005** [comment]
Container läuft jetzt. Jetzt klappt nur noch nicht die Weboberfläche

**Comment by buanet** [comment]
Das sind Themen für das Forum. Ich sehe hier keinen Issue.

#closed
