### ISSUE TITLE
Probleme beim updaten von Adaptern

### ISSUE THREAD

**Issue by octane321** [buanet/docker-iobroker#32]
Ich habe Probleme damit einige Adapter upzudaten.
Im speziellen geht es dabei aktuell um folgende Adapter:
* Admin
* Bluetooth Low Energy
* Homematic ReGaHSS
* Homematic RPC
* Script Engine
* Shelly
* Simple API Adapter
* Text To speech
* Weather Underground forecast

Beim versuch z.B. den Shelly Adapter upzudaten erhalte ich folgende Log Outputs:
```
$ ./iobroker upgrade shelly
Update shelly from @3.0.2 to @3.0.7
NPM version: 6.4.1
npm install iobroker.shelly@3.0.7 --production --save --prefix "/opt/iobroker" (System call)
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/cc-znp/package.json'npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/node_modules/ms/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/@abandonware/noble/node_modules/nopt/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/node_modules/debug/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/node_modules/nopt/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/node_modules/node-pre-gyp/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/@abandonware/noble/node_modules/node-pre-gyp/package.json'


npm
 ERR! Cannot read property '0' of undefined

npm ERR! A complete log of this run can be found in:npm ERR!     /home/iobroker/.npm/_logs/2019-07-28T00_32_52_970Z-debug.log

got /opt/iobroker/node_modules/iobroker.shelly/admin
upload [2] shelly.admin /opt/iobroker/node_modules/iobroker.shelly/admin/words.js words.js application/javascript
upload [1] shelly.admin /opt/iobroker/node_modules/iobroker.shelly/admin/shelly.png shelly.png image/png
upload [0] shelly.admin /opt/iobroker/node_modules/iobroker.shelly/admin/index_m.html index_m.html text/html
Adapter "shelly" updated
process exited with code 0
```
Am Ende von /home/iobroker/.npm/_logs/2019-07-28T00_32_52_970Z-debug.log zeigt sich folgendes:

```
1538 warn enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/cc-znp/package.json'
1539 verbose enoent This is related to npm not being able to find a file.
1540 warn enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/package.json'
1541 verbose enoent This is related to npm not being able to find a file.
1542 warn enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/node_modules/ms/package.json'
1543 verbose enoent This is related to npm not being able to find a file.
1544 warn enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/@abandonware/noble/node_modules/nopt/package.json'
1545 verbose enoent This is related to npm not being able to find a file.
1546 warn enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/node_modules/debug/package.json'
1547 verbose enoent This is related to npm not being able to find a file.
1548 warn enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/node_modules/nopt/package.json'
1549 verbose enoent This is related to npm not being able to find a file.
1550 warn enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/node_modules/node-pre-gyp/package.json'
1551 verbose enoent This is related to npm not being able to find a file.
1552 warn enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/@abandonware/noble/node_modules/node-pre-gyp/package.json'
1553 verbose enoent This is related to npm not being able to find a file.
1554 verbose stack TypeError: Cannot read property '0' of undefined
1554 verbose stack     at rmStuff (/usr/lib/node_modules/npm/lib/unbuild.js:61:24)
1554 verbose stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
1554 verbose stack     at ret (eval at makeNodePromisifiedEval (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
1554 verbose stack     at lifecycle.then.then (/usr/lib/node_modules/npm/lib/install/action/unbuild.js:12:12)
1554 verbose stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
1554 verbose stack     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
1554 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
1554 verbose stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
1554 verbose stack     at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
1554 verbose stack     at Promise._fulfill (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
1554 verbose stack     at /usr/lib/node_modules/npm/node_modules/bluebird/js/release/nodeback.js:42:21
1554 verbose stack     at <anonymous>
1555 verbose cwd /opt/iobroker
1556 verbose Linux 4.19.56-Unraid
1557 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "iobroker.shelly@3.0.7" "--production" "--save" "--prefix" "/opt/iobroker"
1558 verbose node v8.16.0
1559 verbose npm  v6.4.1
1560 error Cannot read property '0' of undefined
1561 verbose exit [ 1, true ]
```

Als Node/npm/linux Laie komme ich hier nicht weiter, ich würde mich sehr über eine kleinen Anstoß freuen mit dem ich meine Adapter wieder updaten kann. Ob es sich hier um einen Bedienungsfehler oder um in generelles Problem handelt kann ich nicht sagen.
PS: Der Container läuft bei mir unter einem UnRaid System.

**Comment by buanet** [comment]
Ich glaube nicht dass das ein Problem des Containers ist. Denke mal da klemmt was bei npm.
Hast du eine "frische" iobroker-Installation oder hast du dein iobroker-Verzeichnis von irgendwo übernommen?
Welche Container Version benutzt du und was gibt "npm -v" und "node -v"?
Sind die files bzw directories die er anmeckert vorhanden oder fehlen sie tatsächlich? 

Hast du mal im Forum nach der Fehlermeldung gesucht? Eventuell hilft schon ein "npm rebuild"... Dazu findet sich auch einiges im Forum.

MfG,
André

**Comment by farinpl** [comment]
Moin,
hab leider das gleiche Problem:
Host: Linux Tower 4.19.55-Unraid
npm -v 6.4.1 node -v v8.16.0
Ich habe bei mir das iobroker-Verzeichnis aus einer alten Installation übernommen, hatte aber vor einigen Wochen noch keine Probleme Adapter zu updaten. Jetzt lässt sich kein Container mehr updaten. Die entsprechenden Files die angemeckert werden sind wirklich nicht vorhanden, jedoch existieren die directories. npm rebuild hat leider nicht geholfen.

`npm install iobroker.alexa2@2.6.4 --unsafe-perm --production --save --prefix "/opt/iobroker" (System call)
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/cul/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/nan/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.zigbee/node_modules/@serialport/bindings/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/abbrev/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/aproba/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/are-we-there-yet/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/balanced-match/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/code-point-at/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/ansi-regex/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/brace-expansion/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/concat-map/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/core-util-is/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/console-control-strings/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/deep-extend/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/detect-libc/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/chownr/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/fs-minipass/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/debug/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/delegates/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/gauge/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/glob/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/has-unicode/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/inherits/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/ini/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/iconv-lite/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/fs.realpath/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/isarray/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/inflight/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/is-fullwidth-code-point/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/minizlib/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/minipass/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/minimist/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/needle/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/ms/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/mkdirp/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/minimatch/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/nopt/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/ignore-walk/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/npm-packlist/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/number-is-nan/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/npmlog/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/node-pre-gyp/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/npm-bundled/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/os-tmpdir/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/once/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/process-nextick-args/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/object-assign/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/path-is-absolute/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/os-homedir/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/osenv/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/rimraf/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/readable-stream/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/rc/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/semver/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/set-blocking/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/string_decoder/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/safer-buffer/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/sax/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/signal-exit/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/safe-buffer/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/tar/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/string-width/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/strip-json-comments/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/wrappy/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/util-deprecate/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/strip-ansi/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/yallist/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/wide-align/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/fsevents/node_modules/rc/node_modules/minimist/package.json'

npm ERR! Cannot read property '0' of undefined`

Gruß
David

**Comment by octane321** [comment]
Hallo zusammen.
Ich habe nun npm auf 6.10.2 aktualisiert - seit dem hab ich keine Probleme mit Adapter-Updates mehr.

@farinpl: Wenn das bei dir auch hilft, kannst du das issue bitte schließen?

Grüße

**Comment by JoschaMiddendorf** [comment]
@farinpl Du hattest mir doch noch irgendwas von veränderten Skripten oder so erzählt.

**Comment by farinpl** [comment]
Moin,
@JoschaMiddendorf ich habe die Lösung  [hier](https://github.com/epoberezkin/ajv/issues/601#issuecomment-488970199) gefunden. 

> Hallo zusammen.
> Ich habe nun npm auf 6.10.2 aktualisiert - seit dem hab ich keine Probleme mit Adapter-Updates mehr.
> 
> @farinpl: Wenn das bei dir auch hilft, kannst du das issue bitte schließen?
> 
> Grüße

Danke für deine Rückmeldung, ich werde npm mal bei Gelegenheit updaten und die Änderung im Skript rückgängig machen und testen. 

Gruß
Farin

**Comment by buanet** [comment]
Gibt es hier noch Probleme oder kann ich den Issue schließen?

MfG,
André
