### ISSUE TITLE
bad tag name and/or "\r" error

### ISSUE THREAD

**Issue by drtp** [buanet/docker-iobroker#34]
Hi,

I have installed version 3.1.0 of the docker-iobroker on a Synology DiskStation DS718+ using MACVLAN with IP adresses 192.168.0.10 and 192.168.0.11. The ioBroker admin webUI is reachable under 192.168.0.12. Everything works fine so far.

However, a simple update by using the command "iobroker update" leads to an "node \r" error. If I try the alternative by using "npm install iobroker.js-controller --production", npm shows an "EINVALIDTAGNAME" message. 

Respective screenshots and further infos in German language can be found [here](https://forum.iobroker.net/topic/4733/howto-anleitung-installation-iobroker-in-docker-auf-synology-diskstation/996) and [here](https://forum.iobroker.net/topic/4733/howto-anleitung-installation-iobroker-in-docker-auf-synology-diskstation/1022).

When I switch to version 2 of docker-iobroker using exact the same mounted directories (/volume1/docker/ioBroker) there is no such error message.

**Comment by buanet** [comment]
Hi,
at the forum thread ([link](https://forum.iobroker.net/post/317162)) I read that this issue is gone after modifying and running "reinstall.sh". Can you confirm?
Can this be closed? Thx.

Regards, 
André

**Comment by drtp** [comment]
Hi André,

 

yes. Thanks for your support.

 

Best regards,

 

Thorsten

 

Von: Andre <notifications@github.com> 
Gesendet: Montag, 28. Oktober 2019 22:43
An: buanet/docker-iobroker <docker-iobroker@noreply.github.com>
Cc: drtp <drtp@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [buanet/docker-iobroker] bad tag name and/or "\r" error (#34)

 

Hi,
at the forum thread (link <https://forum.iobroker.net/post/317162> ) I read that this issue is gone after modifying and running "reinstall.sh". Can you confirm?
Can this be closed? Thx.

Regards,
André
