### ISSUE TITLE
Can you give js-controller 2.0.0 a try ?!

### ISSUE THREAD

**Issue by Apollon77** [buanet/docker-iobroker#35]
Hi there,

we are coming closer for js-controller 2.0.0 and there are several changes in there, also how things are handled and such. Could you give js-controller (so install directly from GitHub Master ala `npm install ioBroker/ioBroker.js-controller`) a try that we see if things are broken for the docker image and/or we or you need to plan in changes?

Thank you!

**Comment by buanet** [comment]
Will do.
What ist best for it, Node 8 or 10?

Regards,
André

**Comment by Apollon77** [comment]
in fcat should work both. recommended with 1.5.x already is nodejs 10 :-) (because 8 will go EOL next year)

**Comment by buanet** [comment]
Tested with latest beta image (node10).
After installation of js-controller 2.0.0 the only thing was a permission related error in log.

```
host.iobrokertest | 2019-09-11 11:50:09.342 | error | Error: EACCES: permission denied, open '/opt/iobroker/node_modules/iobroker.js-controller/pids.txt'
-- | -- | -- | --
host.iobrokertest | 2019-09-11 11:50:09.342 | error | could not store process id list in /opt/iobroker/node_modules/iobroker.js-controller/pids.txt . Please check permissions and check left over processes when stopping ioBroker!
```
After fixing permissons with `chown -R 1000:1000 /opt/iobroker` the error was gone.
As I decided to let "iobroker_startup.sh" set permissions on every run in the future this is not a real issue for me....

Everything else worked fine. Including Adapter updates.

**Comment by Apollon77** [comment]
Cool Thanks!
