### ISSUE TITLE
Externe Devices im Docker-Container

### ISSUE THREAD

**Issue by xtolkien** [buanet/docker-iobroker#36]
Hallo,
meine IOB-Installation arbeitet mit einem Zigbee-Stick an der Synology. Das Device wird mit /dev/ttyACM0 an den Container durchgereicht. Das funktioniert soweit auch einwandfrei. Allerdings  hat das Device im Container die Owner-Zuordnung root:root und auch lediglich Lese-/Schreibrechte für den root-User. Damit kann in der User iobroker nicht auf dieses Device zugreifen. Das Problem kann natürlich dadurch behoben werden, dass ich dem Device auch Rechte für andere Benutzer gebe, allerdings ist dies nur eine temporäre Lösung bis zum nächsten Start des Containers.
Es wäre eine schöne Lösung, wenn die Möglichkeit bestehen würde, dem Container im Zuge des Startprozesses z.B. über Parameter entsprechende Devices mitgeben zu können, die dann dem User iobroker zugänglich gemacht würden. Damit würden hoffentlich keine zu großen Sicherheitsbedenken ausgelöst werden.

VG
Michael

**Comment by buanet** [comment]
Danke, ist jetzt mit auf der ToDo Liste.

MfG,
André

**Comment by buanet** [comment]
Hallo, 
habe eine neue Beta-Version (v4.0.1beta) bereit gestellt. In der ist es möglich eine Environment Variable "USBDEVICES" zu setzen (siehe readme.md). Wenn die Variable entsprechend gesetzt ist, dann werden die Berechtigungen automatisch gesetzt. Bitte mal testen und Rückmeldung geben. 
Danke.

MfG,
André

**Comment by xtolkien** [comment]
Hallo,
das scheint noch nicht zu funktionieren. Ich habe den Test mit Hilfe der Portier-Umgebung gemacht. Als zusätzlichen ENV-Parameter habe ich das Device eingetragen (/dev/ttyACM0), das ich auch unter der devices-Section zugefügt hatte. In der Konsole hat im Container aber lediglich der root-User Schreib-/Leserechte auf das Device.
Schau ich dann in die ENV-Variablen, so ist der Parameter USBDEVICES mit dem Inhalt 'none' belegt.
Im Log kann ich keinen Hinweis entdecken.

VG
Michael

**Comment by buanet** [comment]
Das ist ein bekannter Portainer Bug. Ich vermute mal du hast den Container über den "Duplicate/ Edit"-Button erstellt? Da gibt es Probleme mit dem Erstellen/ Ändern von Environment Variables. Man muss aktuell immer einen ganz neuen Container anlegen wenn man die Variablen anpassen will... Hoffe das wird bald gefixt...

MfG,
André

**Comment by xtolkien** [comment]
Genau, so habe ich es gemacht. Dann mache ich noch einen weiteren Test. Wird aber sicherlich nicht vor morgen klappen.

VG
Michael

**Comment by xtolkien** [comment]
Hallo,

ich habe es doch schon geschafft und es hat funktioniert. Es ist auch die Berechtigung für die Gruppe dialaut vergeben worden, deren Mitglied der User iobroker ja ist.

VG
Michael

**Comment by buanet** [comment]
Sehr gut, danke für die Rückmeldung.
