### ISSUE TITLE
Fehler beim reinstall.sh bei Adapter amazon-dash (v3.1.4beta)

### ISSUE THREAD

**Issue by RK62** [buanet/docker-iobroker#37]
Ich habe meine bestehende v2.0.0 Installation mit der V3.1.4beta im Hostmodus getestet.
Bein ersten Start sind bereits Fehlermeldungen erschienen, beim beim **reinstall.sh** ist dann folgender Fehler aufgetaucht:

```
[       ...........] - extract:iobroker.amazon-dash: verb lock using /root/.npm/_locks/staging-66d2468782e8ffc7.lock for /opt/iobrokernpm ERR! code 128
npm ERR! Command failed: git clone --mirror -q https://github.com/bytzdev/node-socketwatcher.git /root/.npm/_cacache/tmp/git-clone-71417e48/.git
npm ERR! fatal: Konnte führende Verzeichnisse von '/root/.npm/_cacache/tmp/git-clone-71417e48/.git' nicht erstellen.
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-24T18_59_27_203Z-debug.log
FAIL iobroker.amazon-dash

```
Aber das Thema amazon dash button ist ja eh ein Auslaufmodell wo ich mir eine andere Lösung einfallen lassen muss.

Gruß, Ralf

**Comment by buanet** [comment]
Hallo Ralf,
das beim ersten Start Fehlermeldungen kommen kann ich mir vorstellen, es sei denn du hast in v2 deine Node-Version hoch gezogen. :) reinstall.sh ist an dieser Stelle daher schonmal korrekt.... Ist denn das Script sonst durch gelaufen? Vielleicht hilft es ja den Adapter mal zu löschen und neu zu installieren. So wie ich die Fehlermeldung deute geht da irgendwas mit npm schief. Wie führst du das Script aus? unter welchem User?

Habe gerade mal in meiner Testumgebung den Adapter installiert. Lief durch und funktioniert auch... Schein also kein generelles Problem zu sein...

Was den Adapter selbst angeht, da wird aktuell wohl nicht so richtig arbeit rein gesteckt... Laut git seit 10 Monaten nichts passiert. So wie es aussieht wurde er auch noch nicht mir dem js-controller 2 getestet... 

MfG,
André

**Comment by RK62** [comment]
Habe jetzt nochmal folgendes probiert:
- Adapter komplett gelöscht
- Aus /iobroker-data/files ebenfalls entsprechendes Unterverzeichnis gelöscht
- Bibliotheken aufgefrischt: **sudo apt-get update**
- Benötigte Biblithek installiert: **sudo apt-get install libpcap-dev**
- Dann den Adapter via admin installiert und folgende Fehler erhalten (siehe auch [InstallLog.txt](https://github.com/buanet/docker-iobroker/files/3774796/InstallLog.txt)):
`
$ ./iobroker add amazon-dash  --host iobroker

NPM version: 6.12.0

npm install iobroker.amazon-dash@0.3.1 --unsafe-perm --production --save --prefix "/opt/iobroker" (System call)

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.





E: Sperrdatei /var/lib/dpkg/lock konnte nicht geöffnet werden. - open (13: Keine Berechtigung)E: Sperren des Administrationsverzeichnisses (/var/lib/dpkg/) nicht möglich, sind Sie root?



../socket_watcher.cpp: In static member function ‘static void SocketWatcher::Callback(uv_poll_t*, int, int)’:../socket_watcher.cpp:77:60: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]

   Nan::MakeCallback(watcher->handle(), callback, argc, argv);

                                                            
`

**Comment by buanet** [comment]
Hallo Ralf,
so recht weiß ich da gerade auch nicht was da schief läuft. Schaut ein bisschen nach Berechtigungsproblem aus...
Ich habe für meinen Test einen neuen Container gestartet, allerdings mit MACVLAN. Dann habe ich das benötigte libpcap installiert und über die Weboberfläche den Adapter. Das hat funktioniert...
Hast du mal versucht den Adapter als root über die Kommandozeile zu installieren? Sollte mit "iobroker add amazon-dash" funktionieren.

MfG,
André

**Comment by RK62** [comment]
Adapter als root installieren hat auch nicht geholfen :-(.
Ich werde wahnsinnig, was mache ich denn da anders als Du?
- Neuen v4.0.0 container via Synology erstellt, Host-Modus ausgewählt und Verzeichnis zugeordnet
- Container gestartet und Hochfahren abgewartet
- Auf der Console im Portainer: 
   - "root@z-iobroker-db:/opt/iobroker# apt-get update" -> Läuft durch
   - "root@z-iobroker1-db:/opt/iobroker# apt-get install libpcap-dev" ->Läuft durch
 - Im ioBroker-Admin dash-button installiert -> Es kommen Fehler, aber Exit Code 0
 - Start der Instanz und das Log ist rot (in der Anlage das Log vom Container) 
[iobroker.2019-10-27.log](https://github.com/buanet/docker-iobroker/files/3776115/iobroker.2019-10-27.log)

Gibst Du im Environment noch was spezielles mit?

Gruß, Ralf

**Comment by buanet** [comment]
Hallo Ralf,
das ist wirklich mehr als seltsam. Habe es gestern Abend mal eben auch mit dem Host-Modus getestet. So wie von dir beschrieben. Adapter installiert (Auch ich habe dort Fehler, aber am Ende Exit Code 0) und wird sofort grün. Keine Meldungen im Log.

Bei dir im Log sieht es aus, als ob der  Adapter ein Problem mit der pcap-session hat.
```
2019-10-27 17:13:19.058  - [31merror[39m: Caught by controller[0]: Error: socket: Operation not permitted
2019-10-27 17:13:19.058  - [31merror[39m: Caught by controller[0]:     at new PcapSession (/opt/iobroker/node_modules/iobroker.amazon-dash/node_modules/pcap/pcap.js:49:39)
```
Vielleicht fehlen da Berechtigungen. Du könntest die Berechtigungen für den ioBroker-Ordner vor dem Start des Adapters mal über die Kommandozeile nochmal neu setzen: 
 `chown -R iobroker:iobroker /opt/iobroker`
Nicht sicher ob das was bringt, aber das würde ich probieren. 

MfG,
André

**Comment by RK62** [comment]
Habe jetzt alles mögliche ausprobiert, ich gebe auf :-( 
Der chown hat leider auch nichts gebracht. Verstehen tue ich das nicht, die Container auf unseren Maschinen sind ja identisch, da kann es ja eigentlich nur an der Synology oder deren Einstellungen liegen. Ich werde also vor dem Update auf die v4 die dash-buttons durch Alexa-Befehle ersetzen müssen.

Danke für Deine Mühe!

Gruß, Ralf

**Comment by buanet** [comment]
Hallo Ralf,
ich habe gestern meine Produktiv-Umgebung auf Node 10 umgestellt und bin dabei nochmal über den amazon-dash-Adapter gestolpert. Du könntest nochmal folgendes ausprobieren. 
Setze mal beim Erstellen des Containers unter "Advanced container settings" > "Capabilities" die Schalter für "NET_ADMIN" und "NET_RAW". 
Wenn der Container dann läuft führe auf der Kommandozeile als root folgendes aus: 
`setcap 'cap_net_raw,cap_net_admin+eip' $(readlink -f $(which node))`
Danach sollte der Adapter eigentlich laufen...

**Comment by RK62** [comment]
Du gibst wohl nie auf, Respekt!

- Container mit Synology erstellt mit Host-Modus und ohne externes Datenverzeichnis
- Danach Container mit Portainer geändert und NET_ADMIN eingeschaltet (NET_RAW war schon an)
- Als root
   - apt-get update
   - apt-get install libpcap-dev

Dann Dein Kommando hinterher geschoben:
```
root@z-iobroker-v4:/opt/iobroker# setcap 'cap_net_raw,cap_net_admin+eip' $(readlink -f $(which node))
Failed to set capabilities on file `/usr/bin/node' (Operation not supported)
The value of the capability argument is not permitted for a file. Or the file is not a regular (non-symlink) file
```
Was habe ich jetzt wieder falsch gemacht?

Gruß, Ralf

**Comment by buanet** [comment]
Hmm, bei mir klappte das...
Spuckt google was dazu aus? 
Der Befehl selbst soll eigentlich die Capabilities für node netzen...

MfG,
André

**Comment by RK62** [comment]
Hatte ich auch schon mal im Forum gepostet:
https://forum.iobroker.net/topic/4733/howto-anleitung-installation-iobroker-in-docker-auf-synology-diskstation/947

Google liefert 2 Links die mich auch überfordern ;-)
- https://serverfault.com/questions/665709/allowing-node-js-applications-to-run-on-port-80
- https://serverfault.com/questions/801037/allowing-node-js-applications-to-run-libpcap-without-sudo-symlink-issue

Eigentlich kann sich das doch in unseren Containern gar nicht unterschiedlich verhalten?!
Hast Du eine Step-by-step Anleitung wie Du den Container aufbaust?
Oder soll ich Dir mal zusenden wie ich das mache?

Gruß, Ralf

**Comment by buanet** [comment]
Eigentlich sollte es sich nicht unterscheiden... 

Du könntest mal schauen was bei dir ein `which node`ergibt. Dann den Pfad mal mit `ls -la /pfad/zu/node`mal prüfen ob es sich um einen Symlink handelt.

So sieht das bei mir aus
```
root@iobrokertest:/opt/iobroker# which node
/usr/bin/node
root@iobrokertest:/opt/iobroker# ls -la /usr/bin/node
-rwxr-xr-x 1 root root 41108720 Okt 22 18:54 /usr/bin/node
```
Ergebnis kein Symlink, sonst würde am Ende noch der Verweis stehen auf den die Datei verlinkt.

Außerdem kannst du mal prüfen ob du das Paket `libcap2-bin` im Container installiert hast und ggf. nachinstallieren.

MfG,
André

**Comment by RK62** [comment]
Sieht alles genauso aus. 
Paket `libcap2-bin` habe ich sicherheitshalber auch nochmal installiert, war aber schon drauf. 
Trotzdem erscheint die Fehlermeldung beim **setcap**.

**getcap** funktioniert auch nicht:
`root@z-iobroker-v4:/opt/iobroker# getcap /usr/bin/node`
**Failed to get capabilities of file `/usr/bin/node' (Operation not supported)**

Gruß, Ralf

**Comment by buanet** [comment]
Hallo Ralf,
hast du hierzu noch was herausfinden können? Ich komm leider nicht dahinter was da das Problem ist.

**Comment by RK62** [comment]
Hallo André,
nein, ich habe das auch nicht ans Laufen bekommen. Da es die DashButtons ja eh nicht mehr gibt, habe ich die Gelegenheit genutzt und in der V4.0.0 alles auf den alexa-Adapter umgestellt. Die Familie ist zufrieden bis begeistert, habe das Ticket geschlossen.
Danke für Deine Unterstützung.

Gruß, Ralf
