### ISSUE TITLE
Anmeldung am iobroker.web nicht mehr möglich (v3.1.4beta)

### ISSUE THREAD

**Issue by RK62** [buanet/docker-iobroker#38]
Ich habe meine bestehende v2.0.0 Installation mit der V3.1.4beta im Hostmodus getestet.

Danach war keine Anmeldung mehr am iobroker.web möglich.
Das betrifft nur web-Instanzen bei denen die _Authentifikation_ aktiviert ist.
Kennwort im User ändern hilft auch nicht, bei einem neu angelegten User funktioniert die Anmeldung dann. 

Gruß, Ralf

**Comment by buanet** [comment]
Hallo Ralf,
hast du mal bei den Issues vom iobroker.web geschaut? Meine erst kürzlich so etwas (ähnliches) in meinen Mails gelesen zu haben. Zumindest gab es Issues zum Thema Authentifikation.
Hast du die aktuelle Version vom Web installiert? 

Welche Versionen hast du denn jetzt überhaupt laufen? Node? npm? js-controller? Web-Adapter?

MfG,
André

**Comment by RK62** [comment]
Guter Hinweis, es liegt am web adapter.
Habe dort einen enstprechenden Isue aufgemacht: https://github.com/ioBroker/ioBroker.web/issues/33

Da die Adapter beim _reinstall.sh_ aber alle auf den aktuellen Stand gebracht werden muss ich mit dem Update wohl bis zur Behebung warten  :-(  Oder nach Update ein Downgrade auf die V2.4.6 fahren.

Danke, Ralf
