### ISSUE TITLE
TLS ciphers broken with ioBroker.email

### ISSUE THREAD

**Issue by jpawlowski** [buanet/docker-iobroker#40]
Not sure this might be related to the Docker environment, just wanted to double check here as I am not a Node.js expert:

https://github.com/iobroker-community-adapters/ioBroker.email/issues/17

> It seems that supported TLS ciphers are incomplete/outdated. After STARTTLS, the connector is unable to find a common cipher suite:
> 
> ````shell
> Error 140486513518400:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s23_clnt.c:802:
> ````
> 
> I am using https://github.com/buanet/docker-iobroker Docker image, not sure if this is related to outdated Node environment (as I am not a Node expert).
> 
> This is what the mailserver actually offers:
> 
> ```shell
> # for v in ssl2 ssl3 tls1 tls1_1 tls1_2; do
> #  for c in $(openssl ciphers 'ALL:eNULL' | tr ':' ' '); do
> #  openssl s_client -connect 1.2.3.4:25 -starttls smtp \
> #  -cipher $c -$v <<< "Q" > /dev/null 2>&1 && echo -e "$v:\t$c"
> #  done
> # done
> 
> tls1:	ECDHE-ECDSA-AES256-SHA
> tls1:	ECDHE-ECDSA-AES128-SHA
> tls1:	ECDHE-ECDSA-DES-CBC3-SHA
> tls1_1:	ECDHE-ECDSA-AES256-SHA
> tls1_1:	ECDHE-ECDSA-AES128-SHA
> tls1_1:	ECDHE-ECDSA-DES-CBC3-SHA
> tls1_2:	ECDHE-ECDSA-AES256-GCM-SHA384
> tls1_2:	ECDHE-ECDSA-AES256-SHA384
> tls1_2:	ECDHE-ECDSA-AES256-SHA
> tls1_2:	ECDHE-ECDSA-AES128-GCM-SHA256
> tls1_2:	ECDHE-ECDSA-AES128-SHA256
> tls1_2:	ECDHE-ECDSA-AES128-SHA
> tls1_2:	ECDHE-ECDSA-DES-CBC3-SHA
> ```
> 
> Any other cipher suites are disabled for security reasons (which is quite common I believe).

**Comment by buanet** [comment]
To be continued at iobroker-community-adapters/ioBroker.email#17.

Regards,
André.
