### ISSUE TITLE
Node.js 12.x being LTS

### ISSUE THREAD

**Issue by jpawlowski** [buanet/docker-iobroker#41]
A couple of days ago, it was the expected change from Node.js v10.x to v12.x being the recommended LTS version. Ideally the Docker image v4 would actually skip v10.x and would directly move to the 12.x branch.

**Comment by Apollon77** [comment]
I would not support that! While iobroker supports nodejs 12 basically the e tree commended Version is still nodejs 10 because some adapters are still not ready for nodejs 12 because of incompatible deps ... so I would not support that for an official Container Version.

**Comment by jpawlowski** [comment]
It is just a hint/suggestion, no need to use any exclamation marks ;-)

**Comment by buanet** [comment]
No. As I know node10 is recommended at the moment. 
If you name me an adapter requiring node12 I will build a beta including node12 for testing... 

Regards,
André
