### ISSUE TITLE
Clean shutdown state / return code 137

### ISSUE THREAD

**Issue by jpawlowski** [buanet/docker-iobroker#42]
It seems that the current concept of the container does not handle process signalling in a way that will lead to a clean shutdown of the ioBroker processes.

If you shutdown the container, the process will not return with exit code 0 but exit code 137:
![image](https://user-images.githubusercontent.com/75446/67620561-8ec1c080-f808-11e9-87ed-6018c8d927bc.png)

This might be an indicator that ioBroker was not shut down cleanly and therefore it might very well happen that and pre-shutdown activities will not be carried out properly.

Also see https://success.docker.com/article/what-causes-a-container-to-exit-with-code-137

@JoschaMiddendorf was actually developing something very handy for the FHEM Docker container boot handling: https://github.com/fhem/fhem-docker/blob/ab1eff2bb93b00b0571f26125bcd924c0f4c3a68/src/entry.sh#L615-L661

If there is a wish for support, I might be able to spend a few hours to make some contributions to the ioBroker Docker image, based on lessons learned we had.

**Comment by buanet** [comment]
I've been working that way for more than 2 years now. My Backup-Script "kills" the Container every Monday for weekly complete Backup. I have never had any shutdown related problem.
If you have any suggestions how to pimp container shutdown, please let me know.
At this point, I don't know if and how it might be possible to let Docker daemon wait for a successful iobroker shutdown...

Regards,
André

**Comment by DummerJunge** [comment]
The container does not answer or stops gracefully on a SIGTERM. 

This lead e.g. to problems with watchtower: This normally terminates container with SIGTERM. For this Container the label com.centurylinklabs.watchtower.stop-signal=SIGHUP is for me necessary. 

Even if someone using watchtower naturally can start container manually and adding the label there. I believe adding this label to the dockerfile an good idea.

**Comment by buanet** [comment]
Please see https://github.com/buanet/docker-iobroker/tree/beta#changelog.
Container should handle SIGTERM now (v4.2.4beta) and gracefully shutdown iobroker for exit code 0.

@DummerJunge If you still need a special label please add the label on container startup.

Regards,
André
