### ISSUE TITLE
Add vim to default setup

### ISSUE THREAD

**Issue by jpawlowski** [buanet/docker-iobroker#43]
Would it be possible to add vim to the set of packages that come with the image itself?
I know there is this environment variable to add packages during boot-up. It just feels very weird that a tool that's standard since decades is not part of the image directly.

**Comment by buanet** [comment]
As everybody has his own favorite editor (for me it is nano), I will not add vim to the image. Please use ENV "PACKAGES".

Regards,
André

**Comment by jpawlowski** [comment]
It’s not about favorites, it’s about standards everyone knows that it’s always there 🙄

**Comment by buanet** [comment]
Please reference the standards you are talking about. Official Debian Wiki gives no hint about "standard editors" in Debian (https://wiki.debian.org/TextEditor).
Furthermore the image (amd64) is based on the official Debian Docker image (https://hub.docker.com/_/debian) which includes no standard editor. 

Regards,
André

**Comment by jpawlowski** [comment]
It is no ISO standard, it is what people are used to as a minimum editor on every system that is intended for interactive login. A minimum baseline Debian Docker image is usually not intended for interactive login. Also, this image is not designed for immediate use - it is a basis to create actual images
However, ioBroker is one of many cases where you would regularly login in interactive mode to run commands and change files.

First thing you expect to be there on any unknown system is VIM - it is simply one of the oldest editors for *Unix. I know there are quite many semi-professionals who don't like to use VIM because of it's very special way of use. But this is also exactly why this lightweight editor is there for over 3 decades and it is the de-facto fallback editor you always expect to be there if nothing else is installed. nano for sure is not the first editor a professional would expect to open in the first place (that is, because it is simply not installed on so many servers while VIM is).

Anyway - if the intention of this image is a ready-to-use philosophy either it should include VIM, or it is imply not ready to use without immediate customisation (which I personally find to be odd - but maybe that's just me having too high expectations...).

**Comment by Apollon77** [comment]
The Unix standard is “vi” ;-) Debian decided to stay with vi as default. Ubuntu for instance uses vim ... but so it is based on the basic distribution... and here we have Debian as Basis. So I understand the position here.

**Comment by jpawlowski** [comment]
Call it VIM or "vi", it is meant to be the same thing ;)

**Comment by Apollon77** [comment]
Nooooooo vi is original and also available on nearly all other Unix derivates (As/400 and such). Vim is the “better vi” with more easy usage and compatible in usage. But much enhanced, and therefor often used as alias. ;-)

Unix has a veeeeeery long history ;-)

**Comment by jpawlowski** [comment]
I know, I'm quite (and almost) old :-p
At the end of the day, any of those two variants will do for just "bare metal" editing

**Comment by buanet** [comment]
Ok.
My point is still that a text editor is not necessary for successfully setting up and running the container. For most users I see no use case for editing files directly.
For example: Things like modifying iobroker.json work via command line ("iobroker setup custom")...

As I try to keep the image as slim as possible I will not add an editor package or any other "standard" tool directly to the image.  Only packages needed for a clean and successful installation and first start of an iobroker container will be installed by default.
All additional packages can be defined by the use of the env "PACKAGES" or should be installed manually when they are needed. 

BUT: As I defined a "standard value" for env "PACKAGES" in the dockerfile I will set this to "vi".

Regards,
André

**Comment by jpawlowski** [comment]
Thanks! It is not about editing but also about viewing and browsing through file content.
