### ISSUE TITLE
Fix homedir for system user 'iobroker'

### ISSUE THREAD

**Issue by jpawlowski** [buanet/docker-iobroker#44]
Related to [this](https://github.com/SebastianSchultz/ioBroker.lgtv/issues/52) issue, I suggest to fix/change the iobroker users' home directory. E.g., the home directory should be `/opt/iobroker` instead of `/home/iobroker`.

**Comment by buanet** [comment]
Sounds useful. Will be included in beta soon.

747edf9 Row 69.

Regards, 
André
