### ISSUE TITLE
Probleme mit Radar2 Adapter

### ISSUE THREAD

**Issue by Uwe1984** [buanet/docker-iobroker#45]
Hallo, 

ich habe Probleme den Radar2 Adapter lauffähig zu machen. 
Laut Installationsanleitung des Adapterentwicklers muss folgendes auf dem System ausgeführt werden:
![image](https://user-images.githubusercontent.com/45272859/68051934-d6ed5100-fce8-11e9-8f13-a1edc38b93f3.png)

Wenn ich das im Container ausführe, funktioniert er nicht mehr nach einem Neustart z.B. System reboot. 
Im Log steht etwas von "exec Befehl nicht ausführbar", oder ähnliches. 
Außerdem ist diese Änderung nur solange Verfügbar wie ich diese Version des Containers nutze. Aktuell bin ich auf v4.0.0. 

Ich verstehe leider nicht wie ich die Installationsanleitung des Radar2 Adapters im Container dauerhaft zum laufen bekomme. 
Ich nutze docker-compose und könnte eventuell environments definieren. Nur welche sind hier die richtigen. 

Bitte um Hilfe.

**Comment by buanet** [comment]
Hallo,
bitte bei Konfigurationsproblemen zuerst im Forum suchen/ fragen. Im Forum Threat wurde das setcap-Thema bereits besprochen. Einfach mal nach "setcap" im Thema suchen.
Hier müssen sogenannte "Capabilities" beim Aufsetzen des Containers gesetzt werden. Dann sollte das auch klappen.

MfG,
André
