### ISSUE TITLE
Hostname

### ISSUE THREAD

**Issue by mc-0815** [buanet/docker-iobroker#48]
Hi,

warum wird via Startskript beim ersten Starten eines Containers der Hostname auf den beim Docker Build erzeugten Hostnamen gesetzt und nicht auf den aktuellen Hostnamen des laufenden Containers? Letzteres wäre für mich logischer oder übersehe ich da etwas?

**Comment by buanet** [comment]
Hallo,
da übersiehst du etwas. :) Ich hatte da Anfang des Jahres auch eine Diskussion zu, bis ich es verstanden habe. Letztendlich wird mit dem Aufruf `iobroker host [hostnamebuild]` im Script der Hostname aus dem Build, der zu diesem Zeitpunkt ja in den Adaptern hinterlegt ist, mit dem aktuellen Hostname (aus dem laufenden Container) ersetzt.
Bedeutet: Der Befehl gibt nicht den neuen Hostname mit sondern erwartet als Eingabe den Hostname der in den Adaptern ersetzt werden soll...

Falls du dazu Lesestoff benötigst, wirf mal einen Blick hier rein:
https://github.com/ioBroker/ioBroker.js-controller/issues/286#issuecomment-453050070

MfG,
André

**Comment by mc-0815** [comment]
Danke, bin 5 Minuten vor deiner Mail genau über den Thread vom Anfang des Jahres gestolpert und habe meine fehlerhafte Interpretation des Kommandos bemerkt.

Grüße
