### ISSUE TITLE
Versionsnummer

### ISSUE THREAD

**Issue by schmupu** [buanet/docker-iobroker#5]
Hallo,

wenn ich den ioBroker Docker Image mit der Synology herunterlade wird mir nur die Version 1.0.1. und 1.1.0 aber nicht die Stable Version 1.1.2 angeboten. Ist es möglich die anderen Versionen auch anzubieten und nicht nur als latest Version zur Verfügung zu stellen?
Wenn ich latest Version nutze kann ich den Container nicht updaten wenn dieser in einem laufendem Container in Benutzung ist. Außerdem ist dann nicht auf Anhieb die Version sichtbar.

Gruß
Stübi

**Comment by buanet** [comment]
Hallo Stübi,
das ist auch korrekt so. Aktuelle "latest" Stable-Version ist 1.1.0. Bei der 1.1.2 handelt es sich (noch) um "beta".
Unterschied zwischen 1.1.0 und "latest" ist übrigens das Build-Datum des Images. Während "latest" jede Nacht einmal durch läuft und immer die aktuellen Linux-Pakete beinhalten sollte, handelt es sich bei 1.1.0 um den Stand vom Releasedatum (den ich getestet habe und der definitiv funktionieren sollte).
Wer die letzten Änderungen aus 1.1.2 haben möchte muss "beta" laden. Mit Version 1.2.0 wird es dann wieder ein neues "Stable-Release" geben.

MfG,
André
