### ISSUE TITLE
iobroker stop funktioniert nicht in 4.0.0?

### ISSUE THREAD

**Issue by Omega236** [buanet/docker-iobroker#52]
Hallo, 
habe heute auf 4.0.0 upgegraded. in diesem Zug wollte ich auch den Upgrade auf JS 2.1 machen.

aber ich schaffe es nicht den IOBroker zu beenden.
was mach ich falsch?
`
root@IoBrokerNAS:/opt/iobroker# iobroker stop
iobroker controller daemon is not running
root@IoBrokerNAS:/opt/iobroker# iobroker status
iobroker is running

Objects type: file
States  type: file
`

**Comment by buanet** [comment]
Hallo,
im Container läuft kein iobroker Daemon. Daher ist auch kein "iobroker stop" möglich. Bitte verwende stattdessen "pkill io". Siege dazu auch https://buanet.de/tutorials.

MfG,
André

**Comment by AxelRHD** [comment]
Hallo buanet,

ich versuche gerade die Einrichtung von redis mit iobroker in einem docker-compose Netzwerk. Ich habe es folgendermaßen versucht:

`docker-compose exec iobroker pkill io`

`docker-compose exec iobroker setup custom`

```
Type of objects DB [(f)ile, (r)edis], default [file]:
Host / Unix Socket of objects DB(file), default[0.0.0.0]:
Port of objects DB(file), default[9001]:
Type of states DB [(f)file, (r)edis], default [file]: r

When States are stored in a Redis database please make sure to configure Redis
persistence to make sure a Redis problem will not cause data loss!

Host / Unix Socket of states DB (redis), default[0.0.0.0]: redis
Port of states DB (redis), default[6379]:
Host name of this machine [iobroker]:
This host appears to be a Master or a Single host system. Is this correct? [Y/n]:

Do you want to migrate objects and states from "file/file" to "file/redis" [y/N]: y
Connecting to previous DB "file"...

Cannot migrate DB while js-controller is still running!
Please stop ioBroker and try again. No settings have been changed.
```

Irgendwie komme ich da nicht weiter. Scheinbar startet sich io innerhalb des Containers gleich wieder selbst? Deine Internetseite ist derzeit leider nicht erreichbar.

Vielen Dank schon mal für die Hilfe.

**Comment by buanet** [comment]
Hallo, falls es noch aktuell ist, die Website ist wieder online.

https://smarthome.buanet.de

MfG,
André

**Comment by AxelRHD** [comment]
Vielen Dank für die Rückmeldung André.

Ich hatte gerade mit ioBroker begonnen und meine Installation dann sowieso noch mal auf einen Odroid-C4 umgezogen. Ich habe dort die Umgebungsvariablen für Redis (übrigens danke für die klasse Dokumentation auch auf Docker-Hub) in Docker-Compose verwendet. So waren zwar manuell angelegte States weg, aber damit konnte ich zu diesem Zeitpunkt noch leben.

Die Frage, wie man innerhalb des Docker Containers zwischen File-basierter States-DB und Redis wechseln kann (ohne Datenverlust selbstverständlich) bleibt damit aber weiterhin noch offen. Ist vielleicht auch für andere Anwender interessant.

**Comment by buanet** [comment]
> Die Frage, wie man innerhalb des Docker Containers zwischen File-basierter States-DB und Redis wechseln kann (ohne Datenverlust selbstverständlich) bleibt damit aber weiterhin noch offen. Ist vielleicht auch für andere Anwender interessant.

Ich glaube das geht nicht so einfach. Ist aber kein Docker spezifisches Thema. Ist vielleicht mal eine Frage fürs ioBroker Forum. 

MfG,
André
