### ISSUE TITLE
Login mit "Angemeldet bleiben" nicht möglich

### ISSUE THREAD

**Issue by davincino** [buanet/docker-iobroker#54]
Hallo,
habe kürzlich das Image v4.0 (tag: latest) installiert.
Bereits mit der Grundinstallation ist es nicht möglich angemeldet zu bleiben. Sobald der Haken gesetzt wird, ist ein Login nicht möglich. Es werden keine Fehler auf der Login Seite angezeigt.

Reproduzieren des Fehlerbildes:
- Docker Container starten
- ip:8081 aufrufen und Lizenzbestimmungen akzeptieren
- Benutzer Passwort für User admin setzen
- Authentifizierung unter admin.0 aktivieren

Login mit "angemeldet bleiben" nicht möglich

**Comment by buanet** [comment]
Klingt für mich nicht nach einem Problem des Containers. Ist wohl eher ein ioBroker-Admin-Problem. 
Hast du vielleicht noch mehr Infos? Hast du das hier gesehen? 

https://github.com/ioBroker/ioBroker.admin/issues/467

Vielleicht solltest du dich dort dran hängen.

MfG,
André

**Comment by davincino** [comment]
Ok, hast Recht. Hatte vorher beim WEB Adapter auf github geschaut und nichts bzgl der Anmeldung gefunden. Direkt beim Admin Adapter schauen, daran hatte ich nicht gedacht. 

Danke
