### ISSUE TITLE
Paket "udev" wird für COM-Ports bzw. virtuelle COM-Ports benötigt

### ISSUE THREAD

**Issue by tobimai** [buanet/docker-iobroker#55]
Ich hab einen USB-RS485 converter um einen Stromzähler auszulesen, allerdings erkennt der Modbus-Adapter die serielle Schnittstelle nicht, solange "udev" nicht installiert ist. 

Spricht irgendwas dagegen, das Paket im Container mitzuinstallieren? 
Ist vermutlich ein ziemlicher Nischen-Fall, aber negative Auswirkungen sollte es nicht haben.

**Comment by fzzybllz** [comment]
Die Frage nach udev gab es schon einmal. Schreib es einfach in die ENV variable 'packages' mit rein und deploy deinen container neu, dann wird es beim Start automatisch installiert.

**Comment by buanet** [comment]
Entweder das oder du schaust mal in die aktuelle beta. Das ist es schon mit drin.

MfG,
André
