### ISSUE TITLE
Neue "Latest" Version

### ISSUE THREAD

**Issue by gaudes** [buanet/docker-iobroker#58]
Hi Buanet,

wusste keinen besseren Kontaktweg :)

Willst Du vielleicht mal wieder eine "Latest"-Version schieben ? Die Änderung z.B. mit USBDEVICES und ZWAVE sind ja noch Beta ...

Danke und Gruss Ralf

**Comment by buanet** [comment]
Hallo Ralf,
was genau spricht dagegen die Beta zu nutzen (und mir gerne Rückmeldung bei Problemen zu geben)? 
Aktuell bekomme ich relativ wenig Rückmeldungen von Leuten die die Beta testen. Vielleicht ist das ein gutes Zeichen, vielleicht testet aber auch gar niemand. :) Ich weiß es schlicht nicht.
Und zum selbst testen war über die Feiertage einfach nicht genug Zeit...
Mein aktueller Plan sieht aber vor den offenen Pull Request noch in eine neue Beta zu bringen und dann, vermutlich Ende Januar, das Ganze als 4.1 zu bringen.

MfG,
André
