### ISSUE TITLE
Falsches Format bei Neuanlage leerer Ordner

### ISSUE THREAD

**Issue by Baenker** [buanet/docker-iobroker#59]
Hallo,

ich habe ein Problem und zwar möchte ich von V2 auf V4 wechseln aber mal als Cleanisnstall. Also nur leerer Ordner und den Docker Container auf dem Synology gestartet. Betrieb als Host (gleiche IP wie Synology). Language und Lang usw ist ja mittlerweile vorbelegt, so dass ich nur noch einen leeren Ordner anlegen musste. Kurz nach dem Start ist ioBroker auch erreichbar und man muss ein paar Kleinigkeiten einstellen. Danach habe ich den javascript Adapter installiert und ein Script ausgeführt:

Das Ergebnis im Log unterscheidet sich doch etwas von der alten Version.

Vorher V2:

javascript.0	2020-01-04 11:48:14.043	info	script.js.Test.Test_Zeit: dawn de-DE: 07:52:17
javascript.0	2020-01-04 11:48:14.043	info	script.js.Test.Test_Zeit: dawn en-US: 7:52:17 AM
javascript.0	2020-01-04 11:48:14.043	info	script.js.Test.Test_Zeit: dawn ohne: 07:52:17

Mit V4:
javascript.0	2020-01-04 12:03:08.446	info	(831) script.js.common.Skript_1: dawn de-DE: 7:52:17 AM
javascript.0	2020-01-04 12:03:08.446	info	(831) script.js.common.Skript_1: dawn en-US: 7:52:17 AM
javascript.0	2020-01-04 12:03:08.446	info	(831) script.js.common.Skript_1: dawn ohne: 7:52:17 AM

Das heißt er nutze immer das US-Format mit am und pm!? Kann man das irgendwie einstellen?

Hier mein Testscript:

   
function func_Test(){
var date_aktuelle_Uhrzeit = getDateObject(formatDate(new Date(), "hh:mm:ss")).getTime();
var date_aktuelle_Uhrzeit_ = getDateObject(formatDate(new Date(), "hh:mm:ss"));
var aktuelles_Datum = new Date();
var format_aktuelles_Datum = formatDate(new Date(), 'DD-MM-YYY hh:mm:ss'); 

if(compareTime("sunset", "22:00", "between")){
log('Innerhalb sunset und 22:00 Uhr');
}
else{
    log('außerhalb sunset und 22:00')
}
 
let dawn = getAstroDate("dawn").toLocaleTimeString();
let dawn1 = getAstroDate("dawn").toLocaleTimeString('en-US');
let dawn2 = getAstroDate("dawn").toLocaleTimeString('de-DE');
log('dawn ohne: ' +dawn);
log('dawn en-US: ' +dawn1);
log('dawn de-DE: ' +dawn2);
log('aktulles Datum newDate(): ' +aktuelles_Datum);
log('aktulles Datum format: ' +format_aktuelles_Datum);
           
        if(date_aktuelle_Uhrzeit_ > getDateObject('22:00:00') && date_aktuelle_Uhrzeit_ < getDateObject('08:00:00')){
            log('Zwichen 22:00 und 08:00 Uhr');
        }
        else{
            log('Nach 8:00 Uhr aber vor 22:00 Uhr');
        }
    
}

func_Test();

**Comment by buanet** [comment]
Hallo,
bitte beim nächsten Mal etwas recherchieren. Mehr habe ich jetzt auch nicht getan...
Google hat jedenfalls gesagt ich soll mal folgendes ausprobieren: 
`let dawn2 = getAstroDate("dawn").toLocaleTimeString('de-DE', { hour12: false });`
Dann passt es jedenfalls für deutsch. 

Dann habe ich noch das hier gefunden:
https://github.com/ioBroker/ioBroker.javascript/issues/390

Sieht aus als sei es ein Node-Thema. Workaround siehe oben....

MfG,
André

**Comment by Baenker** [comment]
Vielen Dank für die Hilfe. Ich habe gesucht ohne Ende nur leider keine Lösung gefunden.  Und so eine richtige Lösung ist das ja auch nicht, da hier nur die Ausgabe verändert wird. Scheint dann aber wohl an Node zu liegen und nicht am Docker Container.

Ich werde nächste Woche einen weiteren Versuch zum Update probieren.
