### ISSUE TITLE
Apple Homekit / Adapter yahka / avahi wird nicht gestartet

### ISSUE THREAD

**Issue by schmupu** [buanet/docker-iobroker#6]
Hallo,

Wenn ich dann avahi starte gibt es ein chroot() Fehler. Dann muss folgender Eintrag in der /etc/avahi/avahi-daemon.conf  vorgenommen werden:
```

domain-name=local
use-ipv4=yes
use-ipv6=yes
enable-dbus=yes
#rlimit-nproc = 3     # auskommentiern
```

Damit ich die Webcam in Apple Home einbinden kann muss noch folgendes Paket installiert werden.
```
apt-get -f -y  install ffmpeg  # für Cam Anbindung
```

Ist es möglich einem späteren Release das Paket zu berücksichtigen und den Eintrag /etc/avahi/avahi-daemon.conf vorzunehmen?

**Comment by buanet** [comment]
Hallo Stübi,

wenn ich das recht sehe, dann tritt der chroot()-Fehler nur auf wenn man mehrere Docker Container mit Avahi laufen hat? Eigentlich ja nicht so Standard... Soweit ich das recherchieren konnte, sollte aber das Deaktivieren des rlimit keine negativen Auswirkungen haben. Ich werde das mal mit rein nehmen. 

Was das Paket ffmpeg angeht, das werde ich wohl nicht im Image mit aufnehmen. Oder gibt es einen konkreten Adapter der dies erfordert? Weder beim yahka- noch beim HomeKit-Adapter habe ich einen entsprechenden Hinweis finden können. Vielleicht kannst du noch ein bisschen konkreter werden was es damit auf sich hat. 

MfG,
André

**Comment by buanet** [comment]
Ok, da brauch ich nochmal Nachhilfe, Was ist genau das Problem mit dem Avahi?
Soweit ich das sehe, habe ich bereits im Dezember einen Fix gemacht. Dabei wurder der "rlimit-nproc = 3" auskommentiert (und ist es in meinem Container auch)....

MfG,
André

**Comment by buanet** [comment]
Ok, habe lange überlegt, aber das ffmpeg-package jetzt doch aufgenommen. :) Ganz schön groß das Ding... Nunja, da ich im Dockerimage aber nach Möglichkeit alle Adapter voll unterstützen möchte (um es für den Anwender möglichst einfach zu halten) führt wohl kein Weg dran vorbei. Den Build des Images habe ich gerade angestoßen. Die Änderungen sollten dann in wenigen Minuten im Beta enthalten sein. Wenn ich den Build erfolgreich getestet habe, mache ich ein stable draus....

MfG,
André

**Comment by schmupu** [comment]
Super, wenn Du möchtest  kann ich es auch gerne testen?
