### ISSUE TITLE
js-controller is outdated

### ISSUE THREAD

**Issue by Kartax** [buanet/docker-iobroker#60]
Some of my adapters require a newer version of js-controller and iobroker itself is stating
> Your host (js-controller) is outdated!  1.5.14  =>  2.1.1

I am currently on **4.0.2beta**.

Do you have any plans on updating soon?
Or do you suggest to manually do it inside my container as a temporary "solution"?

**Comment by buanet** [comment]
As js-controller is located in /opt/iobroker it is not maintained within the docker image!
You have to update js-controller manually like you always do with your adapters...
This is not a temporary "solution"!
When you set up a new Container with an empty /opt/iobroker folder you will automatically get the newest version of js-controller (the version officially shipped within iobroker-setup)...

Regards,
André
