### ISSUE TITLE
[v4.0.3beta] Zeile 169/192 Einstelliger (unärer) Operator erwartet

### ISSUE THREAD

**Issue by trxit** [buanet/docker-iobroker#64]
Hi zusammen,

wenn ich versuche das Docker Image (Version 4.0.3beta) zu starte, erscheint immer der Fehler "/opt/scripts/iobroker_startup.sh: Zeile 192: [: 8081: Einstelliger (unärer) Operator erwartet."

Kompletter Output:

> iobroker_1  | ------------------------------------------------------------
> iobroker_1  | -----         Step 1 of 5: Preparing container         -----
> iobroker_1  | ------------------------------------------------------------
> iobroker_1  |  
> iobroker_1  | Installing additional packages is set by ENV.
> iobroker_1  | The following packages will be installed: nano...
> iobroker_1  | Done.
> iobroker_1  |  
> iobroker_1  | There are no changes in UID/ GID needed.
> iobroker_1  |  
> iobroker_1  | ------------------------------------------------------------
> iobroker_1  | -----   Step 2 of 5: Detecting ioBroker installation   -----
> iobroker_1  | ------------------------------------------------------------
> iobroker_1  |  
> iobroker_1  | Existing installation of ioBroker detected in /opt/iobroker.
> iobroker_1  |  
> iobroker_1  | ------------------------------------------------------------
> iobroker_1  | -----   Step 3 of 5: Checking ioBroker installation    -----
> iobroker_1  | ------------------------------------------------------------
> iobroker_1  |  
> iobroker_1  | (Re)Setting folder permissions (This might take a while! Please be patient!)...
> iobroker_1  | Done.
> iobroker_1  |  
> iobroker_1  | Fixing "sudo-bug" by replacing sudo in iobroker with gosu...
> iobroker_1  | Done.
> iobroker_1  |  
> iobroker_1  | /opt/scripts/iobroker_startup.sh: Zeile 169: [: !=: Einstelliger (unärer) Operator erwartet.
> iobroker_1  | ------------------------------------------------------------
> iobroker_1  | -----      Step 4 of 5: Applying special settings      -----
> iobroker_1  | ------------------------------------------------------------
> iobroker_1  |  
> iobroker_1  | Some adapters have special requirements/ settings which can be activated by the use of environment variables.
> iobroker_1  | For more information take a look at readme.md on Github!
> iobroker_1  |  
> iobroker_1  | /opt/scripts/iobroker_startup.sh: Zeile 192: [: 8081: Einstelliger (unärer) Operator erwartet.
> iobroker_1  | ------------------------------------------------------------
> iobroker_1  | -----          Step 5 of 5: ioBroker startup           -----
> iobroker_1  | ------------------------------------------------------------
> iobroker_1  |  
> iobroker_1  | Starting ioBroker...
> iobroker_1  |  
> 

Jedoch ist auch kein iobroker gestartet. Kann mir jemand sagen, ob das nur bei mir passiert? Was mach ich falsch?

Danke und Grüße

**Comment by buanet** [comment]
Hallo,
leider fehlt der Kopf deines Logs :(
Hast du für den Adminport eine Umgebungsvariable angelegt? 

MfG,
André

**Comment by trxit** [comment]
Hi,

den Anfang habe ich weggelassen, da ich eigentlich alles nur als default benutze. Ich habe lediglich statt vi testweise nano angegeben, jedoch auch mit vi funktioniert es nicht.

Das wäre noch der Anfang:

> iobroker_1  |
> iobroker_1  | ------------------------------------------------------------
> iobroker_1  | ---------------     2020-01-10 09:11:58      ---------------
> iobroker_1  | ------------------------------------------------------------
> iobroker_1  |
> iobroker_1  | ------------------------------------------------------------
> iobroker_1  | -----       Welcome to your ioBroker-container!        -----
> iobroker_1  | -----          Startupscript is now running.           -----
> iobroker_1  | -----                Please be patient!                -----
> iobroker_1  | ------------------------------------------------------------
> iobroker_1  |
> iobroker_1  | ------------------------------------------------------------
> iobroker_1  | -----              Debugging information               -----
> iobroker_1  | -----                                                  -----
> iobroker_1  | -----                      System                      -----
> iobroker_1  | -----               arch:      x86_64                  -----
> iobroker_1  | -----                                                  -----
> iobroker_1  | -----                     Versions                     -----
> iobroker_1  | -----               image:     v4.0.3beta              -----
> iobroker_1  | -----               node:      v10.18.0                -----
> iobroker_1  | -----               npm:       6.13.4                  -----
> iobroker_1  | -----                                                  -----
> iobroker_1  | -----                       ENV                        -----
> iobroker_1  | -----               ADMINPORT: 8082                    -----
> iobroker_1  | -----               AVAHI:     false                   -----
> iobroker_1  | -----               PACKAGES:  nano                    -----
> iobroker_1  | -----               REDIS:     false                   -----
> iobroker_1  | -----               SETGID:    1000                    -----
> iobroker_1  | -----               SETUID:    1000                    -----
> iobroker_1  | -----               USBDEVICES: none                    -----
> iobroker_1  | -----               ZWAVE:     false                   -----
> iobroker_1  | ------------------------------------------------------------

VG

**Comment by buanet** [comment]
Sorry, ich weiß gerade nicht was ich davon halten soll... 

Warum änderst du bitte deine Logausgabe im Post?!?!? Beim Adminport stand erst 8082!

Dein Fehler bezieht sich im Startupscript auf den Teil, in dem der Adminport angepasst wird. Mit falschen Logdaten und damit falschen Annahmen kann ich mich zu Tode analysieren und werde unter Umständen den Fehler nie finden...

Wovon soll ich nun ausgehen? 

MfG,
André

**Comment by trxit** [comment]
Ich habe natürlich auch probiert die Ports zu ändern. Da das nicht funktioniert hat, habe ich wieder die Standardeinstellungen genutzt. Dummerweise hatte ich noch den alten Output kopiert - deshalb die Änderung

**Comment by Springjunky** [comment]
ADMINPORT sollte doch eigentlich gesetzt sein. Am besten auch noch das docker-compose bzw. die Docker-Parameter mitgeben.

**Comment by trxit** [comment]
Ich starte momentan einfach mit einer docker-compose File und dem Befehl _docker-compose up_:
```
version: '3'

services:
    iobroker:
        image: buanet/iobroker:v4.0.3beta
        ports:
            - "8081:8081"
        volumes:
            - ./iobroker:/opt/iobroker/
        networks:
            - code-network
networks:
    code-network:
        driver: bridge
```

**Comment by Springjunky** [comment]
..ohne vollständiges Log wird Dir @buanet wohl ehr nicht helfen können ..

**Comment by trxit** [comment]
Hat sich endlich erledigt.. ich hatte im Backup 2x system.adapter.admin, damit kommt das iobrtoker_startup.sh Script wohl nicht klar...

**Comment by buanet** [comment]
Nicht ganz so schnell. :) Schön dass du den Fehler finden konntest. Trotzdem ist das für mich interessant. Heißt das, du hattest zwei Admin Instanzen installiert?
Interessiert mich ob ich an der Stelle vielleicht das Script verbessern kann...

MfG,
André

**Comment by trxit** [comment]
Genau,

ich hatte mir mal - warum auch immer - eine zweite Admin Instanz installiert. Ich hatte somit system.adapter.admin.0 und system.adapter.admin.1. Wobei die eigentliche Hauptaktivität dann über den system.adapter.admin.**1** ging, was das Script schätze ich dann durcheinander gebracht hat. da dort eben explizit nach dem system.adapter.admin.**0** gesucht wird :)

VG
