### ISSUE TITLE
OpenZwave Update

### ISSUE THREAD

**Issue by gaudes** [buanet/docker-iobroker#65]
Hi André,

ich habe ein Problem mit einem ZWave-Gerät. Auf alle Fälle ist es laut einem anderen betroffenen mit Version openzwave-1.6.989 behoben, siehe Issue hier:

https://github.com/ioBroker/ioBroker.zwave/issues/99

Wäre es möglich die gefixte Version 1.6.989 von OpenZWave zu integrieren ?

Danke und GRuss Ralf

P.S.: Die Beta mit USBDEVICES-Variable funktioniert sonst wunderbar.

**Comment by buanet** [comment]
Version 1.6.1007 ist im neuen beta (v4.1.1beta) drin. Der Build läuft gerade. Sollte in ca einer halben Stunde verfügbar sein.

MfG,
André

**Comment by gaudes** [comment]
Hi André, 
nur zur Info: gerade aktualisiert, sieht gut aus :) 
Danke für deine tolle Arbeit.
VG Ralf
