### ISSUE TITLE
UnhandledPromiseRejectionWarning when using network_mode: host

### ISSUE THREAD

**Issue by SCRAFII** [buanet/docker-iobroker#68]
In Bridged Mode everything works fine but when I change it to network_mode:host ioBroker doesnt start anymore. I don't use redis.

Here is my docker-compose file:

version: '2'

services:
  iobroker:
    restart: unless-stopped
    image: buanet/iobroker:latest
    container_name: iobroker
    hostname: iobroker
    network_mode: host
*#    ports: //the * is just for github
*#      - "8081:8081" 
    volumes:
      - /home/pi/docker/config-data/iobroker:/opt/iobroker
    environment:
      - USBDEVICES=/dev/ttyACM0
      - AVAHI=true
      - REDIS=false
    devices:
      - /dev/ttyACM0:/dev/ttyACM0

and here is the log:

------------------------------------------------------------

-----         Step 1 of 5: Preparing container         -----

------------------------------------------------------------

 

Installing additional packages is set by ENV.

The following packages will be installed: vi...

Done.

 

There are no changes in UID/ GID needed.

 

------------------------------------------------------------

-----   Step 2 of 5: Detecting ioBroker installation   -----

------------------------------------------------------------

 

Existing installation of ioBroker detected in /opt/iobroker.

 

------------------------------------------------------------

-----   Step 3 of 5: Checking ioBroker installation    -----

------------------------------------------------------------

 

(Re)Setting folder permissions (This might take a while! Please be patient!)...

Done.

 

Fixing "sudo-bug" by replacing sudo in iobroker with gosu...

Done.

 

(node:333) UnhandledPromiseRejectionWarning: ParserError: Protocol error, got "H" as reply type byte. Please report this.

    at handleError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:190:15)

    at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:304:14)

(node:333) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

(node:333) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

------------------------------------------------------------

-----      Step 4 of 5: Applying special settings      -----

------------------------------------------------------------

 

Some adapters have special requirements/ settings which can be activated by the use of environment variables.

For more information take a look at readme.md on Github!

 

(node:354) UnhandledPromiseRejectionWarning: ParserError: Protocol error, got "H" as reply type byte. Please report this.

    at handleError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:190:15)

    at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:304:14)

(node:354) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

(node:354) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Avahi-daemon is activated by ENV.

Checking avahi-daemon installation state...

Avahi-daemon is NOT installed. Going to install it now...

Configuring avahi-daemon...

Configuring dbus...

Starting dbus...

Starting avahi-daemon...

Starting Avahi mDNS/DNS-SD Daemon: avahi-daemon.

Done.

 

Usb-device-support is activated by ENV.

Setting permissions for /dev/ttyACM0...

Done.

 

------------------------------------------------------------

-----          Step 5 of 5: ioBroker startup           -----

------------------------------------------------------------

 

Starting ioBroker...

 

host.iobroker check instance "system.adapter.admin.0" for host "iobroker"

host.iobroker check instance "system.adapter.discovery.0" for host "iobroker"

host.iobroker check instance "system.adapter.zigbee.0" for host "iobroker"

host.iobroker check instance "system.adapter.yahka.0" for host "iobroker"

================================== > LOG REDIRECT system.adapter.admin.0 => true [starting]

(node:923) UnhandledPromiseRejectionWarning: ParserError: Protocol error, got "H" as reply type byte. Please report this.

    at handleError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:190:15)

    at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:304:14)

(node:923) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

(node:923) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

(node:934) UnhandledPromiseRejectionWarning: ParserError: Protocol error, got "H" as reply type byte. Please report this.

    at handleError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:190:15)

    at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:304:14)

(node:934) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

(node:934) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

(node:945) UnhandledPromiseRejectionWarning: ParserError: Protocol error, got "H" as reply type byte. Please report this.

    at handleError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:190:15)

    at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:304:14)

(node:945) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

(node:945) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

(node:956) UnhandledPromiseRejectionWarning: ParserError: Protocol error, got "H" as reply type byte. Please report this.

    at handleError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:190:15)

    at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:304:14)

(node:956) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

(node:956) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Thanks for your help!

**Comment by Apollon77** [comment]
These "unhandled Promise Rejections" normally mean that adapters from a jscontroller 2.x installations connect to a js-controller 1.5.x "main process"...

**Comment by buanet** [comment]
Looks like you use an existing ioBroker installation inside your mounted folder. What happens when you mount an empty folder and start your container in host network mode? 

btw: I cannot reproduce the issue with my testequipment....

Regards,
André

**Comment by SCRAFII** [comment]
Thanks for the Response, I tried it with an empty folder and I get the same error. The Host is an RPi4 running Raspbian Lite.

**Comment by buanet** [comment]
I tried on 3 different machines now. I am not able to reproduce the issue. 

It looks like your container keeps running. Can you try the following commands:

`iobroker object get system.adapter.admin.0 --pretty | grep -oP '(?<="host": ")[^"]*'`
and
`hostname`

I think this may be an issue caused by problems getting the hostname when using host mode networking...

**Comment by SCRAFII** [comment]
Thanks for your help, here is the result:

**root@iobroker_test:/opt/iobroker# iobroker object get system.adapter.admin.0 --pretty | grep -oP '(?<="host": ")[^"]*'**
(node:971) UnhandledPromiseRejectionWarning: ParserError: Protocol error, got "H" as reply type byte. Please report this.
    at handleError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:190:15)
    at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:304:14)
(node:971) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:971) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
iobroker_test
**root@iobroker_test:/opt/iobroker# hostname**
iobroker_test

**Comment by buanet** [comment]
Ok, seems like there is a problem with the iobroker command, not a hostname issue...

For further analysis I need to reproduce the error. But I'm still not able to do that. 
Maybe I can try with my raspberry, but this will take some time...

Regards,
André

**Comment by maku1604** [comment]
Hello SCRAFII, 
I ran into the same issue and I found a reason for it after testing different versions of this container. 
I turned out, that Port 9000 was already in use on my docker host. When using bridge mode, I did not see this, because I only forwarded Port 8081 for the admin interface but not Port 9000. 
After making Port 9000 available on the docker host, the container was launching with network=host as expected. Please give it a try. 

Regards, 
Matthias

**Comment by SCRAFII** [comment]
Thank you very much! this was the issue, I had my Portainer Container running on Port 9000, now it works!
