### ISSUE TITLE
PicoTTS Kompatibilität / Environment Variable für Paketquellen

### ISSUE THREAD

**Issue by Byolock** [buanet/docker-iobroker#69]
Die Nutzung von PicoTTS für den SayIt Adapter benötigt das Paket libttspico-utils
[https://packages.debian.org/stretch/sound/libttspico-utils](url)

Über die PACKAGES Variable lässt sich dieses aber nicht installieren da das Paket nicht in den Standard Paketquellen vorhanden ist sondern unter **non-free** (siehe Link). 

Würde mich sehr freuen wenn du eine Kompatibilität einrichten könntest zb. durch hinzufügen der Paketquelle oder eine neue Variable welche das hinzufügen von eigenen Paketquellen ermöglicht.

**Comment by buanet** [comment]
Hallo,
werde das wohl eher nicht speziell für PicoTTS umsetzen, aber mit dem Feature aus #73 sollte das umsetzbar sein. 

MfG,
André

**Comment by buanet** [comment]
Hallo, in der aktuellen beta gibt es jetzt die möglichkeit beim Start des Containers ein selbst erstelltes Script ausführen zu lassen. Damit sollte die installation von PicoTTS machbar sein. Mehr dazu in #73 .

MfG,
André
