### ISSUE TITLE
ZWAVE Unterstützung

### ISSUE THREAD

**Issue by schmupu** [buanet/docker-iobroker#7]
ich habe eine Frage und kein Issue. Ich nutze die latest Verison vom Docker Container und habe in im Changelog gesehen, dass jetzt auch ZWAVE unterstützt wird. Ich habe den Z-Wave USB Stick (ZMEEUZB1) im Einsatz. Dieser wird auch von der Synology erkannt. Im ioBroker Docker Container sehe ich diesen standardmäßig nicht. Gibt es einen Trick, wenn man über die Synology Oberfläche den ioBroker Docker Container anlegt, dass die USB Devices berücksichtigt werden? Ich muss jetzt den Container wie folgt über die Shell Oberfläche mit device==/dev/ttyACM0  erstellen:

`docker run -d --name iobroker-new --restart=always --hostname=iobroker --ip 192.16.10.81 --dns=192.16.10.80 --dns-search=my-domain.local --add-host="nas nas.my-domain.local:192.16.10.80" --net=eth0 --device=/dev/ttyACM0 -v /volume1/docker/iobroker/opt/iobroker:/opt/iobroker -it buanet/iobroker:latest`

Anschließend kann ich das Device im ioBroker Docker Container nutzen, bekomme aber beim ZWAVE Adapter einen Fehler dass die Library libopenzwave.so.1.4 fehlt. Ich muss im Docker Container noch openzwave installieren. 

```
cd /tmp  
git clone https://github.com/OpenZWave/open-zwave.git
cd /tmp/open-zwave
make install
ln -s /usr/local/lib64/libopenzwave.so /usr/local/lib/libopenzwave.so
ln -s /usr/local/lib64/libopenzwave.so.1.4 /usr/local/lib/libopenzwave.so.1.4
ldconfig
```

Was mache ich verkehrt? Kannst Du openzwave zukünftig im Docker Container berücksichtigen?

**Comment by buanet** [comment]
Hallo Stübi,

es gibt eigentlich zwei Wege USB-Devices auf der DS zu Docker durch zu reichen. Einen hast du mit dem Weg über die Kommandozeile ja bereits gefunden. Der andere ist, den Container auf der DS mit erhöhten Rechten auszuführen (Häkchen "Container mit hoher Priorität ausführen"). Dann hat man aus dem Container heraus auch die Möglichkeit auf die USB-Devices zuzugreifen. 
Ich persönlich habe allerdings keine Peripherie an der DS. Zum einen weil ich dem Container keine erhöhten Rechte einräumen möchte, zum anderen weil der Standort meiner DS ungünstig ist für Bluetooth, RFlink und co ist. Für diese Fälle habe ich mir einen separaten Einplatienencompuer (ähnlich Raspberry Pi) als Multihost an ioBroker angebunden. Und daran dann alles was per USB angebunden wird.

Was die Unterstützung von z-Wave angeht, habe ich eigentlich alle Voraussetzungen die hier (https://github.com/ioBroker/ioBroker.zwave) gelistet sind integriert. Bei deinem Fehler sollte laut Beschreibung zum Adapter ein "ldconfig" reichen. 
Ich persönlich habe eben einmal den Adapter in meinem TestContainer (beta) installiert. Lief ohne Probleme durch und ließ sich starten. Da ich leider kein Z-Wave-USB Device habe kann ich natürlich zur Funktion nichts sagen. 

MfG,
André

Closed #7
