### ISSUE TITLE
Problem with Connection over iobroker to alexa2.0

### ISSUE THREAD

**Issue by maestroat** [buanet/docker-iobroker#70]
i have synology docker and this iobroker version with newest version update last 2 days.
its all new installed.
alexa2.0 loxone, i will see the volume from the echo dots in my loxone app. over script in iobroker i get infos when volume change direct on divise or when it changes on alexa app or website. thats work.
other way i change volume on loxone app or with link direct in webbrowser thats not work. and the webbrowser says me that:
http://192.168.1.2:8081/set/alexa2.0.Echo-Devices.xxxxxxxxxx1.Player.volume?value=10

Cannot GET /set/alexa2.0.Echo-Devices.G090U50991120EX1.Player.volume

so its not a problem between loxone and iobroker its a problem in iobroker i think, but dont know where is the error :( please help thank you.

**Comment by Apollon77** [comment]
Where you got the link from? How your Web Adapter config looks like? It seems YouTube simple-api Adapter Style to set the data. Is that adapter installed or web configured correctly?

All in all no Docker issue. Best contact iobroker Forum.

**Comment by maestroat** [comment]
the link is from a friend. he have iobroker on windows installed and in a manual he found this link its work on loxone app and on webbrowser, but not by me. on loxoneapp i see nothing, and on webbrowser the cannot message......


okay thank you i wait of iobroker forum infos..

**Comment by Apollon77** [comment]
Compare the config from Web Adapter with your friend and check which adapters are installed

**Comment by maestroat** [comment]
Thank you AGAIN! it was Simple api - adapter. now it works

**Comment by buanet** [comment]
I guess this colud be closed...
