### ISSUE TITLE
Support new architecture

### ISSUE THREAD

**Issue by LiTe1991** [buanet/docker-iobroker#72]
Hi,

first of all great work with this docker image.
Can you please add following architecture: linux/i686 (Debian buster)
I would be very happy, if you can make the change quick :-)

Thx

Best regards
LiTe1991

**Comment by buanet** [comment]
Hi,
i686? really? I thought this is dead... :)
As I started to support other architectures I decided to only support 64bit (except armv7). Is it really necessary to support 32bit i686?

What about the community? Any ideas/ votes?

Regards,
André

**Comment by LiTe1991** [comment]
Hi,
sry you are right, I do a misstake during my Debian installation. Amd64 ist supported right?

Best regards
LiTe

**Comment by buanet** [comment]
Yes it is.

Regards,
André
