### ISSUE TITLE
Add possibility to execute advanced userscript on container startup

### ISSUE THREAD

**Issue by buanet** [buanet/docker-iobroker#73]
This has already been an idea/ discussion in the past.
With #69 I now got an possible use case. 

The ides is to make it possible to execute an user defined script on startup. 
This might be a feature only for advanced users. Any suggestions? 

Regards, 
André

**Comment by buanet** [comment]
I added this feature in actual beta. For details see [readme.md](https://github.com/buanet/docker-iobroker/blob/beta/README.md).
Maybe there are some advanced user who want to test that feature and give me some feedback. 
Thank you. 

Regards,
André

**Comment by Byolock** [comment]
Thank you André,
will test it for #69 and report back.

**Comment by Byolock** [comment]
Actually i have a question beforehand,
i would like to test in my production Environment, i have several backups so no worrys about data loss and stuff but would it be possible to go back from "beta" tag to "latest"?

**Comment by buanet** [comment]
Sorry for the late response. Yes it is possible to switch back from beta to latest. No worries.

Did you already test the new feature? 

Regards,
André

**Comment by Byolock** [comment]
Yes i'm running beta since Mid-February and it's running fine.
Thank you for implementing.
