### ISSUE TITLE
Page on docker-hub contains outdated instructions

### ISSUE THREAD

**Issue by Boldie** [buanet/docker-iobroker#76]
The page on docker hub contains outdated instructions like this:
IOB_ADMINPORT | 8081 | Sets ioBroker adminport on startup
-> must be ADMINPORT

or image: buanet/iobroker:latest is incorrect.

It tooks some time to find out what was wring in my config till I had a look to the github repo here.

**Comment by buanet** [comment]
Hi, 
please take a look at the changelog section of readme.md.
There are different versions. One for latest and one for beta. See here:

latest: https://github.com/buanet/docker-iobroker/blob/master/README.md
beta: https://github.com/buanet/docker-iobroker/blob/beta/README.md

At Docker Hub you will always find the newest version (including all beta changes).

In general this is no problem cause I only add things, but in actual beta i changed the name of the ENV "ADMINPORT" to "IOB_ADMINPORT" (to make a difference between ioBroker specific ENVs and container specific ENVs. 
So your confusion is basically my fault. Hope you can forgive me. :)
Will try to take care on that in the future. 
Thank you.

Regards,
André
