### ISSUE TITLE
Restore tar.gz 

### ISSUE THREAD

**Issue by bug84** [buanet/docker-iobroker#78]
Hi, I have installed the container successfully and works. 
Now I want to restore an backitup backup tar.gz
But I don’t become it to work.
In wich Directory I need to put the tar file??

Host is an Intel NUC with Debian 10 and Docker CE installed, visualization with Portainer.

On Startup the script das “Existing Installation found in /opt/iobroker “
But Backup don’t restore

**Comment by buanet** [comment]
Hi,
automatic restore only works on the very first start of a new container. So if you want to restore your backup try the following: 
- place your backup in an empty folder which you will mount to /opt/iobroker into your container
- setup a new container and mount the folder containing your backup
The startup script will detect the backup and restore it before starting iobroker for the first time. 

If you already set up a container and it is running you have to place your backup to the original path (I think it is /opt/iobroker/backups/) which is basically "backups" inside the folder you mounted to /opt/iobroker/ when you configured your container.
Then you can restore your backup by commandline or using the backitup-adapter.

Regards,
André

**Comment by bug84** [comment]
Hi,
thank you for rapid answer.
Now i Add new Container, on volumes i add volume mapping with:
Container: /iobroker
host: /opt/iobroker/ (place of my tar.gz Backup File on Debian)

On first Startup log say:
`Existing installation of ioBroker detected in /opt/iobroker.`

and dont restore anything, the scipt install a empty iobroker, wich works great, but without restore.

whats my error?

**Comment by bug84** [comment]
i test it also with backitup adapter to restore.
i select the backupfrom my ftp server and restore begins, but hang on Gestartet... and dont restore

**Comment by buanet** [comment]
You have to mount your volume/folder to: 
Container: /opt/iobroker
Host: yourvolume or /path/on/your/host

Folder has to be empty exept the backupfile.

Regards,
André

**Comment by bug84** [comment]
ok thats it.
thanks, now restored.

the solution was the Container path.

thank you very much

**Comment by kaputtzich** [comment]
Sorry to open up this issue but i'm stuck in same situation.
Container comes up, picks up the the backup file, moves it into the backup folder created by the startup script but doesn't restore anything.
Log output: `Looks like this is a new and empty installation of ioBroker.`
Manual restore via BackitUp doesn't work either, same as @bug84 reported.

Another error in the log file is
`/opt/scripts/iobroker_startup.sh: Zeile 192: /usr/bin/iobroker: Keine Berechtigung
/opt/scripts/iobroker_startup.sh: Zeile 192: [: 8081: Einstelliger (unärer) Operator erwartet.`

But that seems to be the port mapping

**Comment by buanet** [comment]
Way too less information...
Where ist your Logfile? 

Regards,
André

**Comment by kaputtzich** [comment]
'tschuldigung ;)
[https://pastebin.com/U5Ck52fS](url)

**Comment by bug84** [comment]
Ich konnte es ja erfolgreich wiederherstellen.
Jedoch habe ich den Docker wieder deaktiviert und meine VM auf der gleichen Hardware läuft nun.

Denn der Container lief zwar, jedoch war IoBroker irgendwie träge beim öffnen der Instanzen, öffnete die Einstellungen zum Teil gar nicht, hat Objekte nicht zuverlässig aktualisiert, hat meine Homematic Basis auch irgendwie zum hängen gebracht.

Irgendwas bremst da enorm aus.
Auf meiner Proxmox VM läuft es flüssig und stabil, auf dem gleichen NuC

**Comment by kaputtzich** [comment]
Bei einem älteren Image Build hat es ebenfalls funktioniert sehe ich gerade
Hier noch das restore.log des aktuellen Builds
Kurz und knackig:
`/opt/scripts/iobroker_startup.sh: Zeile 118: /usr/bin/iobroker: Keine Berechtigung`

**Comment by buanet** [comment]
@kaputtzich 
3 Fragen:

1.
"SETGID:    100 " << korrekt oder tippfehler?
denn
Changing UID to 1006 and GID to 100...,
groupmod: GID »100« existiert bereits.,
(was auch immer das heißen mag)

2. 
Was für ein Host nutzt du? Synology DS oder was anderes?

3. 
Trifft das bei dir vielleicht zu?
`Important: If the folder you mount to /opt/iobroker in your container is placed on a mounted device, partition or other storage, the mountpoint on your host should NOT have the "noexec" flag activated. Otherwise you may get problems executing ioBroker inside the container! `
(siehe: https://github.com/buanet/docker-iobroker/blob/beta/README.md)

MfG,
André

**Comment by kaputtzich** [comment]
Asche auf mein Haupt...
Ich hab das mount auf eine Partition verlegt die tatsächlich noexec hatte

Hätte heut früh doch nicht auf Kaffee verzichten sollen
Sorry dafür, aber ich schau mal ob ich ähnliche Laufzeitprobleme habe wie @bug84
