### ISSUE TITLE
Running from commandline Typo

### ISSUE THREAD

**Issue by GRunZ2** [buanet/docker-iobroker#79]
Hallo,

ich bin relativ neu mit Docker unterwegs und ziehe momentan meine Raspberry Anwendungen auf Docker um.
Müsste die Quelle und Ziel vom Beispiel "Running from commandline" nicht getauscht werden? Docker Compose Beispiel ist richtig

Aktuell:
docker run -p 8081:8081 --name iobroker -v **/opt/iobroker:/iobroker** buanet/iobroker:latest
Sollte:
docker run -p 8081:8081 --name iobroker -v **/iobroker:/opt/iobroker** buanet/iobroker:latest

**Comment by buanet** [comment]
Danke für den Hinweis. Ist korrigiert. 

MfG,
André
