### ISSUE TITLE
ZWAVE und v1.2.0

### ISSUE THREAD

**Issue by schmupu** [buanet/docker-iobroker#8]
Hallo,

ich bekommen folgenden Fehler wenn ich den ZWAVE Adapter in Version 1.2.0 starte:

```
host.iobroker-test 2018-08-21 15:08:34.935 info Restart adapter system.adapter.zwave.0 because enabled 
host.iobroker-test 2018-08-21 15:08:34.935 error instance system.adapter.zwave.0 terminated with code 0 (OK) 
host.iobroker-test 2018-08-21 15:08:34.935 error Caught by controller[0]: at Object.Module._extensions..js (module.js:586:10) 
host.iobroker-test 2018-08-21 15:08:34.935 error Caught by controller[0]: at Module._compile (module.js:577:32) 
host.iobroker-test 2018-08-21 15:08:34.935 error Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.zwave/node_modules/openzwave-shared/lib/openzwave-shared.js:24:22) 
host.iobroker-test 2018-08-21 15:08:34.935 error Caught by controller[0]: at require (internal/module.js:20:19) 
host.iobroker-test 2018-08-21 15:08:34.935 error Caught by controller[0]: at Module.require (module.js:504:17) 
host.iobroker-test 2018-08-21 15:08:34.935 error Caught by controller[0]: at Function.Module._load (module.js:445:3) 
host.iobroker-test 2018-08-21 15:08:34.935 error Caught by controller[0]: at tryModuleLoad (module.js:453:12) 
host.iobroker-test 2018-08-21 15:08:34.934 error Caught by controller[0]: at Module.load (module.js:494:32) 
host.iobroker-test 2018-08-21 15:08:34.934 error Caught by controller[0]: at Object.Module._extensions..node (module.js:604:18) 
host.iobroker-test 2018-08-21 15:08:34.934 error Caught by controller[0]: at Error (native) 
host.iobroker-test 2018-08-21 15:08:34.933 error Caught by controller[0]: Error: libopenzwave.so.1.4: cannot open shared object file: No such file or directory 
zwave.0 2018-08-21 15:08:34.901 error Error: libopenzwave.so.1.4: cannot open shared object file: No such file or directory at Error (native) at Object.Module._extensions..node (module.js:604:18) at Module.load (module.js:494: 
zwave.0 2018-08-21 15:08:34.899 error uncaught exception: libopenzwave.so.1.4: cannot open shared object file: No such file or directory 

```
Ich habe auch ein ldconfig ausgeführt. Container läuft im priveleged Modus und /dev/usb/usb habe ich auch gemountet.

Fehlerfrei läuft es erst, wenn ich folgendes Paket noch installiere:

```
cd /tmp  
git clone https://github.com/OpenZWave/open-zwave.git
cd /tmp/open-zwave
make install
ln -s /usr/local/lib64/libopenzwave.so /usr/local/lib/libopenzwave.so
ln -s /usr/local/lib64/libopenzwave.so.1.4 /usr/local/lib/libopenzwave.so.1.4
ldconfig
```

VG
Stübi

**Comment by lizzard77** [comment]
Same issue here, thanks for the workaround, @schmupu !

VG liz

**Comment by buanet** [comment]
Hallo,
werde schauen ob und wie ich das mit in den Container bekomme. Eventuell als zusätzliches Script...
Bis dahin bitte den Workaround nutzen. 

MfG,
André

**Comment by buanet** [comment]
Offensichtlich wird bei der Installation "sudo apt-get install libudev-dev -y" aufgerufen. Sudo gibt es im Container aber nicht...

**Comment by CrazyApple** [comment]
Und was machen wir da jetzt ;) ?

**Comment by CrazyApple** [comment]
Kann ich das separat vorher installieren. oder ruft der "zwave-installer" dann den sudo immer noch auf und läuft in den Fehler?

**Comment by rewegit** [comment]
Du könntest ein anderes base image versuchen.
Ich nehme ubuntu 

FROM ubuntu:16.04

Bisher keine Probleme.

**Comment by CrazyApple** [comment]
sudo ist installiert, aber der install von zwave scheitert trotzdem :(

**Comment by DutchmanNL** [comment]
> sudo ist installiert, aber der install von zwave scheitert trotzdem :(

ich kan das nicht bestätigen bei mir läuft z-wave in diesem docker (latest) und einem Synology NAS

**Comment by buanet** [comment]
So, ich glaube das Thema hier ist lange genug abgehangen. :)
Ich habe leider noch immer kein z-wave sodass ich diesbezüglich nicht experimentieren kann. Daher brauche ich ein wenig Unterstützung...

Folgende Schritte müssen abgearbeitet werden: 
1. Installation und Inbetriebnahme des z-wave-Adapters in einem "jungfräulichen" Beta-Image und Dokumentation der Schritte innerhalb der Kommandozeile zur Installation von "open-zwave"(??)
(Geht es noch so wie im ersten Post von Stübi? Reicht das aus?)
2. Erstellen eines Scripts, dass die Voraussetzungen für den z-wave-Adapter automatisch konfiguriert
3. Integration des Scripts in das Startscript und Einbau einer optionalen Umgebungsvariable "ZWAVE" (true/false) die dann bei Bedarf das z-wave-Script triggert (ähnlich wie ich es mit dem avahi-daemon gemacht habe). 

Bei Schritt 2 kann ich unterstützen und Schritt 3 übernehme ich. Für den ersten Schritt fehlt mir leider das Equipment und das Wissen um z-wave...

Freiwillige vor. :)

MfG,
André

**Comment by DutchmanNL** [comment]
1 kann ich machen, 2 und 3 bin ich raus

**Comment by gaudes** [comment]
Hallo zusammen,

kurz zur Info wie ich es mit dem aktuellen Container zum Laufen bekommen habe:

1. Ich habe den Stick eingesteckt und in Portainer das Device durchgemappt:
![image](https://user-images.githubusercontent.com/34286177/63440905-f2a6c200-c430-11e9-99a5-dd82d62c65c9.png)

2. Ich habe den Adapter installiert und konnte den Anschluss /dev/ttyACM0 auswählen
3. Nach Start des Adapters kam der Fehler im Log wegen fehlender libopenzwave.so
4. libopenzwave.so gemäß Workaround von @schmupu installiert im Container (siehe oben)
5. Danach kam der nächste Fehler "Failed to start driver"
6. Berechtigungen für /dev/ttyACM0 im Container korrigiert: 
chown root:dialout /dev/ttyACM0
chmod g+rw /dev/ttyACM0
7. Danach ZWave-Instanz nochmal neu gestartet und alle meine bisher verbundenen Geräte sind aufgetaucht (ich habe den Stick vom Raspberry übernommen und die gleiche Network-ID verwendet, aber keine Datenübernahme in ioBroker selbst gemacht)

Eventuell hilft dies ja weiter.

Gruss Ralf

**Comment by cburghardt** [comment]
Wir haben mittlerweile auf die offiziellen Releases von openzwave umgestellt, also können wir das Image auch gut erweitern.
Downloads gibt es hier: http://old.openzwave.com/downloads/
Version 1.6.878 und es werden die Packages libopenzwave und devel benötigt, also zb für i386
http://mirror.my-ho.st/Downloads/OpenZWave/Debian_9.0/i386/libopenzwave1.6_1.6.878-0_i386.deb
http://mirror.my-ho.st/Downloads/OpenZWave/Debian_9.0/i386/libopenzwave1.6-dev_1.6.878-0_i386.deb
Das deckt die Punkte 3 und 4 ab.

**Comment by cburghardt** [comment]
Alternativ kompilieren:
curl -L -O http://old.openzwave.com/downloads/openzwave-1.6.913.zip
unzip -o openzwave-1.6.913.zip && rm openzwave-1.6.913.zip
cd openzwave-1.6.913 && make && sudo make install
sudo ldconfig /usr/local/lib64

**Comment by buanet** [comment]
Im aktuellen Beta v3.1.4beta (Vorstufe zu v4) ist jetzt auch ein Script drin was openzwave installieren soll. Aktiviert wird das Ganze über eine env "ZWAVE" die auf true gesetzt werden muss.
Sieht bei mir soweit gut aus, kann es aber mangels Hardware nicht endgültig testen. 

Was die Geschichte mit den Berechtigungen auf das/die (USB-)Devices angeht, habe ich mit #36 ein ähnliches Thema.... Muss ich mir nochmal Gedanken machen... Jemand eine Idee?

MfG,
André

**Comment by cburghardt** [comment]
Gibt es nicht stattdessen eine Möglichkeit, im gemounteten iobroker Verzeichnis ein shell Script nach dem container Start aufzurufen? Das kann ja im Standard leer sein und dort könnte man dann so Geschichten wie zwave, Berechtigungen und Co hinterlegen.

**Comment by buanet** [comment]
Sowas ordne ich allerdings in die Kategorie "Bastellösung" ein.
Ziel ist es für mich das Image so zu erweitern, dass auch ein Laie in der Lage ist es zum laufen zu bekommen und sich nicht damit befassen muss wie es im einzelnen funktioniert.

Problem an der Sache ist momentan eigentlich nur, dass ich keine Hardware an der DS betreibe und dementsprechend nicht auf Erfahrungswerte zurückgreifen kann.
Habe hier noch einen Zigbee Stick rum liegen. Wenn ich mal etwas Zeit haben sollte, könnte ich mal jugend forscht machen und schauen was ich tun muss um aus dem iob darauf zu greifen zu können.
Theoretisch müsste es ja reichen den iobroker-User zum Besitzer für das Device zu machen und das Device in den Container durch zu reichen (wie oben erklärt)... 

MfG, 
André

**Comment by cburghardt** [comment]
Naja, das erste USB Device ist in der Regel /dev/ttyACM0. Damit es funktioniert reicht bei mir ein chmod 666 auf das das Device nach dem Start des container, damit läuft schon mal ein z-wave und zigbee device.
Aber dann deckst du genau diesen einen Fall ab. Hat der Benutzer mehr als ein Gerät, ist die Namensgebung anders und du brauchst einen generischen Ansatz. Sonst wirst du mit Tonnen an environment Variablen enden.
Wie wäre es mit beiden Varianten? Ein ENABLE_USB Flag, dass das erste Device schreibbar macht und für alle anderen Fälle einen Einstiegspunkt als Script?

**Comment by gaudes** [comment]
Hi,

also bei mir hats funktioniert, ich musste halt die Berechtigungen auf das Device wieder setzen:

chown root:dialout /dev/ttyACM0
chmod g+rw /dev/ttyACM0

Zur Lösung des Themas ein Vorschlag:

Falls möglich könnte man ja beim der Variable ZWAVE statt "true" einfach das Device eintragen, also z.B. "ttyACM0". In der Regel ändert sich das ja im Container nicht einfach, da ich ja z.B. im Portainer das Mapping eintragen musste, oder ?

Danke und viele Grüße

Ralf

**Comment by buanet** [comment]
Hallo zusammen,
ich bin gerade dabei eine Lösung zu basteln, aber ich bekomme meinen zwave-adapter einfach nicht grün... Das Log im ioBroker sieht so aus: 


```
zwave.0 | 2019-11-25 15:29:44.168 | debug | node255: timeout
zwave.0 | 2019-11-25 15:29:43.168 | debug | node255: timeout
zwave.0 | 2019-11-25 15:29:42.167 | debug | node255: timeout
zwave.0 | 2019-11-25 15:29:41.167 | debug | node255: timeout
zwave.0 | 2019-11-25 15:29:40.221 | debug | system.adapter.admin.0: logging true
zwave.0 | 2019-11-25 15:29:38.546 | debug | received all objects
zwave.0 | 2019-11-25 15:29:38.500 | info | starting. Version 1.6.3 in /opt/iobroker/node_modules/iobroker.zwave, node: v10.17.0
zwave.0 | 2019-11-25 15:29:38.417 | debug | statesDB connected
zwave.0 | 2019-11-25 15:29:38.390 | debug | objectDB connected
host.iobrokerdev | 2019-11-25 15:29:37.768 | info | instance system.adapter.zwave.0 started with pid 1698
```
Adapter bleibt gelb. Google spuckt so recht nichts aus. :( Berechtigungen und installierte Pakete passen eigentlich auch (so wie es hier ja schon beschrieben worden ist). 
Liegt es vielleicht am Stick? Kann ich das irgendwie testen? 
Danke. 

MfG,
André

**Comment by cburghardt** [comment]
Eine node mit der ID 255 ist etwas seltsam, die starten normal bei 1.
Was für ein Stick ist das? Am Besten das logging in den Einstellungen einschalten, dann erzeugt openzwave ein Log.

**Comment by buanet** [comment]
Ich habe einen selbst geflashten CC2531. Einer hängt an meinem Pi-Slave und läuft, der andere jetzt zum testen an der Synology und will nicht grün werden.... 
Logging hatte ich schon an... Dachte der haut das mit ins ioBroker-Log.... File habe ich gefunden:
[OZW_Log.txt](https://github.com/buanet/docker-iobroker/files/3888433/OZW_Log.txt)
Kann das geübte Auge da was erkennen? Schein mir als würde mein Stick nicht antworten....

**Comment by buanet** [comment]
Ok, habe jetzt eine Beta (v4.0.1beta) gemacht. Dort gibt es eine Variable "USBDEVICES" die man mit einem oder mehreren (per Semikolon getrennten) Devices befüllen kann. Beispiel etwa "/dev/ttyACM0" oder "/dev/ttyACM0;/dev/ttyACM1". Die Berechtigungen werden dann automatisch gesetzt. Bei meinem Test hat das soweit gut funktioniert. Bitte einfach mal testen und Feedback geben. Danke.

MfG,
André

**Comment by gaudes** [comment]
Hallo,

habe es getestet, bei mir funktioniert es wunderbar :-)

Eine Bitte noch: Wäre es möglich im Image den js-controller auf Version 2.1.1 upzudaten ?

Dann wäre die nächste "latest" perfekt :-)

Vielen Dank für deine Arbeit und Gruß

Ralf

**Comment by TheMBeat** [comment]
Hallo zusammen, bei mir hat es bisher noch nicht funktioniert. Ich habe es als neuen Container probiert und per Docker-compose. 
Im Log wird auch immer nur angezeigt, dass openzwave installiert wird und dann erscheint der direkt Starte ioBroker, als wenn die Abfrage für die USB Devices aus dem Startscript übersprungen wird. 
Im Portainer wird die ENV Variable aber richtig angezeigt. 
Als Image habe ich :beta gewählt.

**Comment by gaudes** [comment]
Hi,
ich habe es mit dem Image "v4.0.1beta" getestet.
Gruss Ralf

**Comment by TheMBeat** [comment]
Sollte es nicht eigentlich dasselbe Image sein? 
Aber ich werde es direkt mal testen und melde mich dann noch einmal.

**Comment by buanet** [comment]
> Eine Bitte noch: Wäre es möglich im Image den js-controller auf Version 2.1.1 upzudaten ?

Der js-controller ist Teil von ioBroker. Den musst du in jedem Fall manuell updaten.
Wenn du einen neuen, jungfräulichen Container aufsetzt, kommt immer die Version js-controller mit, die beim ioBroker-Setup aktuell dabei ist....

> Als Image habe ich :beta gewählt.

4.0.1beta sollte gleich :beta sein. Welche Version steht im Log ganz oben? Wie seht es in deiner compose-yml?

MfG,
André

**Comment by TheMBeat** [comment]
Im Log im Header stand beides mal v4.0.1.
Auch im neuen Versuch wurde das echo aus der Abfrage USBDEVICES nicht ausgegeben und ioBroker wurde nach dem Installieren von OpenZWave direkt gestartet.

Das Docker-Compose File sieht so aus.
```YAML
version: '3.7'
services:
  ioBroker:
    image: buanet/iobroker:beta #beta oder latest
    container_name: iobroker
    environment:
      - PACKAGES=nano, wget
      - AVAHI=false
      - LANGUAGE=de_DE:de
      - LANG=de_DE.UTF-8
      - LC_ALL=de_DE
      - TZ=Europe/Berlin
      - SETUID=1000
      - SETGID=1000
      - ZWAVE=true
      - ADMINPORT=8081
      - USBDEVICES=/dev/ttyACM0
      #- USBDEVICES: /dev/ttyACM0; /dev/ttyAMA0  
    ports:
      - "9000:9000" #Multihost
      - "9001:9001" #Multihost
      - "8081:8081" #ioBroker Admin
      - "8088:8088" #Terminal
      - "8284:8284" #SocketIO
      - "8123:8123" #Homekit
      - "8082:8082" #Web (Vis, Mobile, Lovelace, Material)
      - "2000:2000" #hm-rpc
      - "2001:2001" #hm-rpc 
      - "2010:2010" #hm-rpc
      - "8701:8701" #hm-rpc
      - "1880:1880" #node-red
      - "1883:1883" #mqtt
    # devices:
    #   - /dev/ttyACM0;/dev/ttyACM0
    volumes:
      # (Host):(Container)
      - /srv/iobroker_data:/opt/iobroker
    restart: always
```

mit `ls -la /dev/ttyACM0` bekomme ich auch die Meldung => No such file or directory

MfG,
Marcel

**Comment by TheMBeat** [comment]
Ich denke ich habe den Fehler gefunden. 
Da ich auf einem Pi arbeitet wird natürlich das Image für ARMv7hf gezogen und dort sind die Änderungen nicht implementiert worden, die Betas unterscheiden sich in dem Punkt.

**Comment by buanet** [comment]
Sorry,
hatte die changes erstmal nur für amd64 gemacht. :) 
Hab es gerade auch für die anderen Architekturen übernommen. Build läuft gerade. Sollte also in der nächsten Stunde verfügbar sein.

MfG,
André

**Comment by TheMBeat** [comment]
Vielen Dank, ich habe es heute morgen per Docker-Compose und Portainer getestet, bisher hatte ich keinen erfolg. 
Bekomme immer noch die Fehlermeldung "Cannot access '/dev/ttyACM0': No such file or directory"
Habt ihr zufällig eine Idee?

Ich wollte per GID und UID, die Rechte ändern und nochmal testen.

MfG,
Marcel

**Comment by gaudes** [comment]
Hi,
@buanet: Danke, die Updates der zentralen Dinge, also alles außer Adaptern war mir im Container noch nicht so ganz klar. Dann mache ich das mal :-)

@TheMBeat:
wird das USB-Device wirklich in den Container gemappt ? Nachdem Du oben geschrieben hattest, dass ```ls -la /dev/ttyACM0``` nichts ergibt, und im Compose-File folgender Eintrag drin ist:

```
- "1883:1883" #mqtt
    # devices:
    #   - /dev/ttyACM0;/dev/ttyACM0
    volumes: 
```
würde ich vermuten dass das USB-Device aktuell nicht durchgemappt wird ?

Gruss Ralf

**Comment by buanet** [comment]
Hab mir gerade nochmal dein compose file angeschaut. Dein Device-Mount ist auskommentiert. Deswegen bekommst du auch das:

> mit ls -la /dev/ttyACM0 bekomme ich auch die Meldung => No such file or directory

Du musst das device natürlich korrekt durch reichen, sonst kann das Script auch keine Berechtigungen setzen. Kontrolle mache ich immer mit "ls - al /dev". Dann bekommst du die Liste der devices. Ist das device nicht drin, hat was mit dem durchreichen nicht geklappt.

MfG,
André

**Comment by buanet** [comment]
@schmupu als Issue Ersteller: Alle Probleme mit Z-Wave und USB-Devices durch die neuen Environment Variables "ZWAVE" und "USBDEVICES" gelöst? Ich habe bisher nichts Negatives gehört und würde diesen alten Issue am liebsten abschließen... :)

MfG,
André

**Comment by TheMBeat** [comment]
Jetzt alles funktioniert. 
Ich bedanke mich für eure Hilfe.

MfG
Marcel
