### ISSUE TITLE
/usr/bin/iobroker: Keine Berechtigung

### ISSUE THREAD

**Issue by rhoerbe** [buanet/docker-iobroker#81]
Image docker.io/buanet/iobroker:latest (fa310216e0fb) from 2020-02-24T12:02Z) I get following issue:

The start script complains with

    /opt/scripts/iobroker_startup.sh: Zeile 192: /usr/bin/iobroker: Keine Berechtigung
    /opt/scripts/iobroker_startup.sh: Zeile 192: [: 8081: Einstelliger (unärer) Operator erwartet.

In the container shell the same issue appeas: `/usr/bin/iobroker: Keine Berechtigung`

**Comment by buanet** [comment]
#78 #71 #64 
Stichwort: noexec

MfG,
André
