### ISSUE TITLE
Startup not installing packages

### ISSUE THREAD

**Issue by rhoerbe** [buanet/docker-iobroker#82]
While startup echoes that packages will be installed, they are not:

    Installing additional packages is set by ENV.
    The following packages will be installed: history openweathermap viessmannapi...
    Done.

I am able to install the packages later in the admin gui

**Comment by buanet** [comment]
Packages are NOT ioBroker-adapters!
You have to install ioBroker-adapters via admin Interface or using the commandline. 
The ENV PACKAGES is for Linux oackages which should be installed automatically to the container on startup. Some adapters require special Linux packages to work.

Regards,
André
