### ISSUE TITLE
Sudo Probleme im Terminal io broker auf synology docker

### ISSUE THREAD

**Issue by maestroat** [buanet/docker-iobroker#84]
root@iobroker:/opt/iobroker# sudo -i                                                                                        
sudo: Hostname iobroker kann nicht aufgelöst werden                                                                        
sudo: Die Audit-Nachricht kann nicht gesendet werden: Unbekannter Fehler -1                                                 
sudo: pam_open_session: Systemfehler                                                                                        
sudo: Regelwerks-Plugin konnte Sitzung nicht initialisieren 

auch andere sudo befehle kommt sofort diese Meldung

**Comment by maestroat** [comment]
root@iobroker:/opt/iobroker# hostname                                                                                       
iobroker

**Comment by buanet** [comment]
Sudo is not supported/ needed. You are still root...
