### ISSUE TITLE
RPI2 adapter "Cannot setup port 23 as input: Error: EACCES: permission denied, open /sys/class/gpio/export‘ "

### ISSUE THREAD

**Issue by mtk64** [buanet/docker-iobroker#87]
It seems that libc6 is outdated. 
Version 2.28 is requested by wiringpi,
but 2.24 is installed. 

```
root@99a59f9214c7:~# ldd --version
ldd (Debian GLIBC 2.24-11+deb9u4) 2.24
```

testing gpio within container shell brings:

```
root@99a59f9214c7:/opt/iobroker# gpio
gpio: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28′ not found (required by /usr/lib/libwiringPi.so)
```

Seems to be similar to this issue, using gpio in a container:
https://github.com/marthoc/docker-deconz/issues/153

**Comment by buanet** [comment]
Hi,
if you can tell me a way/ link how to install libc6 2.28 on Debian Stretch, I can check how we can get it into the image. 

As my first tests with Debian Buster failed, it is actually no option to switch the base image.

Maybe someone already forked my image and switched the base image to buster??? 

Regards,
André

**Comment by mtk64** [comment]
You might try this:

You will find libc6 2.30 (libc6_2.30-4_armhf.deb) in the unstable sid branch: https://packages.debian.org/sid/armhf/libc6/download
E.g. add deb http://ftp.de.debian.org/debian sid main to /etc/apt/sources.list
and execute apt-get update && apt-get upgrade libc6

Or just download from above link and install deb file via dpkg.
I tried to do that within the container itself, but it says that it was installed manually and cannot be installed because of that. Building your image might solve that using sid repo from beginning ?? Don't know ...

Searching within the database via [https://packages.debian.org/search?suite=stretch&arch=armhf&mode=exactfilename&searchon=contents&keywords=libc6](url)
I found this: 
https://packages.debian.org/buster/libc6
https://packages.debian.org/stretch/libc6
https://packages.debian.org/bullseye/libc6

Seems that there is no way for glibc 2.28 on stretch.

Meanwhile I killed my rpi3 and started the same on a rpi2. 
you will not believe, but adapter rpi2 did not logged any Errors anymore.
Seems to work but something is still not working.
I cannot see any changes to input on `gpio readall` even outside the container anymore.
Will have to create some safer hw test equipment to analyze,
my free floating experiment killed my rpi3 by touching 5V signal :-(
Just ordered one rpi4 instead :-)

regards
Michael

**Comment by buanet** [comment]
Hi,
base image was switched to Buster on April 14th.
Is there still an issue with glibc version? 
Please check and give a short response. 
Thank you.

Regards,
André

**Comment by fzzybllz** [comment]
Hi,
i just checked ldd --version with "ldd (Debian GLIBC 2.28-10) 2.28" as result.

regards
Dominik

**Comment by buanet** [comment]
Thanks. Then I guess this is solved.

Regards,
André
