### ISSUE TITLE
NPM CLI problem -

### ISSUE THREAD

**Issue by the-duke** [buanet/docker-iobroker#88]
Hallo, danke erstmal für diesen tollen Container! Ich nutze ihn schon Jahre lang und wollte jetzt mal wieder updaten um Node 10 zu haben. nun muss ich IO-Broker Updaten und wollte dafür neuen js-controller installieren. Dabei ist mir aufgefallen dass ich npm nicht auch der cli nutzen kann.
```
root@ioBroker:/opt/iobroker# npm install iobroker.js-controller                 
sudo: Die Audit-Nachricht kann nicht gesendet werden: Unbekannter Fehler -1     
sudo: pam_open_session: Systemfehler                                            
sudo: Regelwerks-Plugin konnte Sitzung nicht initialisieren
```
Auch ein simples npm -v produziert diesen Fehler. Woran liegt das?

**Comment by buanet** [comment]
Wird leider alle paar Wochen gefragt....

Lass mich meine Glaskugel befragen... Synology Disk Station? Netzwerk im Host Modus? 
sudo ist das Problem... 

Hier ein bisschen Lesestoff: 
https://forum.iobroker.net/topic/4733/howto-anleitung-installation-iobroker-in-docker-auf-synology-diskstation/1626?page=82

https://forum.iobroker.net/post/352269

Workaround: Auf die Verwendung des "selben Netzwerks wie Host" (temporär) verzichten. Update durchführen und wenn es denn sein muss Netzwerk wieder zurück ändern. 

Alternativ: "iobroker backup" machen, neuen Container erstellen und backup zurückspielen. Seit v4.1.0 (2020-01-17) kann das auch direkt beim Containerstart erledigt werden.

MfG,
André
