### ISSUE TITLE
Known Issues, fehlende Ports

### ISSUE THREAD

**Issue by dwm66** [buanet/docker-iobroker#9]
Nach etwas Experimentieren was für die "Known Issues":

- den Container unbedingt mit "docker run --network host ... " starten, wenn man Sonos bzw. SayIt benutzen möchte - ist auch in der Anleitung so beschrieben.

- OHNE --network host (manchmal will man das ja :)) sollten ins Dockerfile bei den EXPOSE unbedingt noch die Ports 2000, 2001, 2010 und 8701 rein, das sind die RPC Rückkanäle der Homematic. Sonst starten zwar die hm-rpc Adapter, die CCU kann aber nichts zurück liefern.

Sonst läufts gut!
CU
Werner

**Comment by buanet** [comment]
Hallo Werner,

danke für das Feedback! Habe einen entsprechenden Teil im Tutorial eingefügt. Solltest du noch weitere Ports finden lass es mich gerne wissen. Ich werde dann die Liste entsprechend erweitern. 

MfG,
André
