### ISSUE TITLE
cc2531 Not accessible

### ISSUE THREAD

**Issue by thomas126** [buanet/docker-iobroker#90]
Hi guys,

First of all what a great docker image. Thanks a lot for all the work. I’m struggling to get my new zigbee stick working. I bought it preflashed and looked up the usb path. Added both paths: - USBDEVICES=/dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018E2737A-if00;/dev/ttyACM0

Tried to set either one in the Iobroker zigbee COM setting. Francly the Stick does not get recognised and I get errors such as: 818) Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open /dev/serial/by-id/usb-Texas_Instrumen...

Any advice?

Thanks in advance. Best regards
Tom

**Comment by buanet** [comment]
Please take a look at this:
https://buanet.de/2020/02/usb-devices-im-iobroker-docker-container-nutzen/

If that doesn't help, please provide some more informations about where and how you are running your docker container and what steps you made to get the usb-device working inside your container....

Regards,
André

**Comment by thomas126** [comment]
Tried to check for it. Why is the ACM0 not listed?

root@iobroker:/opt/iobroker# ls -al /dev/tty*
crw-rw-rw- 1 root root 5, 0 Apr 19 20:05 /dev/tty

**Comment by thomas126** [comment]
`version: '2'

services:
  iobroker:
    restart: always
    image: buanet/iobroker:latest
    container_name: iobroker
    hostname: iobroker
    ports:
      - "8081:8081"
    volumes:
      - ./data:/opt/iobroker
    environment:
      - USBDEVICES=/dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018E26C6B-if00;/dev/ttyACM0
      - SETGID=XXX
      - SETUID=XXXX
      - TZ=Europe/Berlin`

This is my setup code. Found the device by ls -la /dev/serial/by-id/:
`
total 0
drwxr-xr-x 2 root root 60 Apr 19 19:59 .
drwxr-xr-x 4 root root 80 Apr 19 19:59 ..
lrwxrwxrwx 1 root root 13 Apr 19 19:59 usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018E26C6B-if00 -> ../../ttyACM0`

Any help appreciated!

**Comment by thomas126** [comment]
Wow seems like I missed the devices part. Seems to be working now

**Comment by thomas126** [comment]
Okay so can I run it in host mode instead? What could solve it? Can you post a link for that please?
