### ISSUE TITLE
ffmpeg nicht enthalten

### ISSUE THREAD

**Issue by Tidle999** [buanet/docker-iobroker#93]
Hallo,

mit dem Cahngelog von v1.2.0 (2018-08-21) wurde ffmpeg in den Docker integriert. Es ist aber nicht enthalten, gibt es einen Tricke (Umgebungsvariable)?

Grüße

Tidle

**Comment by buanet** [comment]
Danke für den Hinweis. Das muss aus dem Changelog gestrichen werden. Mittlerweile ist das nicht mehr enthalten, weil es die ENV "PACKAGES" gibt. Darüber lässt sich das Paket nachinstallieren.

MfG,
André

**Comment by Tidle999** [comment]
Ach Perfekt, dann gehts darüber, danke für die extrem schnelle Antwort! =)
