### ISSUE TITLE
USB zmeeuzb1 

### ISSUE THREAD

**Issue by realrobgit** [buanet/docker-iobroker#95]
Hi, 
I would love to move from IOBROKER from Raspi 3 to my QNAP where I allready installed docker-iobroker.  But I do need ZWAVE protocol, which I realized on Raspi with Razberry (serial) On my QNAP I have an USB zmeeuzb1 and I tried to open it on the Iobroker Container. I see it running in the QNAP console, but I can´t access it on the container. Any idea what is my mistake?

**Comment by buanet** [comment]
Hi,
please take a look at the coming version of my readme.md file here: https://github.com/buanet/docker-iobroker/blob/dev/README.md
Especially the part: 
> Mounting USB device
> If you want to use a USB device within ioBroker inside your container don´t forget to [mount the device](https://docs.docker.com/engine/reference/commandline/run/#add-host-device-to-container---device) on container startup and use the environment variable "USBDEVICES".

Maybe this can help you too: https://buanet.de/2020/02/usb-devices-im-iobroker-docker-container-nutzen/
If you need some more support, please take a look at the ioBroker Forum Thread linked in readme.md. 

Regards, 
André
