### ISSUE TITLE
Question: Node.js v12.16.2 recomended by ioBroker

### ISSUE THREAD

**Issue by JoschaMiddendorf** [buanet/docker-iobroker#96]
Is there a reason to stick with node 10?

**Comment by buanet** [comment]
As I read at iobroker forum, node 12 will be recommended with js-controller 3. But js-controller 3 is only latest at the moment. When it comes to stable (default repo) I will update node within the image. But I can still make a beta version if needed...

Please correct me when I am wrong @Apollon77

Regards, 
André

**Comment by JoschaMiddendorf** [comment]
Thanks for your short clarification I don't see a need at the moment. I'm just in the process of switching over my extensive FHEM instalation, and still learning about ioBroker. Thank you also for providing and noticeably maintaining this docker image.

**Comment by Apollon77** [comment]
In fact we know that nodejs 12 is working good, see also https://forum.iobroker.net/topic/30561/status-iobroker-und-node-js-12-x thats why we decided to already update info adaoter to "recommend nodejs 12". In official communication it will come with js.controller 3.0 stable release.
