### ISSUE TITLE
Is there a upgrade plant for js-controller >= 2.0.0?

### ISSUE THREAD

**Issue by bbung** [buanet/docker-iobroker#97]
Hi,

some adapters need version >= 2.0.0 of js-controller. Is there a plan to upgrade this in the image?

Thanks and regards

PS: Thanks for providing this image.

**Comment by buanet** [comment]
As js-controller is part of the ioBroker and located inside the ioBroker folder you have to update it manually inside your container:
https://buanet.de/knowledge-base/steuerung-iob-ueber-kommandozeile/

Regards,
André

btw: if you download the actual image and set up a fresh & empty new container, js-controller will already be > v2.0.0...
