### ISSUE TITLE
ADB not working on newest version 4.2.0

### ISSUE THREAD

**Issue by zaunermax** [buanet/docker-iobroker#99]
So maybe this is not actionable for you or you don't want to do something about it (which is totally fine) but I noticed, that since you use the buster image adb is not working anymore, as linux fails to generate some keys. I am not entirely sure what the issue is, but reverting to 4.1.0 has resolved the issue.

This issue is just a heads up, just so you know, you can also close this right away, but changing to buster might have an impact for people, that install additional packages as well. In my case I use ADB to control my android TV, which might be a usecase for other people as well. 

As this repo is quite small, it would be no problem for me to just copy the scripts in here and modify them to make it work on my system. Thank you for this great docker image!

**Comment by buanet** [comment]
Hi,
I would like to check whats wrong and if I could do something. But to do so I need some more information about that issue. Do u have any log files or error messages for me?
Thank you.

Regards,
André

**Comment by buanet** [comment]
No more information provided.

**Comment by zaunermax** [comment]
Sorry, I completely forgot to answer :man_facepalming:

**Comment by zaunermax** [comment]
Sorry, I completely forgot to answer :man_facepalming: 

There seems to be a problem in keygeneration, which the previous image didn't seem to have.

The error messages are as follows:
```
List of devices attached
* daemon not running; starting now at tcp:5037
ADB server didn't ACK
Full server startup log: /tmp/adb.0.log
Server had pid: 2951
--- adb starting (pid 2951) ---
adb I 09-20 12:21:32  2951  2951 main.cpp:57] Android Debug Bridge version 1.0.39
adb I 09-20 12:21:32  2951  2951 main.cpp:57] Version 1:8.1.0+r23-5
adb I 09-20 12:21:32  2951  2951 main.cpp:57] Installed as /usr/lib/android-sdk/platform-tools/adb
adb I 09-20 12:21:32  2951  2951 main.cpp:57] 
adb I 09-20 12:21:32  2951  2951 adb_auth_host.cpp:416] adb_auth_init...
adb I 09-20 12:21:32  2951  2951 adb_auth_host.cpp:262] User key '/root/.android/adbkey' does not exist...
adb I 09-20 12:21:32  2951  2951 adb_auth_host.cpp:109] generate_key(/root/.android/adbkey)...

* failed to start daemon
error: cannot connect to daemon
```

I am going to try to find something, if anyone has the same problems with the current image.

**Comment by zaunermax** [comment]
The super weird part about this is, that the 4.1 image still works with adb and I cannot figure out why :thinking:
